var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="",fa;"undefined"!=typeof document&&document.currentScript&&(ea=document.currentScript.src);ea=0!==ea.indexOf("blob:")?ea.substr(0,ea.replace(/[?#].*/,"").lastIndexOf("/")+1):"";fa=a=>{document.title=a};var ha=g.print||console.log.bind(console),k=g.printErr||console.warn.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);
g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var ia;g.wasmBinary&&(ia=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&ja("no native wasm support detected");var ka,la=!1,ma,na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function oa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&na)return na.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function n(a,b){return a?oa(t,a,b):""}
function pa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function u(a,b,c){return pa(a,t,b,c)}
function qa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var v,t,ra,sa,x,y,z,ta;function ua(){var a=ka.buffer;g.HEAP8=v=new Int8Array(a);g.HEAP16=ra=new Int16Array(a);g.HEAP32=x=new Int32Array(a);g.HEAPU8=t=new Uint8Array(a);g.HEAPU16=sa=new Uint16Array(a);g.HEAPU32=y=new Uint32Array(a);g.HEAPF32=z=new Float32Array(a);g.HEAPF64=ta=new Float64Array(a)}var va,wa=[],xa=[],ya=[],Aa=[],Ba=[];
function Ca(){var a=g.preRun.shift();wa.unshift(a)}var Da=0,Ea=null,Fa=null;function ja(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";k(a);la=!0;ma=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ga(a){return a.startsWith("data:application/octet-stream;base64,")}var Ha;Ha="index.wasm";if(!Ga(Ha)){var Ia=Ha;Ha=g.locateFile?g.locateFile(Ia,ea):ea+Ia}
function Ja(a){try{if(a==Ha&&ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}catch(b){ja(b)}}function Ka(a){return ia||"function"!=typeof fetch?Promise.resolve().then(function(){return Ja(a)}):fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return Ja(a)})}
function La(a,b,c){return Ka(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){k("failed to asynchronously prepare wasm: "+d);ja(d)})}
function Ma(a,b){var c=Ha;ia||"function"!=typeof WebAssembly.instantiateStreaming||Ga(c)||"function"!=typeof fetch?La(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(e){k("wasm streaming compile failed: "+e);k("falling back to ArrayBuffer instantiation");return La(c,a,b)})})}
var A,B,Qa={99904:(a,b,c)=>{g.SDL2||(g.SDL2={});var d=g.SDL2;d.wi!==g.canvas&&(d.Yg=g.createContext(g.canvas,!1,!0),d.wi=g.canvas);if(d.w!==a||d.Li!==b||d.Ni!==d.Yg)d.image=d.Yg.createImageData(a,b),d.w=a,d.Li=b,d.Ni=d.Yg;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=x[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.yi!==a&&(d.xi=new Int32Array(a.buffer),d.zi=new Uint8Array(a.buffer),d.yi=
a),a=d.xi,c=a.length,a.set(x.subarray(b,b+c)),a=d.zi,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Yg.putImageData(d.image,0,0)},101373:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var h=f.getContext("2d");a=h.createImageData(a,b);b=a.data;e>>=2;var l=0,m;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(m=
b.length;l<m;){var q=x[e];b[l]=q&255;b[l+1]=q>>8&255;b[l+2]=q>>16&255;b[l+3]=q>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),m=b.length,b.set(x.subarray(e,e+m));h.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);u(c,d,c.length+1);return d},102362:a=>{g.canvas&&(g.canvas.style.cursor=n(a))},102445:()=>{g.canvas&&(g.canvas.style.cursor="none")},102514:()=>window.innerWidth,102544:()=>window.innerHeight,102575:()=>{Na("/saves");
Oa(E,"/saves");Pa(!0,function(a){a&&console.log(a)})},102693:()=>{Pa(!1,function(a){console.log(a)})}};function Ra(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Sa(a){for(;0<a.length;)a.shift()(g)}
var Ta=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ua=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ta(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Va=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Wa=a=>
{if("/"===a)return"/";a=Ua(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Xa(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}return()=>ja("randomDevice")}
function Ya(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ta(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function Za(a,b){var c=Array(qa(a)+1);a=pa(a,c,0,c.length);b&&(c.length=a);return c}var $a=[];function ab(a,b){$a[a]={input:[],Pg:[],rh:b};bb(a,cb)}
var cb={open:function(a){var b=$a[a.node.yh];if(!b)throw new H(43);a.Ng=b;a.seekable=!1},close:function(a){a.Ng.rh.Ch(a.Ng)},Ch:function(a){a.Ng.rh.Ch(a.Ng)},read:function(a,b,c,d){if(!a.Ng||!a.Ng.rh.di)throw new H(60);for(var e=0,f=0;f<d;f++){try{var h=a.Ng.rh.di(a.Ng)}catch(l){throw new H(29);}if(void 0===h&&0===e)throw new H(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Ng||!a.Ng.rh.Qh)throw new H(60);try{for(var e=0;e<d;e++)a.Ng.rh.Qh(a.Ng,
b[c+e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},db={di:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Za(b,!0)}return a.input.shift()},Qh:function(a,b){null===b||10===b?(ha(oa(a.Pg,0)),a.Pg=[]):0!=b&&a.Pg.push(b)},Ch:function(a){a.Pg&&0<a.Pg.length&&(ha(oa(a.Pg,0)),a.Pg=[])}},
eb={Qh:function(a,b){null===b||10===b?(k(oa(a.Pg,0)),a.Pg=[]):0!=b&&a.Pg.push(b)},Ch:function(a){a.Pg&&0<a.Pg.length&&(k(oa(a.Pg,0)),a.Pg=[])}},I={ah:null,Tg:function(){return I.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.ah||(I.ah={dir:{node:{Zg:I.Jg.Zg,Sg:I.Jg.Sg,th:I.Jg.th,Eh:I.Jg.Eh,li:I.Jg.li,Nh:I.Jg.Nh,Hh:I.Jg.Hh,Gh:I.Jg.Gh,Ih:I.Jg.Ih},stream:{ih:I.Lg.ih}},file:{node:{Zg:I.Jg.Zg,Sg:I.Jg.Sg},stream:{ih:I.Lg.ih,read:I.Lg.read,
write:I.Lg.write,Vh:I.Lg.Vh,fi:I.Lg.fi,hi:I.Lg.hi}},link:{node:{Zg:I.Jg.Zg,Sg:I.Jg.Sg,zh:I.Jg.zh},stream:{}},Zh:{node:{Zg:I.Jg.Zg,Sg:I.Jg.Sg},stream:fb}});c=gb(a,b,c,d);16384===(c.mode&61440)?(c.Jg=I.ah.dir.node,c.Lg=I.ah.dir.stream,c.Kg={}):32768===(c.mode&61440)?(c.Jg=I.ah.file.node,c.Lg=I.ah.file.stream,c.Mg=0,c.Kg=null):40960===(c.mode&61440)?(c.Jg=I.ah.link.node,c.Lg=I.ah.link.stream):8192===(c.mode&61440)&&(c.Jg=I.ah.Zh.node,c.Lg=I.ah.Zh.stream);c.timestamp=Date.now();a&&(a.Kg[b]=c,a.timestamp=
c.timestamp);return c},Hi:function(a){return a.Kg?a.Kg.subarray?a.Kg.subarray(0,a.Mg):new Uint8Array(a.Kg):new Uint8Array(0)},bi:function(a,b){var c=a.Kg?a.Kg.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Kg,a.Kg=new Uint8Array(b),0<a.Mg&&a.Kg.set(c.subarray(0,a.Mg),0))},Yi:function(a,b){if(a.Mg!=b)if(0==b)a.Kg=null,a.Mg=0;else{var c=a.Kg;a.Kg=new Uint8Array(b);c&&a.Kg.set(c.subarray(0,Math.min(b,a.Mg)));a.Mg=b}},Jg:{Zg:function(a){var b={};b.Bi=8192===(a.mode&
61440)?a.id:1;b.Ph=a.id;b.mode=a.mode;b.Ti=1;b.uid=0;b.Ki=0;b.yh=a.yh;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Mg:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.si=new Date(a.timestamp);b.Fh=new Date(a.timestamp);b.vi=new Date(a.timestamp);b.ti=4096;b.ui=Math.ceil(b.size/b.ti);return b},Sg:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&I.Yi(a,b.size)},th:function(){throw hb[44];},Eh:function(a,b,c,d){return I.createNode(a,
b,c,d)},li:function(a,b,c){if(16384===(a.mode&61440)){try{var d=ib(b,c)}catch(f){}if(d)for(var e in d.Kg)throw new H(55);}delete a.parent.Kg[a.name];a.parent.timestamp=Date.now();a.name=c;b.Kg[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Nh:function(a,b){delete a.Kg[b];a.timestamp=Date.now()},Hh:function(a,b){var c=ib(a,b),d;for(d in c.Kg)throw new H(55);delete a.Kg[b];a.timestamp=Date.now()},Gh:function(a){var b=[".",".."],c;for(c in a.Kg)a.Kg.hasOwnProperty(c)&&b.push(c);return b},Ih:function(a,
b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},zh:function(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},Lg:{read:function(a,b,c,d,e){var f=a.node.Kg;if(e>=a.node.Mg)return 0;a=Math.min(a.node.Mg-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===v.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Kg||a.Kg.subarray)){if(f)return a.Kg=b.subarray(c,c+d),a.Mg=d;if(0===
a.Mg&&0===e)return a.Kg=b.slice(c,c+d),a.Mg=d;if(e+d<=a.Mg)return a.Kg.set(b.subarray(c,c+d),e),d}I.bi(a,e+d);if(a.Kg.subarray&&b.subarray)a.Kg.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Kg[e+f]=b[c+f];a.Mg=Math.max(a.Mg,e+d);return d},ih:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Mg);if(0>b)throw new H(28);return b},Vh:function(a,b,c){I.bi(a.node,b+c);a.node.Mg=Math.max(a.node.Mg,b+c)},fi:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);
a=a.node.Kg;if(e&2||a.buffer!==v.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;ja();b=void 0;if(!b)throw new H(48);v.set(a,b)}else c=!1,b=a.byteOffset;return{yj:b,kj:c}},hi:function(a,b,c,d){I.Lg.write(a,b,0,d,c,!1);return 0}}},E={Bh:{},indexedDB:()=>{if("undefined"!=typeof indexedDB)return indexedDB;var a=null;"object"==typeof window&&(a=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB);a||ja("IDBFS used, but indexedDB not supported");
return a},oi:21,gh:"FILE_DATA",Tg:function(a){return I.Tg.apply(null,arguments)},mi:(a,b,c)=>{E.Ii(a,(d,e)=>{if(d)return c(d);E.Ji(a,(f,h)=>{if(f)return c(f);E.Vi(b?h:e,b?e:h,c)})})},zj:()=>{Object.values(E.Bh).forEach(a=>a.close());E.Bh={}},Gi:(a,b)=>{var c=E.Bh[a];if(c)return b(null,c);try{var d=E.indexedDB().open(a,E.oi)}catch(e){return b(e)}if(!d)return b("Unable to connect to IndexedDB");d.onupgradeneeded=e=>{var f=e.target.result;e=e.target.transaction;var h;f.objectStoreNames.contains(E.gh)?
h=e.objectStore(E.gh):h=f.createObjectStore(E.gh);h.indexNames.contains("timestamp")||h.createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=()=>{c=d.result;E.Bh[a]=c;b(null,c)};d.onerror=e=>{b(this.error);e.preventDefault()}},Ii:(a,b)=>{function c(l){return"."!==l&&".."!==l}function d(l){return m=>Ua(l+"/"+m)}var e={};for(a=jb(a.xh).filter(c).map(d(a.xh));a.length;){var f=a.pop();try{var h=lb(f)}catch(l){return b(l)}16384===(h.mode&61440)&&a.push.apply(a,jb(f).filter(c).map(d(f)));e[f]=
{timestamp:h.Fh}}return b(null,{type:"local",entries:e})},Ji:(a,b)=>{var c={};E.Gi(a.xh,(d,e)=>{if(d)return b(d);try{var f=e.transaction([E.gh],"readonly");f.onerror=h=>{b(this.error);h.preventDefault()};f.objectStore(E.gh).index("timestamp").openKeyCursor().onsuccess=h=>{h=h.target.result;if(!h)return b(null,{type:"remote",db:e,entries:c});c[h.primaryKey]={timestamp:h.key};h.continue()}}catch(h){return b(h)}})},Qi:(a,b)=>{try{var c=J(a).node;var d=lb(a)}catch(e){return b(e)}return 16384===(d.mode&
61440)?b(null,{timestamp:d.Fh,mode:d.mode}):32768===(d.mode&61440)?(c.Kg=I.Hi(c),b(null,{timestamp:d.Fh,mode:d.mode,contents:c.Kg})):b(Error("node type not supported"))},aj:(a,b,c)=>{try{if(16384===(b.mode&61440))for(var d=b.mode,e=a.split("/"),f="",h=0;h<e.length;++h){if(e[h]){f+="/"+e[h];try{Na(f,d)}catch(C){if(20!=C.Ug)throw C;}}}else if(32768===(b.mode&61440)){f=b.contents;d={Xh:!0};d.flags=d.flags||577;h=mb(a,d.flags,d.mode);if("string"==typeof f){var l=new Uint8Array(qa(f)+1),m=pa(f,l,0,l.length);
nb(h,l,0,m,void 0,d.Xh)}else if(ArrayBuffer.isView(f))nb(h,f,0,f.byteLength,void 0,d.Xh);else throw Error("Unsupported data type");ob(h)}else return c(Error("node type not supported"));var q=b.mode;var r="string"==typeof a?J(a,{oh:!0}).node:a;if(!r.Jg.Sg)throw new H(63);r.Jg.Sg(r,{mode:q&4095|r.mode&-4096,timestamp:Date.now()});var w=b.timestamp,G=b.timestamp,p=J(a,{oh:!0}).node;p.Jg.Sg(p,{timestamp:Math.max(w,G)})}catch(C){return c(C)}c(null)},Wi:(a,b)=>{try{var c=lb(a);if(16384===(c.mode&61440)){var d=
J(a,{parent:!0}).node,e=Wa(a),f=ib(d,e),h=pb(d,e,!0);if(h)throw new H(h);if(!d.Jg.Hh)throw new H(63);if(f.ph)throw new H(10);d.Jg.Hh(d,e);qb(f)}else if(32768===(c.mode&61440)){var l=J(a,{parent:!0}).node;if(!l)throw new H(44);var m=Wa(a),q=ib(l,m),r=pb(l,m,!1);if(r)throw new H(r);if(!l.Jg.Nh)throw new H(63);if(q.ph)throw new H(10);l.Jg.Nh(l,m);qb(q)}}catch(w){return b(w)}b(null)},Ri:(a,b,c)=>{a=a.get(b);a.onsuccess=d=>{c(null,d.target.result)};a.onerror=d=>{c(this.error);d.preventDefault()}},bj:(a,
b,c,d)=>{try{var e=a.put(c,b)}catch(f){d(f);return}e.onsuccess=()=>{d(null)};e.onerror=f=>{d(this.error);f.preventDefault()}},Xi:(a,b,c)=>{a=a.delete(b);a.onsuccess=()=>{c(null)};a.onerror=d=>{c(this.error);d.preventDefault()}},Vi:(a,b,c)=>{function d(r){if(r&&!l)return l=!0,c(r)}var e=0,f=[];Object.keys(a.entries).forEach(function(r){var w=a.entries[r],G=b.entries[r];G&&w.timestamp.getTime()==G.timestamp.getTime()||(f.push(r),e++)});var h=[];Object.keys(b.entries).forEach(function(r){a.entries[r]||
(h.push(r),e++)});if(!e)return c(null);var l=!1,m=("remote"===a.type?a.db:b.db).transaction([E.gh],"readwrite"),q=m.objectStore(E.gh);m.onerror=r=>{d(this.error);r.preventDefault()};m.oncomplete=()=>{l||c(null)};f.sort().forEach(r=>{"local"===b.type?E.Ri(q,r,(w,G)=>{if(w)return d(w);E.aj(r,G,d)}):E.Qi(r,(w,G)=>{if(w)return d(w);E.bj(q,r,G,d)})});h.sort().reverse().forEach(r=>{"local"===b.type?E.Wi(r,d):E.Xi(q,r,d)})}},rb=null,sb={},tb=[],ub=1,vb=null,wb=!0,H=null,hb={},xb=0,J=(a,b={})=>{a=Ya(a);if(!a)return{path:"",
node:null};b=Object.assign({ci:!0,Rh:0},b);if(8<b.Rh)throw new H(32);a=a.split("/").filter(h=>!!h);for(var c=rb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=ib(c,a[e]);d=Ua(d+"/"+a[e]);c.ph&&(!f||f&&b.ci)&&(c=c.ph.root);if(!f||b.oh)for(f=0;40960===(c.mode&61440);)if(c=yb(d),d=Ya(Va(d),c),c=J(d,{Rh:b.Rh+1}).node,40<f++)throw new H(32);}return{path:d,node:c}},zb=a=>{for(var b;;){if(a===a.parent)return a=a.Tg.xh,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},
Ab=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%vb.length},qb=a=>{var b=Ab(a.parent.id,a.name);if(vb[b]===a)vb[b]=a.qh;else for(b=vb[b];b;){if(b.qh===a){b.qh=a.qh;break}b=b.qh}},ib=(a,b)=>{var c;if(c=(c=Bb(a,"x"))?c:a.Jg.th?0:2)throw new H(c,a);for(c=vb[Ab(a.id,b)];c;c=c.qh){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Jg.th(a,b)},gb=(a,b,c,d)=>{a=new Cb(a,b,c,d);b=Ab(a.parent.id,a.name);a.qh=vb[b];return vb[b]=a},Db={r:0,"r+":2,w:577,"w+":578,
a:1089,"a+":1090},Eb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Bb=(a,b)=>{if(wb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Fb=(a,b)=>{try{return ib(a,b),20}catch(c){}return Bb(a,"wx")},pb=(a,b,c)=>{try{var d=ib(a,b)}catch(e){return e.Ug}if(a=Bb(a,"wx"))return a;if(c){if(16384!==(d.mode&61440))return 54;if(d===d.parent||"/"===zb(d))return 10}else if(16384===(d.mode&61440))return 31;return 0},
Gb=(a=0)=>{for(;4096>=a;a++)if(!tb[a])return a;throw new H(33);},Ib=(a,b)=>{Hb||(Hb=function(){this.Wg={}},Hb.prototype={},Object.defineProperties(Hb.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.Wg.flags},set:function(c){this.Wg.flags=c}},position:{get:function(){return this.Wg.position},set:function(c){this.Wg.position=c}}}));a=Object.assign(new Hb,a);b=Gb(b);a.eh=b;return tb[b]=a},fb={open:a=>{a.Lg=sb[a.node.yh].Lg;a.Lg.open&&
a.Lg.open(a)},ih:()=>{throw new H(70);}},bb=(a,b)=>{sb[a]={Lg:b}},Jb=()=>{for(var a=[],b=[rb.Tg];b.length;){var c=b.pop();a.push(c);b.push.apply(b,c.gi)}return a},Pa=(a,b)=>{function c(h){xb--;return b(h)}function d(h){if(h){if(!d.Ci)return d.Ci=!0,c(h)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);xb++;1<xb&&k("warning: "+xb+" FS.syncfs operations in flight at once, probably just doing extra work");var e=Jb(),f=0;e.forEach(h=>{if(!h.type.mi)return d(null);h.type.mi(h,a,d)})},Oa=(a,
b)=>{var c="/"===b,d=!b;if(c&&rb)throw new H(10);if(!c&&!d){var e=J(b,{ci:!1});b=e.path;e=e.node;if(e.ph)throw new H(10);if(16384!==(e.mode&61440))throw new H(54);}b={type:a,wj:{},xh:b,gi:[]};a=a.Tg(b);a.Tg=b;b.root=a;c?rb=a:e&&(e.ph=b,e.Tg&&e.Tg.gi.push(b))},Kb=(a,b,c)=>{var d=J(a,{parent:!0}).node;a=Wa(a);if(!a||"."===a||".."===a)throw new H(28);var e=Fb(d,a);if(e)throw new H(e);if(!d.Jg.Eh)throw new H(63);return d.Jg.Eh(d,a,b,c)},Na=(a,b)=>Kb(a,(void 0!==b?b:511)&1023|16384,0),Lb=(a,b,c)=>{"undefined"==
typeof c&&(c=b,b=438);Kb(a,b|8192,c)},Mb=(a,b)=>{if(!Ya(a))throw new H(44);var c=J(b,{parent:!0}).node;if(!c)throw new H(44);b=Wa(b);var d=Fb(c,b);if(d)throw new H(d);if(!c.Jg.Ih)throw new H(63);c.Jg.Ih(c,b,a)},jb=a=>{a=J(a,{oh:!0}).node;if(!a.Jg.Gh)throw new H(54);return a.Jg.Gh(a)},yb=a=>{a=J(a).node;if(!a)throw new H(44);if(!a.Jg.zh)throw new H(28);return Ya(zb(a.parent),a.Jg.zh(a))},lb=(a,b)=>{a=J(a,{oh:!b}).node;if(!a)throw new H(44);if(!a.Jg.Zg)throw new H(63);return a.Jg.Zg(a)},mb=(a,b,c)=>
{if(""===a)throw new H(44);if("string"==typeof b){var d=Db[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ua(a);try{e=J(a,{oh:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new H(20);}else e=Kb(a,c,0),d=!0;if(!e)throw new H(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new H(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&
("r"!==Eb(b)||b&512)?31:Bb(e,Eb(b)):44))throw new H(c);if(b&512&&!d){c=e;c="string"==typeof c?J(c,{oh:!0}).node:c;if(!c.Jg.Sg)throw new H(63);if(16384===(c.mode&61440))throw new H(31);if(32768!==(c.mode&61440))throw new H(28);if(d=Bb(c,"w"))throw new H(d);c.Jg.Sg(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Ib({node:e,path:zb(e),flags:b,seekable:!0,position:0,Lg:e.Lg,gj:[],error:!1});e.Lg.open&&e.Lg.open(e);!g.logReadFiles||b&1||(Nb||(Nb={}),a in Nb||(Nb[a]=1));return e},ob=a=>{if(null===a.eh)throw new H(8);
a.hh&&(a.hh=null);try{a.Lg.close&&a.Lg.close(a)}catch(b){throw b;}finally{tb[a.eh]=null}a.eh=null},Ob=(a,b,c)=>{if(null===a.eh)throw new H(8);if(!a.seekable||!a.Lg.ih)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.Lg.ih(a,b,c);a.gj=[];return a.position},nb=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new H(28);if(null===a.eh)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(16384===(a.node.mode&61440))throw new H(31);if(!a.Lg.write)throw new H(28);a.seekable&&a.flags&1024&&Ob(a,0,2);
var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new H(70);b=a.Lg.write(a,b,c,d,e,f);h||(a.position+=b);return b},Pb=()=>{H||(H=function(a,b){this.name="ErrnoError";this.node=b;this.Zi=function(c){this.Ug=c};this.Zi(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(a=>{hb[a]=new H(a);hb[a].stack="<generic error, no stack>"}))},Qb,Rb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Tb=(a,b,c)=>{a=Ua("/dev/"+a);var d=Rb(!!b,!!c);Sb||(Sb=
64);var e=Sb++<<8|0;bb(e,{open:f=>{f.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(f,h,l,m)=>{for(var q=0,r=0;r<m;r++){try{var w=b()}catch(G){throw new H(29);}if(void 0===w&&0===q)throw new H(6);if(null===w||void 0===w)break;q++;h[l+r]=w}q&&(f.node.timestamp=Date.now());return q},write:(f,h,l,m)=>{for(var q=0;q<m;q++)try{c(h[l+q])}catch(r){throw new H(29);}m&&(f.node.timestamp=Date.now());return q}});Lb(a,d,e)},Sb,Ub={},Hb,Nb,Vb=void 0;function Wb(){Vb+=4;return x[Vb-4>>2]}
function Xb(a){a=tb[a];if(!a)throw new H(8);return a}function Yb(a){return 0===a%4&&(0!==a%100||0===a%400)}var Zb=[0,31,60,91,121,152,182,213,244,274,305,335],$b=[0,31,59,90,120,151,181,212,243,273,304,334];function ac(a){var b=qa(a)+1,c=D(b);c&&pa(a,v,c,b);return c}
function bc(a,b){cc=a;dc=b;if(ec)if(fc||(fc=!0),0==a)gc=function(){var d=Math.max(0,hc+b-ic())|0;setTimeout(jc,d)};else if(1==a)gc=function(){kc(jc)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}gc=function(){setImmediate(jc)}}}var ic;ic=()=>performance.now();
function lc(a,b,c,d,e){!ec||ja("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");ec=a;mc=d;var f=nc;fc=!1;jc=function(){if(!la)if(0<oc.length){var h=Date.now(),l=oc.shift();l.qj(l.lj);if(pc){var m=pc,q=0==m%1?m-1:Math.floor(m);pc=l.nj?q:(8*m+(q+.5))/9}ha('main loop blocker "'+l.name+'" took '+(Date.now()-h)+" ms");g.setStatus&&(h=g.statusMessage||"Please wait...",
l=pc,m=qc.pj,l?l<m?g.setStatus(h+" ("+(m-l)+"/"+m+")"):g.setStatus(h):g.setStatus(""));f<nc||setTimeout(jc,0)}else f<nc||(rc=rc+1|0,1==cc&&1<dc&&0!=rc%dc?gc():(0==cc&&(hc=ic()),la||g.preMainLoop&&!1===g.preMainLoop()||(sc(a),g.postMainLoop&&g.postMainLoop()),f<nc||("object"==typeof SDL&&SDL.audio&&SDL.audio.Ui&&SDL.audio.Ui(),gc())))};e||(b&&0<b?bc(0,1E3/b):bc(1,1),gc());if(c)throw"unwind";}function tc(a){a instanceof Ra||"unwind"==a||da(1,a)}
function uc(a){ma=ma=a;if(!noExitRuntime){if(g.onExit)g.onExit(a);la=!0}da(a,new Ra(a))}function sc(a){if(!la)try{if(a(),!noExitRuntime)try{uc(ma)}catch(b){tc(b)}}catch(b){tc(b)}}function vc(a){setTimeout(function(){sc(a)},1E4)}function wc(a){xc||(xc={});xc[a]||(xc[a]=1,k(a))}var xc,fc=!1,gc=null,nc=0,ec=null,mc=0,cc=0,dc=0,rc=0,oc=[],qc={},hc,jc,pc,yc=!1,zc=!1,Ac=[];
function Bc(){function a(){zc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!Cc){Cc=!0;try{Dc=!0}catch(c){Dc=!1,k("warning: no blob constructor, cannot create blobs with mimetypes")}Ec="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Dc?null:k("warning: no BlobBuilder");Fc="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;g.ii||"undefined"!=typeof Fc||(k("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.ii=!0);g.preloadPlugins.push({canHandle:function(c){return!g.ii&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=null;if(Dc)try{h=new Blob([c],{type:Gc(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Gc(d)}))}catch(q){wc("Blob constructor present but fails: "+
q+"; falling back to blob builder")}h||(h=new Ec,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var l=Fc.createObjectURL(h),m=new Image;m.onload=()=>{m.complete||ja("Image "+d+" could not be decoded");var q=document.createElement("canvas");q.width=m.width;q.height=m.height;q.getContext("2d").drawImage(m,0,0);Fc.revokeObjectURL(l);e&&e(c)};m.onerror=()=>{ha("Image "+l+" could not be decoded");f&&f()};m.src=l}});g.preloadPlugins.push({canHandle:function(c){return!g.vj&&c.substr(-4)in{".ogg":1,
".wav":1,".mp3":1}},handle:function(c,d,e,f){function h(){m||(m=!0,e&&e(c))}function l(){m||(m=!0,new Audio,f&&f())}var m=!1;if(Dc){try{var q=new Blob([c],{type:Gc(d)})}catch(w){return l()}q=Fc.createObjectURL(q);var r=new Audio;r.addEventListener("canplaythrough",()=>h(r),!1);r.onerror=function(){if(!m){k("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var w="",G=0,p=0,C=0;C<c.length;C++)for(G=G<<8|c[C],p+=8;6<=p;){var F=G>>p-6&63;p-=6;w+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[F]}2==
p?(w+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(G&3)<<4],w+="=="):4==p&&(w+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(G&15)<<2],w+="=");r.src="data:audio/x-"+d.substr(-3)+";base64,"+w;h(r)}};r.src=q;vc(function(){h(r)})}else return l()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!zc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Hc(a,b,c,d){if(b&&g.Yg&&a==g.canvas)return g.Yg;var e;if(b){var f={antialias:!1,alpha:!1,Dh:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!=typeof Ic&&(e=Jc(a,f)))var l=Kc[e].dh}else l=a.getContext("2d");if(!l)return null;c&&(b||"undefined"==typeof K||ja("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Yg=l,b&&Lc(e),g.hj=b,Ac.forEach(function(m){m()}),Bc());return l}var Mc=!1,Nc=void 0,Oc=void 0;
function Pc(a,b){function c(){yc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Qc,Nc&&d.requestPointerLock(),yc=!0,Oc?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]|8388608),Rc(g.canvas),Sc()):Rc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Oc?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]&
-8388609),Rc(g.canvas),Sc()):Rc(d));if(g.onFullScreen)g.onFullScreen(yc);if(g.onFullscreen)g.onFullscreen(yc)}Nc=a;Oc=b;"undefined"==typeof Nc&&(Nc=!0);"undefined"==typeof Oc&&(Oc=!1);var d=g.canvas;Mc||(Mc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Qc(){if(!yc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Tc=0;function kc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Tc)Tc=b+1E3/60;else for(;b+2>=Tc;)Tc+=1E3/60;setTimeout(a,Math.max(Tc-b,0))}}
function Gc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Uc=[];function Sc(){var a=g.canvas;Uc.forEach(function(b){b(a.width,a.height)})}
function Rc(a,b,c){b&&c?(a.ij=b,a.Mi=c):(b=a.ij,c=a.Mi);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Oc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Cc,Dc,Ec,Fc,L=12288,Vc=!1,Wc=0,Xc=0,Yc=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},Zc={},$c;function ad(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function bd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function cd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var dd=1,ed=[],N=[],fd=[],gd=[],hd=[],O=[],P=[],Kc=[],Q=[],jd=[],kd=[],ld=[],md={},nd={},od=4;function R(a){pd||(pd=a)}function qd(a){for(var b=dd++,c=a.length;c<b;c++)a[c]=null;return b}function rd(a,b,c){for(var d="",e=0;e<a;++e){var f=c?x[c+4*e>>2]:-1;d+=n(x[b+4*e>>2],0>f?void 0:f)}return d}
function Jc(a,b){a.Wg||(a.Wg=a.getContext,a.getContext=function(d,e){e=a.Wg(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Dh?a.getContext("webgl2",b):a.getContext("webgl",b);return c?sd(c,b):0}function sd(a,b){var c=qd(Kc),d={rj:c,attributes:b,version:b.Dh,dh:a};a.canvas&&(a.canvas.sh=d);Kc[c]=d;("undefined"==typeof b.ai||b.ai)&&td(d);return c}function Lc(a){S=Kc[a];g.Yg=K=S&&S.dh;return!(a&&!K)}
function td(a){a||(a=S);if(!a.Oi){a.Oi=!0;var b=a.dh;ad(b);bd(b);cd(b);b.oj=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.tj=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Qg=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Qg)b.Qg=b.getExtension("EXT_disjoint_timer_query");b.uj=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var Ic={},pd,S,ud=[];function vd(a,b){ud.length=0;var c;for(b>>=2;c=t[a++];)b+=105!=c&b,ud.push(105==c?x[b]:ta[b++>>1]),++b;return ud}function wd(a){var b=xd();a=a();yd(b);return a}var zd=0;function Ad(){for(var a=Bd.length-1;0<=a;--a)Cd(a);Bd=[];Dd=[]}var Dd=[];
function Ed(a,b,c){function d(h,l){if(h.length!=l.length)return!1;for(var m in h)if(h[m]!=l[m])return!1;return!0}for(var e in Dd){var f=Dd[e];if(f.Th==a&&d(f.Wh,c))return}Dd.push({Th:a,ki:b,Wh:c});Dd.sort(function(h,l){return h.ki<l.ki})}function Fd(a){for(var b=0;b<Dd.length;++b)Dd[b].Th==a&&(Dd.splice(b,1),--b)}function Gd(){if(zd&&Hd.mh)for(var a=0;a<Dd.length;++a){var b=Dd[a];Dd.splice(a,1);--a;b.Th.apply(null,b.Wh)}}var Bd=[];
function Cd(a){var b=Bd[a];b.target.removeEventListener(b.Rg,b.Di,b.Vg);Bd.splice(a,1)}function Id(a){function b(d){++zd;Hd=a;Gd();a.$g(d);Gd();--zd}if(a.Xg)a.Di=b,a.target.addEventListener(a.Rg,b,a.Vg),Bd.push(a),Jd||(Aa.push(Ad),Jd=!0);else for(var c=0;c<Bd.length;++c)Bd[c].target==a.target&&Bd[c].Rg==a.Rg&&Cd(c--)}function Kd(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function Ld(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Md={},Jd,Hd,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd={},Yd=[0,document,window];function T(a){a=2<a?n(a):a;return Yd[a]||document.querySelector(a)}function Zd(a){return wd(function(){var b=$d(8),c=b+4,d=$d(a.id.length+1);u(a.id,d,a.id.length+1);if(d=T(d))x[b>>2]=d.width,x[c>>2]=d.height;return[x[b>>2],x[c>>2]]})}function ae(a,b,c){a=T(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function be(a,b,c){a.mj?wd(function(){var d=$d(a.id.length+1);u(a.id,d,a.id.length+1);ae(d,b,c)}):(a.width=b,a.height=c)}var ce=[];function U(a){var b=ce[a];b||(a>=ce.length&&(ce.length=a+1),ce[a]=b=va.get(a));return b}
function de(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),be(a,d,e),a.style.width=f,a.style.height=h,a.style.backgroundColor=l,m||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=m,a.style.paddingLeft=q,a.style.paddingRight=r,a.style.paddingTop=w,a.style.paddingBottom=G,a.style.marginLeft=p,a.style.marginRight=C,a.style.marginTop=
F,a.style.marginBottom=X,document.body.style.margin=za,document.documentElement.style.overflow=kb,document.body.scroll=Qe,a.style.fh=Re,a.sh&&a.sh.dh.viewport(0,0,d,e),Xd.Ah&&U(Xd.Ah)(37,0,Xd.Yh))}var c=Zd(a),d=c[0],e=c[1],f=a.style.width,h=a.style.height,l=a.style.backgroundColor,m=document.body.style.backgroundColor,q=a.style.paddingLeft,r=a.style.paddingRight,w=a.style.paddingTop,G=a.style.paddingBottom,p=a.style.marginLeft,C=a.style.marginRight,F=a.style.marginTop,X=a.style.marginBottom,za=document.body.style.margin,
kb=document.documentElement.style.overflow,Qe=document.body.scroll,Re=a.style.fh;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function ee(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function fe(a){return 0>Yd.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function ge(a,b){if(0!=b.Sh||0!=b.Oh){de(a);var c=b.$i?innerWidth:screen.width,d=b.$i?innerHeight:screen.height,e=fe(a),f=e.width;e=e.height;var h=Zd(a),l=h[0];h=h[1];3==b.Sh?(ee(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Sh&&(c*h<l*d?(f=h*c/l,ee(a,(d-f)/2,0),d=f):(f=l*d/h,ee(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Fi&&(a.style.fh="optimizeSpeed",
a.style.fh="-moz-crisp-edges",a.style.fh="-o-crisp-edges",a.style.fh="-webkit-optimize-contrast",a.style.fh="optimize-contrast",a.style.fh="crisp-edges",a.style.fh="pixelated");f=2==b.Oh?devicePixelRatio:1;0!=b.Oh&&(c=c*f|0,d=d*f|0,be(a,c,d),a.sh&&a.sh.dh.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Ld()?-3:-1;Xd=b;b.Ah&&U(b.Ah)(37,0,b.Yh);return 0}
function he(a){if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0}var ie=[];function V(a,b,c,d){for(var e=0;e<a;e++){var f=K[c](),h=f&&qd(d);f?(f.name=h,d[h]=f):R(1282);x[b+4*e>>2]=h}}function je(a,b,c,d,e,f,h,l){b=N[b];if(a=K[a](b,c))d=l&&u(a.name,l,d),e&&(x[e>>2]=d),f&&(x[f>>2]=a.size),h&&(x[h>>2]=a.type)}function ke(a,b){y[a>>2]=b;y[a+4>>2]=(b-y[a>>2])/4294967296}
function le(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=K.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>S.version){R(1282);return}d=2*(K.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>S.version){R(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=K.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:z[b+4*a>>2]=e[a];break;case 4:v[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){R(1280);
k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:R(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:ke(b,d);break;case 0:x[b>>2]=d;break;case 2:z[b>>2]=d;break;case 4:v[b>>0]=d?1:0}}else R(1281)}
function me(a,b,c,d){if(c){b=K.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:R(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{R(1280);return}break;default:R(1280);return}switch(d){case 1:ke(c,a);break;case 0:x[c>>2]=a;break;case 2:z[c>>2]=a;break;case 4:v[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else R(1281)}
function ne(a){var b=qa(a)+1,c=D(b);u(a,c,b);return c}function oe(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function pe(a){var b=a.lh,c=a.Mh,d;if(!b)for(a.lh=b={},a.ni={},d=0;d<K.getProgramParameter(a,35718);++d){var e=K.getActiveUniform(a,d);var f=e.name;e=e.size;var h=oe(f);h=0<h?f.slice(0,h):f;var l=a.Lh;a.Lh+=e;c[h]=[e,l];for(f=0;f<e;++f)b[l]=f,a.ni[l++]=h}}
function W(a){var b=K.$h;if(b){var c=b.lh[a];"number"==typeof c&&(b.lh[a]=c=K.getUniformLocation(b,b.ni[a]+(0<c?"["+c+"]":"")));return c}R(1282)}function qe(a,b,c,d){if(c)if(a=N[a],pe(a),a=K.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b]}else R(1281)}
function re(a,b,c,d){if(c)if(a=K.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b])}else R(1281)}function se(a){a-=5120;return 0==a?v:1==a?t:2==a?ra:4==a?x:6==a?z:5==a||28922==a||28520==a||30779==a||30782==a?y:sa}
function te(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function ue(a,b,c,d,e){a=se(a);var f=te(a),h=od;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}var ve=[],we=[];function xe(a,b){if(!Ld())return-1;a=T(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?zd&&Hd.mh?ge(a,b):b.Ai?(Ed(ge,1,[a,b]),1):-2:-3:-4}
function ye(a,b){var c={target:T(2),Rg:"beforeunload",Xg:b,$g:function(d=event){var e=U(b)(28,0,a);e&&(e=n(e));if(e)return d.preventDefault(),d.returnValue=e},Vg:!0};Id(c)}function ze(a,b,c,d,e,f){Nd||(Nd=D(256));a={target:T(a),Rg:f,Xg:d,$g:function(h=event){var l=h.target.id?h.target.id:"",m=Nd;u(Kd(h.target),m+0,128);u(l,m+128,128);U(d)(e,m,b)&&h.preventDefault()},Vg:c};Id(a)}
function Ae(a,b,c,d,e){Pd||(Pd=D(280));Id({target:a,Rg:e,Xg:d,$g:function(f=event){var h=Pd,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,m=!!l;x[h>>2]=m;x[h+4>>2]=Ld();var q=m?l:Od,r=q&&q.id?q.id:"";u(Kd(q),h+8,128);u(r,h+136,128);x[h+264>>2]=q?q.clientWidth:0;x[h+268>>2]=q?q.clientHeight:0;x[h+272>>2]=screen.width;x[h+276>>2]=screen.height;m&&(Od=l);U(d)(19,h,b)&&f.preventDefault()},Vg:c})}
function Be(a,b,c,d,e,f){Qd||(Qd=D(176));a={target:T(a),mh:!0,Rg:f,Xg:d,$g:function(h){var l=Qd;ta[l>>3]=h.timeStamp;var m=l>>2;x[m+2]=h.location;x[m+3]=h.ctrlKey;x[m+4]=h.shiftKey;x[m+5]=h.altKey;x[m+6]=h.metaKey;x[m+7]=h.repeat;x[m+8]=h.charCode;x[m+9]=h.keyCode;x[m+10]=h.which;u(h.key||"",l+44,32);u(h.code||"",l+76,32);u(h.char||"",l+108,32);u(h.locale||"",l+140,32);U(d)(e,l,b)&&h.preventDefault()},Vg:c};Id(a)}
function Ce(a,b,c){ta[a>>3]=b.timeStamp;a>>=2;x[a+2]=b.screenX;x[a+3]=b.screenY;x[a+4]=b.clientX;x[a+5]=b.clientY;x[a+6]=b.ctrlKey;x[a+7]=b.shiftKey;x[a+8]=b.altKey;x[a+9]=b.metaKey;ra[2*a+20]=b.button;ra[2*a+21]=b.buttons;x[a+11]=b.movementX;x[a+12]=b.movementY;c=fe(c);x[a+13]=b.clientX-c.left;x[a+14]=b.clientY-c.top}
function De(a,b,c,d,e,f){Rd||(Rd=D(72));a=T(a);Id({target:a,mh:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Rg:f,Xg:d,$g:function(h=event){Ce(Rd,h,a);U(d)(e,Rd,b)&&h.preventDefault()},Vg:c})}function Ee(a,b,c,d,e){Sd||(Sd=D(260));Id({target:a,Rg:e,Xg:d,$g:function(f=event){var h=Sd,l=document.pointerLockElement||document.pi||document.jj||document.ri;x[h>>2]=!!l;var m=l&&l.id?l.id:"";u(Kd(l),h+4,128);u(m,h+132,128);U(d)(20,h,b)&&f.preventDefault()},Vg:c})}
function Fe(a,b,c,d){Td||(Td=D(36));a=T(a);Id({target:a,Rg:"resize",Xg:d,$g:function(e=event){if(e.target==a){var f=document.body;if(f){var h=Td;x[h>>2]=e.detail;x[h+4>>2]=f.clientWidth;x[h+8>>2]=f.clientHeight;x[h+12>>2]=innerWidth;x[h+16>>2]=innerHeight;x[h+20>>2]=outerWidth;x[h+24>>2]=outerHeight;x[h+28>>2]=pageXOffset;x[h+32>>2]=pageYOffset;U(d)(10,h,b)&&e.preventDefault()}}},Vg:c})}
function Ge(a,b,c,d,e,f){Ud||(Ud=D(1696));a=T(a);Id({target:a,mh:"touchstart"==f||"touchend"==f,Rg:f,Xg:d,$g:function(h){for(var l,m={},q=h.touches,r=0;r<q.length;++r)l=q[r],l.ei=l.ji=0,m[l.identifier]=l;for(r=0;r<h.changedTouches.length;++r)l=h.changedTouches[r],l.ei=1,m[l.identifier]=l;for(r=0;r<h.targetTouches.length;++r)m[h.targetTouches[r].identifier].ji=1;q=Ud;ta[q>>3]=h.timeStamp;var w=q>>2;x[w+3]=h.ctrlKey;x[w+4]=h.shiftKey;x[w+5]=h.altKey;x[w+6]=h.metaKey;w+=7;var G=fe(a),p=0;for(r in m)if(l=
m[r],x[w]=l.identifier,x[w+1]=l.screenX,x[w+2]=l.screenY,x[w+3]=l.clientX,x[w+4]=l.clientY,x[w+5]=l.pageX,x[w+6]=l.pageY,x[w+7]=l.ei,x[w+8]=l.ji,x[w+9]=l.clientX-G.left,x[w+10]=l.clientY-G.top,w+=13,31<++p)break;x[q+8>>2]=p;U(d)(e,q,b)&&h.preventDefault()},Vg:c})}
function He(a,b,c){var d=Yd[1];Vd||(Vd=D(8));Id({target:d,Rg:"visibilitychange",Xg:c,$g:function(e=event){var f=Vd,h=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);x[f>>2]=document.hidden;x[f+4>>2]=h;U(c)(21,f,a)&&e.preventDefault()},Vg:b})}
function Ie(a,b,c,d){Wd||(Wd=D(104));Id({target:a,mh:!0,Rg:"wheel",Xg:d,$g:function(e=event){var f=Wd;Ce(f,e,a);ta[f+72>>3]=e.deltaX;ta[f+80>>3]=e.deltaY;ta[f+88>>3]=e.deltaZ;x[f+96>>2]=e.deltaMode;U(d)(9,f,b)&&e.preventDefault()},Vg:c})}var Je=["default","low-power","high-performance"],Ke=[null],Y=null,Le={};
function Me(){if(!Ne){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Le)void 0===Le[b]?delete a[b]:a[b]=Le[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ne=c}return Ne}var Ne,Oe=[31,29,31,30,31,30,31,31,30,31,30,31],Pe=[31,28,31,30,31,30,31,31,30,31,30,31];
function Se(a,b,c,d){function e(p,C,F){for(p="number"==typeof p?p.toString():p||"";p.length<C;)p=F[0]+p;return p}function f(p,C){return e(p,C,"0")}function h(p,C){function F(za){return 0>za?-1:0<za?1:0}var X;0===(X=F(p.getFullYear()-C.getFullYear()))&&0===(X=F(p.getMonth()-C.getMonth()))&&(X=F(p.getDate()-C.getDate()));return X}function l(p){switch(p.getDay()){case 0:return new Date(p.getFullYear()-1,11,29);case 1:return p;case 2:return new Date(p.getFullYear(),0,3);case 3:return new Date(p.getFullYear(),
0,2);case 4:return new Date(p.getFullYear(),0,1);case 5:return new Date(p.getFullYear()-1,11,31);case 6:return new Date(p.getFullYear()-1,11,30)}}function m(p){var C=p.jh;for(p=new Date((new Date(p.kh+1900,0,1)).getTime());0<C;){var F=p.getMonth(),X=(Yb(p.getFullYear())?Oe:Pe)[F];if(C>X-p.getDate())C-=X-p.getDate()+1,p.setDate(1),11>F?p.setMonth(F+1):(p.setMonth(0),p.setFullYear(p.getFullYear()+1));else{p.setDate(p.getDate()+C);break}}F=new Date(p.getFullYear()+1,0,4);C=l(new Date(p.getFullYear(),
0,4));F=l(F);return 0>=h(C,p)?0>=h(F,p)?p.getFullYear()+1:p.getFullYear():p.getFullYear()-1}var q=x[d+40>>2];d={ej:x[d>>2],dj:x[d+4>>2],Jh:x[d+8>>2],Uh:x[d+12>>2],Kh:x[d+16>>2],kh:x[d+20>>2],bh:x[d+24>>2],jh:x[d+28>>2],Bj:x[d+32>>2],cj:x[d+36>>2],fj:q?n(q):""};c=n(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in q)c=c.replace(new RegExp(r,"g"),q[r]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),G="January February March April May June July August September October November December".split(" ");q={"%a":function(p){return w[p.bh].substring(0,3)},"%A":function(p){return w[p.bh]},"%b":function(p){return G[p.Kh].substring(0,3)},"%B":function(p){return G[p.Kh]},
"%C":function(p){return f((p.kh+1900)/100|0,2)},"%d":function(p){return f(p.Uh,2)},"%e":function(p){return e(p.Uh,2," ")},"%g":function(p){return m(p).toString().substring(2)},"%G":function(p){return m(p)},"%H":function(p){return f(p.Jh,2)},"%I":function(p){p=p.Jh;0==p?p=12:12<p&&(p-=12);return f(p,2)},"%j":function(p){for(var C=0,F=0;F<=p.Kh-1;C+=(Yb(p.kh+1900)?Oe:Pe)[F++]);return f(p.Uh+C,3)},"%m":function(p){return f(p.Kh+1,2)},"%M":function(p){return f(p.dj,2)},"%n":function(){return"\n"},"%p":function(p){return 0<=
p.Jh&&12>p.Jh?"AM":"PM"},"%S":function(p){return f(p.ej,2)},"%t":function(){return"\t"},"%u":function(p){return p.bh||7},"%U":function(p){return f(Math.floor((p.jh+7-p.bh)/7),2)},"%V":function(p){var C=Math.floor((p.jh+7-(p.bh+6)%7)/7);2>=(p.bh+371-p.jh-2)%7&&C++;if(C)53==C&&(F=(p.bh+371-p.jh)%7,4==F||3==F&&Yb(p.kh)||(C=1));else{C=52;var F=(p.bh+7-p.jh-1)%7;(4==F||5==F&&Yb(p.kh%400-1))&&C++}return f(C,2)},"%w":function(p){return p.bh},"%W":function(p){return f(Math.floor((p.jh+7-(p.bh+6)%7)/7),2)},
"%y":function(p){return(p.kh+1900).toString().substring(2)},"%Y":function(p){return p.kh+1900},"%z":function(p){p=p.cj;var C=0<=p;p=Math.abs(p)/60;return(C?"+":"-")+String("0000"+(p/60*100+p%60)).slice(-4)},"%Z":function(p){return p.fj},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(r in q)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),q[r](d)));c=c.replace(/\0\0/g,"%");r=Za(c,!1);if(r.length>b)return 0;v.set(r,a);return r.length-1}
function Cb(a,b,c,d){a||(a=this);this.parent=a;this.Tg=a.Tg;this.ph=null;this.id=ub++;this.name=b;this.mode=c;this.Jg={};this.Lg={};this.yh=d}Object.defineProperties(Cb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Pb();vb=Array(4096);Oa(I,"/");Na("/tmp");Na("/home");Na("/home/web_user");
(()=>{Na("/dev");bb(259,{read:()=>0,write:(b,c,d,e)=>e});Lb("/dev/null",259);ab(1280,db);ab(1536,eb);Lb("/dev/tty",1280);Lb("/dev/tty1",1536);var a=Xa();Tb("random",a);Tb("urandom",a);Na("/dev/shm");Na("/dev/shm/tmp")})();(()=>{Na("/proc");var a=Na("/proc/self");Na("/proc/self/fd");Oa({Tg:()=>{var b=gb(a,"fd",16895,73);b.Jg={th:(c,d)=>{var e=tb[+d];if(!e)throw new H(8);c={parent:null,Tg:{xh:"fake"},Jg:{zh:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
g.requestFullscreen=function(a,b){Pc(a,b)};g.requestAnimationFrame=function(a){kc(a)};g.setCanvasSize=function(a,b,c){Rc(g.canvas,a,b);c||Sc()};g.pauseMainLoop=function(){gc=null;nc++};g.resumeMainLoop=function(){nc++;var a=cc,b=dc,c=ec;ec=null;lc(c,0,!1,mc,!0);bc(a,b);gc()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return Hc(a,b,c,d)};for(var K,Z=0;32>Z;++Z)ie.push(Array(Z));
var Te=new Float32Array(288);for(Z=0;288>Z;++Z)ve[Z]=Te.subarray(0,Z+1);var Ue=new Int32Array(288);for(Z=0;288>Z;++Z)we[Z]=Ue.subarray(0,Z+1);
var Xe={a:function(a,b,c,d){ja("Assertion failed: "+n(a)+", at: "+[b?n(b):"unknown filename",c,d?n(d):"unknown function"])},ja:function(a,b,c){Vb=c;try{var d=Xb(a);switch(b){case 0:var e=Wb();return 0>e?-28:Ib(d,e).eh;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Wb(),d.flags|=e,0;case 5:return e=Wb(),ra[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return x[Ve()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof Ub||"ErrnoError"!==f.name)throw f;return-f.Ug}},
La:function(a,b,c){try{var d=Xb(a);d.hh||(d.hh=jb(d.path));a=0;for(var e=Ob(d,0,1),f=Math.floor(e/280);f<d.hh.length&&a+280<=c;){var h=d.hh[f];if("."===h){var l=d.node.id;var m=4}else if(".."===h)l=J(d.path,{parent:!0}).node.id,m=4;else{var q=ib(d.node,h);l=q.id;m=8192===(q.mode&61440)?2:16384===(q.mode&61440)?4:40960===(q.mode&61440)?10:8}B=[l>>>0,(A=l,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[b+a>>2]=B[0];x[b+a+4>>
2]=B[1];B=[280*(f+1)>>>0,(A=280*(f+1),1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[b+a+8>>2]=B[0];x[b+a+12>>2]=B[1];ra[b+a+16>>1]=280;v[b+a+18>>0]=m;u(h,b+a+19,256);a+=280;f+=1}Ob(d,280*f,0);return a}catch(r){if("undefined"==typeof Ub||"ErrnoError"!==r.name)throw r;return-r.Ug}},Ua:function(a,b,c){Vb=c;try{var d=Xb(a);switch(b){case 21509:case 21505:return d.Ng?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Ng?
0:-59;case 21519:if(!d.Ng)return-59;var e=Wb();return x[e>>2]=0;case 21520:return d.Ng?-28:-59;case 21531:a=e=Wb();if(!d.Lg.Pi)throw new H(59);return d.Lg.Pi(d,b,a);case 21523:return d.Ng?0:-59;case 21524:return d.Ng?0:-59;default:return-28}}catch(f){if("undefined"==typeof Ub||"ErrnoError"!==f.name)throw f;return-f.Ug}},ka:function(a,b,c,d){Vb=d;try{b=n(b);var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":Xb(a).path;if(0==e.length)throw new H(44);b=Ua(f+"/"+e)}var h=d?Wb():0;return mb(b,c,
h).eh}catch(l){if("undefined"==typeof Ub||"ErrnoError"!==l.name)throw l;return-l.Ug}},Ia:function(a,b){try{a=n(a);a:{var c=lb;try{var d=c(a)}catch(m){if(m&&m.node&&Ua(a)!==Ua(zb(m.node))){var e=-54;break a}throw m;}x[b>>2]=d.Bi;x[b+8>>2]=d.Ph;x[b+12>>2]=d.mode;y[b+16>>2]=d.Ti;x[b+20>>2]=d.uid;x[b+24>>2]=d.Ki;x[b+28>>2]=d.yh;B=[d.size>>>0,(A=d.size,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[b+40>>2]=B[0];x[b+44>>2]=B[1];
x[b+48>>2]=4096;x[b+52>>2]=d.ui;var f=d.si.getTime(),h=d.Fh.getTime(),l=d.vi.getTime();B=[Math.floor(f/1E3)>>>0,(A=Math.floor(f/1E3),1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[b+56>>2]=B[0];x[b+60>>2]=B[1];y[b+64>>2]=f%1E3*1E3;B=[Math.floor(h/1E3)>>>0,(A=Math.floor(h/1E3),1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[b+72>>2]=B[0];x[b+76>>
2]=B[1];y[b+80>>2]=h%1E3*1E3;B=[Math.floor(l/1E3)>>>0,(A=Math.floor(l/1E3),1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[b+88>>2]=B[0];x[b+92>>2]=B[1];y[b+96>>2]=l%1E3*1E3;B=[d.Ph>>>0,(A=d.Ph,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[b+104>>2]=B[0];x[b+108>>2]=B[1];e=0}return e}catch(m){if("undefined"==typeof Ub||"ErrnoError"!==m.name)throw m;
return-m.Ug}},Va:function(){return!0},Oa:function(a,b){a=new Date(1E3*(y[a>>2]+4294967296*x[a+4>>2]));x[b>>2]=a.getSeconds();x[b+4>>2]=a.getMinutes();x[b+8>>2]=a.getHours();x[b+12>>2]=a.getDate();x[b+16>>2]=a.getMonth();x[b+20>>2]=a.getFullYear()-1900;x[b+24>>2]=a.getDay();x[b+28>>2]=(Yb(a.getFullYear())?Zb:$b)[a.getMonth()]+a.getDate()-1|0;x[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();x[b+32>>
2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},Na:function(a,b,c){function d(m){return(m=m.toTimeString().match(/\(([A-Za-z ]+)\)$/))?m[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),h=new Date(e,6,1);e=f.getTimezoneOffset();var l=h.getTimezoneOffset();y[a>>2]=60*Math.max(e,l);x[b>>2]=Number(e!=l);a=d(f);b=d(h);a=ac(a);b=ac(b);l<e?(y[c>>2]=a,y[c+4>>2]=b):(y[c>>2]=b,y[c+4>>2]=a)},c:function(){ja("")},tg:function(a){navigator.clipboard.writeText(n(a))},gc:function(a){if(12448==a)return L=
12288,1;L=12300;return 0},ue:function(a,b,c,d,e){if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=x[b>>2];if(12321==a)M.alpha=0<x[b+4>>2];else if(12325==a)M.depth=0<x[b+4>>2];else if(12326==a)M.stencil=0<x[b+4>>2];else if(12337==a)a=x[b+4>>2],M.antialias=0<a;else if(12338==a)a=x[b+4>>2],M.antialias=1==a;else if(12544==a)M.sj=12547!=x[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(x[e>>2]=1),c&&0<d&&(x[c>>2]=62002),L=12288,c=1):(L=12300,c=0)}return c},_d:function(a,b,c,d){if(62E3!=a)return L=12296,0;for(a=
1;;){b=x[d>>2];if(12440==b)a=x[d+4>>2];else if(12344==b)break;else return L=12292,0;d+=8}if(2>a||3<a)return L=12293,0;M.Dh=a-1;M.Si=0;$c=Jc(g.canvas,M);if(0!=$c)return L=12288,Lc($c),g.hj=!0,Ac.forEach(function(e){e()}),Lc(null),62004;L=12297;return 0},Ed:function(a,b){if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},Pd:function(a,b){if(62E3!=a)return L=12296,0;if(62004!=b)return L=12294,0;a=$c;S===Kc[a]&&(S=null);if("object"==typeof Md)for(var c=Kc[a].dh.canvas,d=0;d<
Bd.length;++d)Bd[d].target!=c||Cd(d--);Kc[a]&&Kc[a].dh.canvas&&(Kc[a].dh.canvas.sh=void 0);Kc[a]=null;L=12288;Wc==b&&(Wc=0);return 1},td:function(a,b){if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;Xc==b&&(Xc=0);Yc==b&&(Yc=0);L=12288;return 1},je:function(a,b,c,d){if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return x[d>>2]=M.alpha?32:24,1;case 12321:return x[d>>2]=M.alpha?8:0,1;case 12322:return x[d>>2]=8,1;case 12323:return x[d>>
2]=8,1;case 12324:return x[d>>2]=8,1;case 12325:return x[d>>2]=M.depth?24:0,1;case 12326:return x[d>>2]=M.stencil?8:0,1;case 12327:return x[d>>2]=12344,1;case 12328:return x[d>>2]=62002,1;case 12329:return x[d>>2]=0,1;case 12330:return x[d>>2]=4096,1;case 12331:return x[d>>2]=16777216,1;case 12332:return x[d>>2]=4096,1;case 12333:return x[d>>2]=0,1;case 12334:return x[d>>2]=0,1;case 12335:return x[d>>2]=12344,1;case 12337:return x[d>>2]=M.antialias?4:0,1;case 12338:return x[d>>2]=M.antialias?1:0,
1;case 12339:return x[d>>2]=4,1;case 12340:return x[d>>2]=12344,1;case 12341:case 12342:case 12343:return x[d>>2]=-1,1;case 12345:case 12346:return x[d>>2]=0,1;case 12347:return x[d>>2]=0,1;case 12348:return x[d>>2]=1;case 12349:case 12350:return x[d>>2]=0,1;case 12351:return x[d>>2]=12430,1;case 12352:return x[d>>2]=4,1;case 12354:return x[d>>2]=0,1;default:return L=12292,0}},ma:function(){L=12288;return 62E3},Mb:function(){return L},Qe:function(a,b,c){if(62E3!=a)return L=12296,0;b&&(x[b>>2]=1);
c&&(x[c>>2]=4);Vc=!0;L=12288;return 1},id:function(a,b,c,d){if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return L=12301,0;Lc(d?$c:null);Wc=d;Yc=b;Xc=c;L=12288;return 1},Xb:function(a,b){if(62E3!=a)return L=12296,0;L=12288;if(Zc[b])return Zc[b];switch(b){case 12371:a=ac("Emscripten");break;case 12372:a=ac("1.4 Emscripten EGL");break;case 12373:a=ac("");break;case 12429:a=ac("OpenGL_ES");break;default:return L=12300,0}return Zc[b]=a},Zc:function(){if(Vc)if(g.Yg)if(g.Yg.isContextLost())L=
12302;else return L=12288,1;else L=12290;else L=12289;return 0},Oc:function(a,b){if(62E3!=a)return L=12296,0;0==b?bc(0,0):bc(1,b);L=12288;return 1},Fe:function(a){if(62E3!=a)return L=12296,0;Yc=Xc=Wc=0;Vc=!1;L=12288;return 1},rc:function(){L=12288;return 1},Cc:function(){L=12288;return 1},na:function(a,b,c){b=vd(b,c);return Qa[a].apply(null,b)},p:function(a,b,c){b=vd(b,c);return Qa[a].apply(null,b)},A:function(){return Date.now()},Ea:function(){if(!Ld())return-1;Fd(ge);var a=Yd[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},d:function(){Fd(he);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},o:function(){return devicePixelRatio},n:function(a,b,c){a=T(a);if(!a)return-4;a=fe(a);ta[b>>3]=a.width;ta[c>>3]=a.height;return 0},z:ic,Bb:function(a,b){x[a>>2]=screen.width;x[b>>2]=screen.height},Wf:function(a){K.activeTexture(a)},Vf:function(a,b){K.attachShader(N[a],O[b])},
Mc:function(a,b){K.beginQuery(a,Q[b])},lg:function(a,b){K.Qg.beginQueryEXT(a,Q[b])},qc:function(a){K.beginTransformFeedback(a)},Uf:function(a,b,c){K.bindAttribLocation(N[a],b,n(c))},Tf:function(a,b){35051==a?K.nh=b:35052==a&&(K.Og=b);K.bindBuffer(a,ed[b])},nc:function(a,b,c){K.bindBufferBase(a,b,ed[c])},oc:function(a,b,c,d,e){K.bindBufferRange(a,b,ed[c],d,e)},Sf:function(a,b){K.bindFramebuffer(a,fd[b])},Rf:function(a,b){K.bindRenderbuffer(a,gd[b])},rb:function(a,b){K.bindSampler(a,jd[b])},Qf:function(a,
b){K.bindTexture(a,hd[b])},jb:function(a,b){K.bindTransformFeedback(a,kd[b])},wc:function(a){K.bindVertexArray(P[a])},cg:function(a){K.bindVertexArray(P[a])},Pf:function(a,b,c,d){K.blendColor(a,b,c,d)},Of:function(a){K.blendEquation(a)},Nf:function(a,b){K.blendEquationSeparate(a,b)},Mf:function(a,b){K.blendFunc(a,b)},Lf:function(a,b,c,d){K.blendFuncSeparate(a,b,c,d)},zc:function(a,b,c,d,e,f,h,l,m,q){K.blitFramebuffer(a,b,c,d,e,f,h,l,m,q)},Kf:function(a,b,c,d){2<=S.version?c&&b?K.bufferData(a,t,d,
c,b):K.bufferData(a,b,d):K.bufferData(a,c?t.subarray(c,c+b):b,d)},Jf:function(a,b,c,d){2<=S.version?c&&K.bufferSubData(a,b,t,d,c):K.bufferSubData(a,b,t.subarray(d,d+c))},If:function(a){return K.checkFramebufferStatus(a)},Hf:function(a){K.clear(a)},Qb:function(a,b,c,d){K.clearBufferfi(a,b,c,d)},Rb:function(a,b,c){K.clearBufferfv(a,b,z,c>>2)},Tb:function(a,b,c){K.clearBufferiv(a,b,x,c>>2)},Sb:function(a,b,c){K.clearBufferuiv(a,b,y,c>>2)},Gf:function(a,b,c,d){K.clearColor(a,b,c,d)},Ff:function(a){K.clearDepth(a)},
Ef:function(a){K.clearStencil(a)},Ab:function(a,b,c,d){return K.clientWaitSync(ld[a],b,(c>>>0)+4294967296*d)},Df:function(a,b,c,d){K.colorMask(!!a,!!b,!!c,!!d)},Cf:function(a){K.compileShader(O[a])},Bf:function(a,b,c,d,e,f,h,l){2<=S.version?K.Og||!h?K.compressedTexImage2D(a,b,c,d,e,f,h,l):K.compressedTexImage2D(a,b,c,d,e,f,t,l,h):K.compressedTexImage2D(a,b,c,d,e,f,l?t.subarray(l,l+h):null)},Sc:function(a,b,c,d,e,f,h,l,m){K.Og?K.compressedTexImage3D(a,b,c,d,e,f,h,l,m):K.compressedTexImage3D(a,b,c,
d,e,f,h,t,m,l)},Af:function(a,b,c,d,e,f,h,l,m){2<=S.version?K.Og||!l?K.compressedTexSubImage2D(a,b,c,d,e,f,h,l,m):K.compressedTexSubImage2D(a,b,c,d,e,f,h,t,m,l):K.compressedTexSubImage2D(a,b,c,d,e,f,h,m?t.subarray(m,m+l):null)},Rc:function(a,b,c,d,e,f,h,l,m,q,r){K.Og?K.compressedTexSubImage3D(a,b,c,d,e,f,h,l,m,q,r):K.compressedTexSubImage3D(a,b,c,d,e,f,h,l,m,t,r,q)},Ob:function(a,b,c,d,e){K.copyBufferSubData(a,b,c,d,e)},zf:function(a,b,c,d,e,f,h,l){K.copyTexImage2D(a,b,c,d,e,f,h,l)},yf:function(a,
b,c,d,e,f,h,l){K.copyTexSubImage2D(a,b,c,d,e,f,h,l)},Tc:function(a,b,c,d,e,f,h,l,m){K.copyTexSubImage3D(a,b,c,d,e,f,h,l,m)},xf:function(){var a=qd(N),b=K.createProgram();b.name=a;b.wh=b.uh=b.vh=0;b.Lh=1;N[a]=b;return a},wf:function(a){var b=qd(O);O[b]=K.createShader(a);return b},vf:function(a){K.cullFace(a)},uf:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=ed[d];e&&(K.deleteBuffer(e),e.name=0,ed[d]=null,d==K.nh&&(K.nh=0),d==K.Og&&(K.Og=0))}},tf:function(a,b){for(var c=0;c<a;++c){var d=x[b+
4*c>>2],e=fd[d];e&&(K.deleteFramebuffer(e),e.name=0,fd[d]=null)}},sf:function(a){if(a){var b=N[a];b?(K.deleteProgram(b),b.name=0,N[a]=null):R(1281)}},Pc:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Q[d];e&&(K.deleteQuery(e),Q[d]=null)}},ng:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Q[d];e&&(K.Qg.deleteQueryEXT(e),Q[d]=null)}},rf:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=gd[d];e&&(K.deleteRenderbuffer(e),e.name=0,gd[d]=null)}},tb:function(a,b){for(var c=0;c<a;c++){var d=
x[b+4*c>>2],e=jd[d];e&&(K.deleteSampler(e),e.name=0,jd[d]=null)}},qf:function(a){if(a){var b=O[a];b?(K.deleteShader(b),O[a]=null):R(1281)}},Cb:function(a){if(a){var b=ld[a];b?(K.deleteSync(b),b.name=0,ld[a]=null):R(1281)}},pf:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=hd[d];e&&(K.deleteTexture(e),e.name=0,hd[d]=null)}},ib:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=kd[d];e&&(K.deleteTransformFeedback(e),e.name=0,kd[d]=null)}},vc:function(a,b){for(var c=0;c<a;c++){var d=x[b+
4*c>>2];K.deleteVertexArray(P[d]);P[d]=null}},bg:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];K.deleteVertexArray(P[d]);P[d]=null}},of:function(a){K.depthFunc(a)},nf:function(a){K.depthMask(!!a)},mf:function(a,b){K.depthRange(a,b)},lf:function(a,b){K.detachShader(N[a],O[b])},kf:function(a){K.disable(a)},jf:function(a){K.disableVertexAttribArray(a)},hf:function(a,b,c){K.drawArrays(a,b,c)},Gb:function(a,b,c,d){K.drawArraysInstanced(a,b,c,d)},Zf:function(a,b,c,d){K.drawArraysInstanced(a,b,c,
d)},bd:function(a,b,c,d){K.drawArraysInstanced(a,b,c,d)},cd:function(a,b,c,d){K.drawArraysInstanced(a,b,c,d)},Wa:function(a,b,c,d){K.drawArraysInstanced(a,b,c,d)},Ic:function(a,b){for(var c=ie[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];K.drawBuffers(c)},Yc:function(a,b){for(var c=ie[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];K.drawBuffers(c)},_f:function(a,b){for(var c=ie[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];K.drawBuffers(c)},gf:function(a,b,c,d){K.drawElements(a,b,c,d)},Fb:function(a,b,c,d,e){K.drawElementsInstanced(a,b,c,
d,e)},Yf:function(a,b,c,d,e){K.drawElementsInstanced(a,b,c,d,e)},_c:function(a,b,c,d,e){K.drawElementsInstanced(a,b,c,d,e)},$c:function(a,b,c,d,e){K.drawElementsInstanced(a,b,c,d,e)},ad:function(a,b,c,d,e){K.drawElementsInstanced(a,b,c,d,e)},Wc:function(a,b,c,d,e,f){K.drawElements(a,d,e,f)},ff:function(a){K.enable(a)},ef:function(a){K.enableVertexAttribArray(a)},Lc:function(a){K.endQuery(a)},kg:function(a){K.Qg.endQueryEXT(a)},pc:function(){K.endTransformFeedback()},Eb:function(a,b){return(a=K.fenceSync(a,
b))?(b=qd(ld),a.name=b,ld[b]=a,b):0},df:function(){K.finish()},cf:function(){K.flush()},bf:function(a,b,c,d){K.framebufferRenderbuffer(a,b,c,gd[d])},af:function(a,b,c,d,e){K.framebufferTexture2D(a,b,c,hd[d],e)},xc:function(a,b,c,d,e){K.framebufferTextureLayer(a,b,hd[c],d,e)},$e:function(a){K.frontFace(a)},_e:function(a,b){V(a,b,"createBuffer",ed)},Ye:function(a,b){V(a,b,"createFramebuffer",fd)},Qc:function(a,b){V(a,b,"createQuery",Q)},og:function(a,b){for(var c=0;c<a;c++){var d=K.Qg.createQueryEXT();
if(!d){for(R(1282);c<a;)x[b+4*c++>>2]=0;break}var e=qd(Q);d.name=e;Q[e]=d;x[b+4*c>>2]=e}},Xe:function(a,b){V(a,b,"createRenderbuffer",gd)},ub:function(a,b){V(a,b,"createSampler",jd)},We:function(a,b){V(a,b,"createTexture",hd)},hb:function(a,b){V(a,b,"createTransformFeedback",kd)},uc:function(a,b){V(a,b,"createVertexArray",P)},ag:function(a,b){V(a,b,"createVertexArray",P)},Ze:function(a){K.generateMipmap(a)},Ve:function(a,b,c,d,e,f,h){je("getActiveAttrib",a,b,c,d,e,f,h)},Ue:function(a,b,c,d,e,f,h){je("getActiveUniform",
a,b,c,d,e,f,h)},Ib:function(a,b,c,d,e){a=N[a];if(a=K.getActiveUniformBlockName(a,b))e&&0<c?(c=u(a,e,c),d&&(x[d>>2]=c)):d&&(x[d>>2]=0)},Jb:function(a,b,c,d){if(d)if(a=N[a],35393==c)c=K.getActiveUniformBlockName(a,b),x[d>>2]=c.length+1;else{if(a=K.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)x[d+4*c>>2]=a[c];else x[d>>2]=a}else R(1281)},Lb:function(a,b,c,d,e){if(e)if(0<b&&0==c)R(1281);else{a=N[a];for(var f=[],h=0;h<b;h++)f.push(x[c+4*h>>2]);if(a=K.getActiveUniforms(a,
f,d))for(b=a.length,h=0;h<b;h++)x[e+4*h>>2]=a[h]}else R(1281)},Te:function(a,b,c,d){a=K.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=O.indexOf(a[b])},Se:function(a,b){return K.getAttribLocation(N[a],n(b))},Re:function(a,b){le(a,b,4)},vb:function(a,b,c){c?ke(c,K.getBufferParameter(a,b)):R(1281)},Pe:function(a,b,c){c?x[c>>2]=K.getBufferParameter(a,b):R(1281)},Oe:function(){var a=K.getError()||pd;pd=0;return a},Ne:function(a,b){le(a,b,2)},bc:function(a,b){return K.getFragDataLocation(N[a],
n(b))},Me:function(a,b,c,d){a=K.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},wb:function(a,b,c){me(a,b,c,1)},yb:function(a,b){le(a,b,1)},sc:function(a,b,c){me(a,b,c,0)},Le:function(a,b){le(a,b,0)},Ya:function(a,b,c,d,e){if(0>d)R(1281);else if(e){if(a=K.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)x[e+4*b>>2]=a[b]}else R(1281)},db:function(){R(1282)},Je:function(a,b,c,d){a=K.getProgramInfoLog(N[a]);
null===a&&(a="(unknown error)");b=0<b&&d?u(a,d,b):0;c&&(x[c>>2]=b)},Ke:function(a,b,c){if(c)if(a>=dd)R(1281);else if(a=N[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b){if(!a.wh)for(b=0;b<K.getProgramParameter(a,35718);++b)a.wh=Math.max(a.wh,K.getActiveUniform(a,b).name.length+1);x[c>>2]=a.wh}else if(35722==b){if(!a.uh)for(b=0;b<K.getProgramParameter(a,35721);++b)a.uh=Math.max(a.uh,K.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.uh}else if(35381==
b){if(!a.vh)for(b=0;b<K.getProgramParameter(a,35382);++b)a.vh=Math.max(a.vh,K.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.vh}else x[c>>2]=K.getProgramParameter(a,b);else R(1281)},eg:function(a,b,c){if(c){a=Q[a];b=2>S.version?K.Qg.getQueryObjectEXT(a,b):K.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;ke(c,d)}else R(1281)},hg:function(a,b,c){if(c){a=K.Qg.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else R(1281)},dg:function(a,b,c){if(c){a=Q[a];b=2>
S.version?K.Qg.getQueryObjectEXT(a,b):K.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;ke(c,d)}else R(1281)},Jc:function(a,b,c){if(c){a=K.getQueryParameter(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else R(1281)},fg:function(a,b,c){if(c){a=K.Qg.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else R(1281)},Kc:function(a,b,c){c?x[c>>2]=K.getQuery(a,b):R(1281)},ig:function(a,b,c){c?x[c>>2]=K.Qg.getQueryEXT(a,b):R(1281)},Ie:function(a,b,c){c?x[c>>2]=
K.getRenderbufferParameter(a,b):R(1281)},lb:function(a,b,c){c?z[c>>2]=K.getSamplerParameter(jd[a],b):R(1281)},mb:function(a,b,c){c?x[c>>2]=K.getSamplerParameter(jd[a],b):R(1281)},Ge:function(a,b,c,d){a=K.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?u(a,d,b):0;c&&(x[c>>2]=b)},Ee:function(a,b,c,d){a=K.getShaderPrecisionFormat(a,b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},De:function(a,b,c,d){if(a=K.getShaderSource(O[a]))b=0<b&&d?u(a,d,b):0,c&&(x[c>>2]=b)},He:function(a,
b,c){c?35716==b?(a=K.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(O[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=K.getShaderParameter(O[a],b):R(1281)},Ce:function(a){var b=md[a];if(!b){switch(a){case 7939:b=K.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=ne(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=K.getParameter(a))||R(1280);b=b&&ne(b);break;case 7938:b=K.getParameter(7938);b=2<=S.version?
"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=ne(b);break;case 35724:b=K.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ne(b);break;default:R(1280)}md[a]=b}return b},Pb:function(a,b){if(2>S.version)return R(1282),0;var c=nd[a];if(c)return 0>b||b>=c.length?(R(1281),0):c[b];switch(a){case 7939:return c=K.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=
c.map(function(d){return ne(d)}),c=nd[a]=c,0>b||b>=c.length?(R(1281),0):c[b];default:return R(1280),0}},xb:function(a,b,c,d,e){0>c?R(1281):e?(a=K.getSyncParameter(ld[a],b),null!==a&&(x[e>>2]=a,d&&(x[d>>2]=1))):R(1281)},Be:function(a,b,c){c?z[c>>2]=K.getTexParameter(a,b):R(1281)},Ae:function(a,b,c){c?x[c>>2]=K.getTexParameter(a,b):R(1281)},lc:function(a,b,c,d,e,f,h){a=N[a];if(a=K.getTransformFeedbackVarying(a,b))h&&0<c?(c=u(a.name,h,c),d&&(x[d>>2]=c)):d&&(x[d>>2]=0),e&&(x[e>>2]=a.size),f&&(x[f>>2]=
a.type)},Kb:function(a,b){return K.getUniformBlockIndex(N[a],n(b))},Nb:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))R(1281);else{a=N[a];for(var e=[],f=0;f<b;f++)e.push(n(x[c+4*f>>2]));if(a=K.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)x[d+4*f>>2]=a[f]}else R(1281)},xe:function(a,b){b=n(b);if(a=N[a]){pe(a);var c=a.lh,d=0,e=b,f=oe(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Mh[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else R(1281);return-1},ze:function(a,
b,c){qe(a,b,c,2)},ye:function(a,b,c){qe(a,b,c,0)},cc:function(a,b,c){qe(a,b,c,0)},jc:function(a,b,c){re(a,b,c,0)},ic:function(a,b,c){re(a,b,c,0)},te:function(a,b,c){c?x[c>>2]=K.getVertexAttribOffset(a,b):R(1281)},we:function(a,b,c){re(a,b,c,2)},ve:function(a,b,c){re(a,b,c,5)},se:function(a,b){K.hint(a,b)},ab:function(a,b,c){for(var d=ie[b],e=0;e<b;e++)d[e]=x[c+4*e>>2];K.invalidateFramebuffer(a,d)},$a:function(a,b,c,d,e,f,h){for(var l=ie[b],m=0;m<b;m++)l[m]=x[c+4*m>>2];K.invalidateSubFramebuffer(a,
l,d,e,f,h)},re:function(a){return(a=ed[a])?K.isBuffer(a):0},qe:function(a){return K.isEnabled(a)},pe:function(a){return(a=fd[a])?K.isFramebuffer(a):0},oe:function(a){return(a=N[a])?K.isProgram(a):0},Nc:function(a){return(a=Q[a])?K.isQuery(a):0},mg:function(a){return(a=Q[a])?K.Qg.isQueryEXT(a):0},ne:function(a){return(a=gd[a])?K.isRenderbuffer(a):0},sb:function(a){return(a=jd[a])?K.isSampler(a):0},me:function(a){return(a=O[a])?K.isShader(a):0},Db:function(a){return K.isSync(ld[a])},le:function(a){return(a=
hd[a])?K.isTexture(a):0},gb:function(a){return K.isTransformFeedback(kd[a])},tc:function(a){return(a=P[a])?K.isVertexArray(a):0},$f:function(a){return(a=P[a])?K.isVertexArray(a):0},ke:function(a){K.lineWidth(a)},ie:function(a){a=N[a];K.linkProgram(a);a.lh=0;a.Mh={}},fb:function(){K.pauseTransformFeedback()},he:function(a,b){3317==a&&(od=b);K.pixelStorei(a,b)},ge:function(a,b){K.polygonOffset(a,b)},cb:function(){R(1280)},bb:function(){R(1280)},jg:function(a,b){K.Qg.queryCounterEXT(Q[a],b)},Xc:function(a){K.readBuffer(a)},
fe:function(a,b,c,d,e,f,h){if(2<=S.version)if(K.nh)K.readPixels(a,b,c,d,e,f,h);else{var l=se(f);K.readPixels(a,b,c,d,e,f,l,h>>te(l))}else(h=ue(f,e,c,d,h))?K.readPixels(a,b,c,d,e,f,h):R(1280)},ee:function(){},de:function(a,b,c,d){K.renderbufferStorage(a,b,c,d)},yc:function(a,b,c,d,e){K.renderbufferStorageMultisample(a,b,c,d,e)},eb:function(){K.resumeTransformFeedback()},ce:function(a,b){K.sampleCoverage(a,!!b)},ob:function(a,b,c){K.samplerParameterf(jd[a],b,c)},nb:function(a,b,c){K.samplerParameterf(jd[a],
b,z[c>>2])},qb:function(a,b,c){K.samplerParameteri(jd[a],b,c)},pb:function(a,b,c){K.samplerParameteri(jd[a],b,x[c>>2])},be:function(a,b,c,d){K.scissor(a,b,c,d)},ae:function(){R(1280)},$d:function(a,b,c,d){b=rd(b,c,d);K.shaderSource(O[a],b)},Zd:function(a,b,c){K.stencilFunc(a,b,c)},Yd:function(a,b,c,d){K.stencilFuncSeparate(a,b,c,d)},Xd:function(a){K.stencilMask(a)},Wd:function(a,b){K.stencilMaskSeparate(a,b)},Vd:function(a,b,c){K.stencilOp(a,b,c)},Ud:function(a,b,c,d){K.stencilOpSeparate(a,b,c,d)},
Td:function(a,b,c,d,e,f,h,l,m){if(2<=S.version)if(K.Og)K.texImage2D(a,b,c,d,e,f,h,l,m);else if(m){var q=se(l);K.texImage2D(a,b,c,d,e,f,h,l,q,m>>te(q))}else K.texImage2D(a,b,c,d,e,f,h,l,null);else K.texImage2D(a,b,c,d,e,f,h,l,m?ue(l,h,d,e,m):null)},Vc:function(a,b,c,d,e,f,h,l,m,q){if(K.Og)K.texImage3D(a,b,c,d,e,f,h,l,m,q);else if(q){var r=se(m);K.texImage3D(a,b,c,d,e,f,h,l,m,r,q>>te(r))}else K.texImage3D(a,b,c,d,e,f,h,l,m,null)},Sd:function(a,b,c){K.texParameterf(a,b,c)},Rd:function(a,b,c){K.texParameterf(a,
b,z[c>>2])},Qd:function(a,b,c){K.texParameteri(a,b,c)},Od:function(a,b,c){K.texParameteri(a,b,x[c>>2])},_a:function(a,b,c,d,e){K.texStorage2D(a,b,c,d,e)},Za:function(a,b,c,d,e,f){K.texStorage3D(a,b,c,d,e,f)},Nd:function(a,b,c,d,e,f,h,l,m){if(2<=S.version)if(K.Og)K.texSubImage2D(a,b,c,d,e,f,h,l,m);else if(m){var q=se(l);K.texSubImage2D(a,b,c,d,e,f,h,l,q,m>>te(q))}else K.texSubImage2D(a,b,c,d,e,f,h,l,null);else q=null,m&&(q=ue(l,h,e,f,m)),K.texSubImage2D(a,b,c,d,e,f,h,l,q)},Uc:function(a,b,c,d,e,f,
h,l,m,q,r){if(K.Og)K.texSubImage3D(a,b,c,d,e,f,h,l,m,q,r);else if(r){var w=se(q);K.texSubImage3D(a,b,c,d,e,f,h,l,m,q,w,r>>te(w))}else K.texSubImage3D(a,b,c,d,e,f,h,l,m,q,null)},mc:function(a,b,c,d){a=N[a];for(var e=[],f=0;f<b;f++)e.push(n(x[c+4*f>>2]));K.transformFeedbackVaryings(a,e,d)},Md:function(a,b){K.uniform1f(W(a),b)},Ld:function(a,b,c){if(2<=S.version)b&&K.uniform1fv(W(a),z,c>>2,b);else{if(288>=b)for(var d=ve[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);K.uniform1fv(W(a),
d)}},Kd:function(a,b){K.uniform1i(W(a),b)},Jd:function(a,b,c){if(2<=S.version)b&&K.uniform1iv(W(a),x,c>>2,b);else{if(288>=b)for(var d=we[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);K.uniform1iv(W(a),d)}},ac:function(a,b){K.uniform1ui(W(a),b)},Yb:function(a,b,c){b&&K.uniform1uiv(W(a),y,c>>2,b)},Id:function(a,b,c){K.uniform2f(W(a),b,c)},Hd:function(a,b,c){if(2<=S.version)b&&K.uniform2fv(W(a),z,c>>2,2*b);else{if(144>=b)for(var d=ve[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=
z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);K.uniform2fv(W(a),d)}},Gd:function(a,b,c){K.uniform2i(W(a),b,c)},Fd:function(a,b,c){if(2<=S.version)b&&K.uniform2iv(W(a),x,c>>2,2*b);else{if(144>=b)for(var d=we[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);K.uniform2iv(W(a),d)}},$b:function(a,b,c){K.uniform2ui(W(a),b,c)},Wb:function(a,b,c){b&&K.uniform2uiv(W(a),y,c>>2,2*b)},Dd:function(a,b,c,d){K.uniform3f(W(a),b,c,d)},Cd:function(a,b,c){if(2<=S.version)b&&
K.uniform3fv(W(a),z,c>>2,3*b);else{if(96>=b)for(var d=ve[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);K.uniform3fv(W(a),d)}},Bd:function(a,b,c,d){K.uniform3i(W(a),b,c,d)},Ad:function(a,b,c){if(2<=S.version)b&&K.uniform3iv(W(a),x,c>>2,3*b);else{if(96>=b)for(var d=we[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);K.uniform3iv(W(a),d)}},_b:function(a,b,c,d){K.uniform3ui(W(a),
b,c,d)},Vb:function(a,b,c){b&&K.uniform3uiv(W(a),y,c>>2,3*b)},zd:function(a,b,c,d,e){K.uniform4f(W(a),b,c,d,e)},yd:function(a,b,c){if(2<=S.version)b&&K.uniform4fv(W(a),z,c>>2,4*b);else{if(72>=b){var d=ve[4*b-1],e=z;c>>=2;for(var f=0;f<4*b;f+=4){var h=c+f;d[f]=e[h];d[f+1]=e[h+1];d[f+2]=e[h+2];d[f+3]=e[h+3]}}else d=z.subarray(c>>2,c+16*b>>2);K.uniform4fv(W(a),d)}},xd:function(a,b,c,d,e){K.uniform4i(W(a),b,c,d,e)},wd:function(a,b,c){if(2<=S.version)b&&K.uniform4iv(W(a),x,c>>2,4*b);else{if(72>=b)for(var d=
we[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);K.uniform4iv(W(a),d)}},Zb:function(a,b,c,d,e){K.uniform4ui(W(a),b,c,d,e)},Ub:function(a,b,c){b&&K.uniform4uiv(W(a),y,c>>2,4*b)},Hb:function(a,b,c){a=N[a];K.uniformBlockBinding(a,b,c)},vd:function(a,b,c,d){if(2<=S.version)b&&K.uniformMatrix2fv(W(a),!!c,z,d>>2,4*b);else{if(72>=b)for(var e=ve[4*b-1],f=0;f<4*b;f+=4)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>2],e[f+
2]=z[d+(4*f+8)>>2],e[f+3]=z[d+(4*f+12)>>2];else e=z.subarray(d>>2,d+16*b>>2);K.uniformMatrix2fv(W(a),!!c,e)}},Hc:function(a,b,c,d){b&&K.uniformMatrix2x3fv(W(a),!!c,z,d>>2,6*b)},Fc:function(a,b,c,d){b&&K.uniformMatrix2x4fv(W(a),!!c,z,d>>2,8*b)},ud:function(a,b,c,d){if(2<=S.version)b&&K.uniformMatrix3fv(W(a),!!c,z,d>>2,9*b);else{if(32>=b)for(var e=ve[9*b-1],f=0;f<9*b;f+=9)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>2],e[f+2]=z[d+(4*f+8)>>2],e[f+3]=z[d+(4*f+12)>>2],e[f+4]=z[d+(4*f+16)>>2],e[f+5]=z[d+(4*f+20)>>
2],e[f+6]=z[d+(4*f+24)>>2],e[f+7]=z[d+(4*f+28)>>2],e[f+8]=z[d+(4*f+32)>>2];else e=z.subarray(d>>2,d+36*b>>2);K.uniformMatrix3fv(W(a),!!c,e)}},Gc:function(a,b,c,d){b&&K.uniformMatrix3x2fv(W(a),!!c,z,d>>2,6*b)},Bc:function(a,b,c,d){b&&K.uniformMatrix3x4fv(W(a),!!c,z,d>>2,12*b)},sd:function(a,b,c,d){if(2<=S.version)b&&K.uniformMatrix4fv(W(a),!!c,z,d>>2,16*b);else{if(18>=b){var e=ve[16*b-1],f=z;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+h;e[h]=f[l];e[h+1]=f[l+1];e[h+2]=f[l+2];e[h+3]=f[l+3];e[h+4]=f[l+4];
e[h+5]=f[l+5];e[h+6]=f[l+6];e[h+7]=f[l+7];e[h+8]=f[l+8];e[h+9]=f[l+9];e[h+10]=f[l+10];e[h+11]=f[l+11];e[h+12]=f[l+12];e[h+13]=f[l+13];e[h+14]=f[l+14];e[h+15]=f[l+15]}}else e=z.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(W(a),!!c,e)}},Ec:function(a,b,c,d){b&&K.uniformMatrix4x2fv(W(a),!!c,z,d>>2,8*b)},Ac:function(a,b,c,d){b&&K.uniformMatrix4x3fv(W(a),!!c,z,d>>2,12*b)},rd:function(a){a=N[a];K.useProgram(a);K.$h=a},qd:function(a){K.validateProgram(N[a])},pd:function(a,b){K.vertexAttrib1f(a,b)},od:function(a,
b){K.vertexAttrib1f(a,z[b>>2])},nd:function(a,b,c){K.vertexAttrib2f(a,b,c)},md:function(a,b){K.vertexAttrib2f(a,z[b>>2],z[b+4>>2])},ld:function(a,b,c,d){K.vertexAttrib3f(a,b,c,d)},kd:function(a,b){K.vertexAttrib3f(a,z[b>>2],z[b+4>>2],z[b+8>>2])},jd:function(a,b,c,d,e){K.vertexAttrib4f(a,b,c,d,e)},hd:function(a,b){K.vertexAttrib4f(a,z[b>>2],z[b+4>>2],z[b+8>>2],z[b+12>>2])},kb:function(a,b){K.vertexAttribDivisor(a,b)},Xf:function(a,b){K.vertexAttribDivisor(a,b)},dd:function(a,b){K.vertexAttribDivisor(a,
b)},ed:function(a,b){K.vertexAttribDivisor(a,b)},Xa:function(a,b){K.vertexAttribDivisor(a,b)},hc:function(a,b,c,d,e){K.vertexAttribI4i(a,b,c,d,e)},ec:function(a,b){K.vertexAttribI4i(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},fc:function(a,b,c,d,e){K.vertexAttribI4ui(a,b,c,d,e)},dc:function(a,b){K.vertexAttribI4ui(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},kc:function(a,b,c,d,e){K.vertexAttribIPointer(a,b,c,d,e)},gd:function(a,b,c,d,e,f){K.vertexAttribPointer(a,b,c,!!d,e,f)},fd:function(a,b,c,d){K.viewport(a,
b,c,d)},zb:function(a,b,c,d){K.waitSync(ld[a],b,(c>>>0)+4294967296*d)},D:function(){return 0},Ra:function(a,b,c){t.copyWithin(a,b,b+c)},Fa:function(a,b,c){return xe(a,{Sh:x[c>>2],Oh:x[c+4>>2],Fi:x[c+8>>2],Ai:b,Ah:x[c+12>>2],Yh:x[c+16>>2]})},la:function(a,b){a=T(a);return a?a.requestPointerLock?zd&&Hd.mh?he(a):b?(Ed(he,2,[a]),1):-2:-1:-4},Ma:function(a){var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,f=e.min;d=Math.max(a,d);
d+=(65536-d%65536)%65536;a:{var h=ka.buffer;try{ka.grow(f.call(e,2147483648,d)-h.byteLength+65535>>>16);ua();var l=1;break a}catch(m){}l=void 0}if(l)return!0}return!1},S:function(a,b,c){if("undefined"==typeof onbeforeunload)return-1;if(1!==c)return-5;ye(a,b);return 0},ba:function(a,b,c,d){ze(a,b,c,d,12,"blur");return 0},q:ae,y:function(a,b,c){a=T(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},ca:function(a,b,c,d){ze(a,b,c,d,13,"focus");return 0},V:function(a,b,c,d){if(!Ld())return-1;
a=T(a);if(!a)return-4;Ae(a,b,c,d,"fullscreenchange");Ae(a,b,c,d,"webkitfullscreenchange");return 0},Y:function(a,b,c,d){Be(a,b,c,d,2,"keydown");return 0},W:function(a,b,c,d){Be(a,b,c,d,1,"keypress");return 0},X:function(a,b,c,d){Be(a,b,c,d,3,"keyup");return 0},za:function(a,b,c){a=U(a);lc(a,b,c)},ha:function(a,b,c,d){De(a,b,c,d,5,"mousedown");return 0},fa:function(a,b,c,d){De(a,b,c,d,33,"mouseenter");return 0},ea:function(a,b,c,d){De(a,b,c,d,34,"mouseleave");return 0},ia:function(a,b,c,d){De(a,b,
c,d,8,"mousemove");return 0},ga:function(a,b,c,d){De(a,b,c,d,6,"mouseup");return 0},w:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Wg||document.body.ri||document.body.pi))return-1;a=T(a);if(!a)return-4;Ee(a,b,c,d,"pointerlockchange");Ee(a,b,c,d,"mozpointerlockchange");Ee(a,b,c,d,"webkitpointerlockchange");Ee(a,b,c,d,"mspointerlockchange");return 0},U:function(a,b,c,d){Fe(a,b,c,d);return 0},Z:function(a,b,c,d){Ge(a,b,c,d,25,"touchcancel");return 0},
$:function(a,b,c,d){Ge(a,b,c,d,23,"touchend");return 0},_:function(a,b,c,d){Ge(a,b,c,d,24,"touchmove");return 0},aa:function(a,b,c,d){Ge(a,b,c,d,22,"touchstart");return 0},T:function(a,b,c){He(a,b,c);return 0},da:function(a,b,c,d){a=T(a);return"undefined"!=typeof a.onwheel?(Ie(a,b,c,d),0):-1},Ga:function(a){fa(n(a))},C:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Q:function(a,b){b>>=2;b={alpha:!!x[b],depth:!!x[b+1],
stencil:!!x[b+2],antialias:!!x[b+3],premultipliedAlpha:!!x[b+4],preserveDrawingBuffer:!!x[b+5],powerPreference:Je[x[b+6]],failIfMajorPerformanceCaveat:!!x[b+7],Dh:x[b+8],Si:x[b+9],ai:x[b+10],Ei:x[b+11],xj:x[b+12],Aj:x[b+13]};a=T(a);return!a||b.Ei?0:Jc(a,b)},Ba:function(a){a>>=2;for(var b=0;14>b;++b)x[a+b]=0;x[a]=x[a+1]=x[a+3]=x[a+4]=x[a+8]=x[a+10]=1},Aa:function(a){return Lc(a)?0:-5},xa:function(a){if("undefined"==typeof WebSocket)return-1;if(!a)return-5;var b=a>>2;a=n(x[b]);a=(b=x[b+1])?new WebSocket(a,
n(b).split(",")):new WebSocket(a);a.binaryType="arraybuffer";b=Ke.length;Ke[b]=a;return b},l:function(a,b,c){a=Ke[a];if(!a)return-3;a.send(t.subarray(b,b+c));return 0},N:function(a,b){a=Ke[a];if(!a)return-3;b=n(b);a.send(b);return 0},ua:function(a,b,c){Y||(Y=D(1024));var d=Ke[a];if(!d)return-3;d.onclose=function(e){y[Y>>2]=a;y[Y+4>>2]=e.wasClean;y[Y+8>>2]=e.code;u(e.reason,Y+10,512);U(c)(0,Y,b)};return 0},va:function(a,b,c){Y||(Y=D(1024));var d=Ke[a];if(!d)return-3;d.onerror=function(){y[Y>>2]=a;
U(c)(0,Y,b)};return 0},wa:function(a,b,c){Y||(Y=D(1024));var d=Ke[a];if(!d)return-3;d.onmessage=function(e){y[Y>>2]=a;if("string"==typeof e.data){var f=qa(e.data)+1,h=D(f);u(e.data,h,f);y[Y+12>>2]=1}else f=e.data.byteLength,h=D(f),v.set(new Uint8Array(e.data),h),y[Y+12>>2]=0;y[Y+4>>2]=h;y[Y+8>>2]=f;U(c)(0,Y,b);We(h)};return 0},ta:function(a,b,c){Y||(Y=D(1024));var d=Ke[a];if(!d)return-3;d.onopen=function(){y[Y>>2]=a;U(c)(0,Y,b)};return 0},Pa:function(a,b){var c=0;Me().forEach(function(d,e){var f=
b+c;e=y[a+4*e>>2]=f;for(f=0;f<d.length;++f)v[e++>>0]=d.charCodeAt(f);v[e>>0]=0;c+=d.length+1});return 0},Qa:function(a,b){var c=Me();y[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});y[b>>2]=d;return 0},oa:uc,u:function(a){try{var b=Xb(a);ob(b);return 0}catch(c){if("undefined"==typeof Ub||"ErrnoError"!==c.name)throw c;return c.Ug}},Ta:function(a,b,c,d){try{a:{var e=Xb(a);a=b;for(var f,h=b=0;h<c;h++){var l=y[a>>2],m=y[a+4>>2];a+=8;var q=e,r=l,w=m,G=f,p=v;if(0>w||0>G)throw new H(28);if(null===
q.eh)throw new H(8);if(1===(q.flags&2097155))throw new H(8);if(16384===(q.node.mode&61440))throw new H(31);if(!q.Lg.read)throw new H(28);var C="undefined"!=typeof G;if(!C)G=q.position;else if(!q.seekable)throw new H(70);var F=q.Lg.read(q,p,r,w,G);C||(q.position+=F);var X=F;if(0>X){var za=-1;break a}b+=X;if(X<m)break;"undefined"!==typeof f&&(f+=X)}za=b}y[d>>2]=za;return 0}catch(kb){if("undefined"==typeof Ub||"ErrnoError"!==kb.name)throw kb;return kb.Ug}},Ha:function(a,b,c,d,e){try{b=c+2097152>>>0<
4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var f=Xb(a);Ob(f,b,d);B=[f.position>>>0,(A=f.position,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[e>>2]=B[0];x[e+4>>2]=B[1];f.hh&&0===b&&0===d&&(f.hh=null);return 0}catch(h){if("undefined"==typeof Ub||"ErrnoError"!==h.name)throw h;return h.Ug}},Sa:function(a,b,c,d){try{a:{var e=Xb(a);a=b;for(var f,h=b=0;h<c;h++){var l=y[a>>2],m=y[a+4>>2];a+=8;var q=nb(e,v,l,m,
f);if(0>q){var r=-1;break a}b+=q;"undefined"!==typeof f&&(f+=q)}r=b}y[d>>2]=r;return 0}catch(w){if("undefined"==typeof Ub||"ErrnoError"!==w.name)throw w;return w.Ug}},ya:function(){return ne(location.hash.replace("#",""))},qa:function(a,b){K.attachShader(N[a],O[b])},f:function(a,b){35051==a?K.nh=b:35052==a&&(K.Og=b);K.bindBuffer(a,ed[b])},g:function(a,b){K.bindTexture(a,hd[b])},b:function(a){K.bindVertexArray(P[a])},Ja:function(a,b){K.blendFunc(a,b)},i:function(a,b,c,d){2<=S.version?c&&b?K.bufferData(a,
t,d,c,b):K.bufferData(a,b,d):K.bufferData(a,c?t.subarray(c,c+b):b,d)},h:function(a,b,c,d){2<=S.version?c&&K.bufferSubData(a,b,t,d,c):K.bufferSubData(a,b,t.subarray(d,d+c))},O:function(a){K.clear(a)},Ca:function(a,b,c,d){K.clearColor(a,b,c,d)},R:function(a,b,c,d){K.colorMask(!!a,!!b,!!c,!!d)},I:function(a){K.compileShader(O[a])},vg:function(){var a=qd(N),b=K.createProgram();b.name=a;b.wh=b.uh=b.vh=0;b.Lh=1;N[a]=b;return a},K:function(a){var b=qd(O);O[b]=K.createShader(a);return b},qg:function(a,b){for(var c=
0;c<a;c++){var d=x[b+4*c>>2],e=ed[d];e&&(K.deleteBuffer(e),e.name=0,ed[d]=null,d==K.nh&&(K.nh=0),d==K.Og&&(K.Og=0))}},pg:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];K.deleteVertexArray(P[d]);P[d]=null}},Dc:function(a){K.depthFunc(a)},e:function(a,b,c){K.drawArrays(a,b,c)},B:function(a){K.enable(a)},t:function(a){K.enableVertexAttribArray(a)},L:function(a,b){V(a,b,"createBuffer",ed)},G:function(a,b){V(a,b,"createTexture",hd)},M:function(a,b){V(a,b,"createVertexArray",P)},x:function(a,b){return K.getAttribLocation(N[a],
n(b))},H:function(a,b,c,d){a=K.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?u(a,d,b):0;c&&(x[c>>2]=b)},r:function(a,b,c){c?35716==b?(a=K.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(O[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=K.getShaderParameter(O[a],b):R(1281)},m:function(a,b){b=n(b);if(a=N[a]){pe(a);var c=a.lh,d=0,e=b,f=oe(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Mh[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||
K.getUniformLocation(a,b)))return d}else R(1281);return-1},ug:function(a){a=N[a];K.linkProgram(a);a.lh=0;a.Mh={}},J:function(a,b,c,d){b=rd(b,c,d);K.shaderSource(O[a],b)},F:function(a,b,c,d,e,f,h,l,m){if(2<=S.version)if(K.Og)K.texImage2D(a,b,c,d,e,f,h,l,m);else if(m){var q=se(l);K.texImage2D(a,b,c,d,e,f,h,l,q,m>>te(q))}else K.texImage2D(a,b,c,d,e,f,h,l,null);else K.texImage2D(a,b,c,d,e,f,h,l,m?ue(l,h,d,e,m):null)},k:function(a,b,c){K.texParameteri(a,b,c)},v:function(a,b,c,d,e,f,h,l,m){if(2<=S.version)if(K.Og)K.texSubImage2D(a,
b,c,d,e,f,h,l,m);else if(m){var q=se(l);K.texSubImage2D(a,b,c,d,e,f,h,l,q,m>>te(q))}else K.texSubImage2D(a,b,c,d,e,f,h,l,null);else q=null,m&&(q=ue(l,h,e,f,m)),K.texSubImage2D(a,b,c,d,e,f,h,l,q)},E:function(a,b){K.uniform1f(W(a),b)},pa:function(a,b,c){K.uniform2f(W(a),b,c)},wg:function(a,b,c){if(2<=S.version)b&&K.uniform3fv(W(a),z,c>>2,3*b);else{if(96>=b)for(var d=ve[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);K.uniform3fv(W(a),
d)}},gg:function(a,b,c){if(2<=S.version)b&&K.uniform4fv(W(a),z,c>>2,4*b);else{if(72>=b){var d=ve[4*b-1],e=z;c>>=2;for(var f=0;f<4*b;f+=4){var h=c+f;d[f]=e[h];d[f+1]=e[h+1];d[f+2]=e[h+2];d[f+3]=e[h+3]}}else d=z.subarray(c>>2,c+16*b>>2);K.uniform4fv(W(a),d)}},j:function(a,b,c,d){if(2<=S.version)b&&K.uniformMatrix4fv(W(a),!!c,z,d>>2,16*b);else{if(18>=b){var e=ve[16*b-1],f=z;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+h;e[h]=f[l];e[h+1]=f[l+1];e[h+2]=f[l+2];e[h+3]=f[l+3];e[h+4]=f[l+4];e[h+5]=f[l+5];e[h+6]=
f[l+6];e[h+7]=f[l+7];e[h+8]=f[l+8];e[h+9]=f[l+9];e[h+10]=f[l+10];e[h+11]=f[l+11];e[h+12]=f[l+12];e[h+13]=f[l+13];e[h+14]=f[l+14];e[h+15]=f[l+15]}}else e=z.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(W(a),!!c,e)}},xg:function(a){a=N[a];K.useProgram(a);K.$h=a},ra:function(a,b){K.vertexAttrib1f(a,b)},sa:function(a,b,c){K.vertexAttrib2f(a,b,c)},s:function(a,b,c,d,e,f){K.vertexAttribPointer(a,b,c,!!d,e,f)},Da:function(a,b,c,d){K.viewport(a,b,c,d)},yg:function(){return window.fullScreen||window.innerWidth==
screen.width&&window.innerHeight==screen.height},rg:function(){return"ontouchstart"in window||0<navigator.maxTouchPoints||0<navigator.msMaxTouchPoints},P:function(a){location.hash=n(a)},Ka:function(a,b,c,d){return Se(a,b,c,d)},sg:function(){document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement?document.Wg?document.Wg():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen():document.documentElement.requestFullscreen?
document.documentElement.requestFullscreen():document.documentElement.mozRequestFullScreen?document.documentElement.mozRequestFullScreen():document.documentElement.webkitRequestFullscreen&&document.documentElement.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}};
(function(){function a(c){c=c.exports;g.asm=c;ka=g.asm.zg;ua();va=g.asm.Fg;xa.unshift(g.asm.Ag);Da--;g.monitorRunDependencies&&g.monitorRunDependencies(Da);if(0==Da&&(null!==Ea&&(clearInterval(Ea),Ea=null),Fa)){var d=Fa;Fa=null;d()}return c}var b={a:Xe};Da++;g.monitorRunDependencies&&g.monitorRunDependencies(Da);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return k("Module.instantiateWasm callback failed with error: "+c),!1}Ma(b,function(c){a(c.instance)});return{}})();
function D(){return(D=g.asm.Bg).apply(null,arguments)}function We(){return(We=g.asm.Cg).apply(null,arguments)}function Ve(){return(Ve=g.asm.Dg).apply(null,arguments)}var Ye=g._main=function(){return(Ye=g._main=g.asm.Eg).apply(null,arguments)};function xd(){return(xd=g.asm.Gg).apply(null,arguments)}function yd(){return(yd=g.asm.Hg).apply(null,arguments)}function $d(){return($d=g.asm.Ig).apply(null,arguments)}g.___start_em_js=102748;g.___stop_em_js=103882;var Ze;Fa=function $e(){Ze||af();Ze||(Fa=$e)};
function bf(a=[]){var b=Ye;a.unshift(ca);var c=a.length,d=$d(4*(c+1)),e=d>>2;a.forEach(h=>{var l=x,m=e++,q=qa(h)+1,r=$d(q);pa(h,v,r,q);l[m]=r});x[e]=0;try{var f=b(c,d);uc(f,!0)}catch(h){tc(h)}}
function af(){var a=ba;function b(){if(!Ze&&(Ze=!0,g.calledRun=!0,!la)){g.noFSInit||Qb||(Qb=!0,Pb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Tb("stdin",g.stdin):Mb("/dev/tty","/dev/stdin"),g.stdout?Tb("stdout",null,g.stdout):Mb("/dev/tty","/dev/stdout"),g.stderr?Tb("stderr",null,g.stderr):Mb("/dev/tty1","/dev/stderr"),mb("/dev/stdin",0),mb("/dev/stdout",1),mb("/dev/stderr",1));wb=!1;Sa(xa);Sa(ya);if(g.onRuntimeInitialized)g.onRuntimeInitialized();cf&&bf(a);if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Ba.unshift(c)}Sa(Ba)}}if(!(0<Da)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ca();Sa(wa);0<Da||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var cf=!0;g.noInitialRun&&(cf=!1);af();
