var h;h||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="";"undefined"!=typeof document&&document.currentScript&&(ea=document.currentScript.src);ea=ea.startsWith("blob:")?"":ea.substr(0,ea.replace(/[?#].*/,"").lastIndexOf("/")+1);var fa=h.print||console.log.bind(console),ha=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);
h.quit&&(da=h.quit);var ia;h.wasmBinary&&(ia=h.wasmBinary);"object"!=typeof WebAssembly&&ja("no native wasm support detected");var ka,la=!1,ma,k,n,na,oa,t,u,v,w;function pa(){var a=ka.buffer;h.HEAP8=k=new Int8Array(a);h.HEAP16=na=new Int16Array(a);h.HEAPU8=n=new Uint8Array(a);h.HEAPU16=oa=new Uint16Array(a);h.HEAP32=t=new Int32Array(a);h.HEAPU32=u=new Uint32Array(a);h.HEAPF32=v=new Float32Array(a);h.HEAPF64=w=new Float64Array(a)}var qa=[],ra=[],sa=[],ta=[];
function ua(){var a=h.preRun.shift();qa.unshift(a)}var va=0,wa=null,xa=null;function ja(a){h.onAbort?.(a);a="Aborted("+a+")";ha(a);la=!0;ma=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ya=a=>a.startsWith("data:application/octet-stream;base64,"),za;za="index.wasm";if(!ya(za)){var Aa=za;za=h.locateFile?h.locateFile(Aa,ea):ea+Aa}function Ba(a){if(a==za&&ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}
function Ca(a){return ia||"function"!=typeof fetch?Promise.resolve().then(()=>Ba(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Ba(a))}function Da(a,b,c){return Ca(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{ha(`failed to asynchronously prepare wasm: ${d}`);ja(d)})}
function Ea(a,b){var c=za;ia||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||"function"!=typeof fetch?Da(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){ha(`wasm streaming compile failed: ${e}`);ha("falling back to ArrayBuffer instantiation");return Da(c,a,b)}))}
var y,z,Ia={112407:()=>window.innerWidth,112437:()=>window.innerHeight,112468:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.zi!==h.canvas&&(d.dh=h.createContext(h.canvas,!1,!0),d.zi=h.canvas);if(d.w!==a||d.h!==b||d.Oi!==d.dh)d.image=d.dh.createImageData(a,b),d.w=a,d.h=b,d.Oi=d.dh;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=t[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Ci!==a&&(d.Bi=
new Int32Array(a.buffer),d.Di=new Uint8Array(a.buffer),d.Ci=a),a=d.Bi,c=a.length,a.set(t.subarray(b,b+c)),a=d.Di,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.dh.putImageData(d.image,0,0)},113937:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var l=0,m;if("undefined"!==
typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(m=b.length;l<m;){var q=t[e];b[l]=q&255;b[l+1]=q>>8&255;b[l+2]=q>>16&255;b[l+3]=q>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),m=b.length,b.set(t.subarray(e,e+m));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=A(c.length+1);B(c,n,d,c.length+1);return d},114926:a=>{h.canvas&&(h.canvas.style.cursor=a?C(n,a):"")},115009:()=>{h.canvas&&(h.canvas.style.cursor="none")},115078:()=>
{Fa("/saves");Ga(E,"/saves");Ha(!0,function(a){a&&console.log(a)})},115196:()=>{Ha(!1,function(a){console.log(a)})}};function Ja(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ka=a=>{for(;0<a.length;)a.shift()(h)},La=h.noExitRuntime||!0,Ma="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,C=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ma)return Ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Na=(a,b)=>a?C(n,a,b):"",Oa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Pa=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Oa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Qa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Ra=a=>{if("/"===a)return"/";a=Pa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Sa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);ja("initRandomDevice")},Ta=a=>(Ta=Sa())(a);
function Ua(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Oa(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Va=[],Wa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},B=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>
12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Xa(a,b){var c=Array(Wa(a)+1);a=B(a,c,0,c.length);b&&(c.length=a);return c}var Ya=[];function Za(a,b){Ya[a]={input:[],Ug:[],ih:b};$a(a,ab)}
var ab={open(a){var b=Ya[a.node.xh];if(!b)throw new F(43);a.Qg=b;a.seekable=!1},close(a){a.Qg.ih.Dh(a.Qg)},Dh(a){a.Qg.ih.Dh(a.Qg)},read(a,b,c,d){if(!a.Qg||!a.Qg.ih.fi)throw new F(60);for(var e=0,f=0;f<d;f++){try{var g=a.Qg.ih.fi(a.Qg)}catch(l){throw new F(29);}if(void 0===g&&0===e)throw new F(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.Qg||!a.Qg.ih.Sh)throw new F(60);try{for(var e=0;e<d;e++)a.Qg.ih.Sh(a.Qg,b[c+e])}catch(f){throw new F(29);
}d&&(a.node.timestamp=Date.now());return e}},bb={fi(){a:{if(!Va.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Va=Xa(a,!0)}a=Va.shift()}return a},Sh(a,b){null===b||10===b?(fa(C(a.Ug,0)),a.Ug=[]):0!=b&&a.Ug.push(b)},Dh(a){a.Ug&&0<a.Ug.length&&(fa(C(a.Ug,0)),a.Ug=[])},Ri(){return{pj:25856,rj:5,oj:191,qj:35387,nj:[3,28,127,21,4,0,1,0,
17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Si(){return 0},Ti(){return[24,80]}},cb={Sh(a,b){null===b||10===b?(ha(C(a.Ug,0)),a.Ug=[]):0!=b&&a.Ug.push(b)},Dh(a){a.Ug&&0<a.Ug.length&&(ha(C(a.Ug,0)),a.Ug=[])}};function db(a,b){var c=a.Og?a.Og.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Og,a.Og=new Uint8Array(b),0<a.Sg&&a.Og.set(c.subarray(0,a.Sg),0))}
var G={gh:null,Wg(){return G.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(63);G.gh||(G.gh={dir:{node:{fh:G.Ng.fh,Vg:G.Ng.Vg,vh:G.Ng.vh,Ih:G.Ng.Ih,ni:G.Ng.ni,Ph:G.Ng.Ph,Lh:G.Ng.Lh,Kh:G.Ng.Kh,Mh:G.Ng.Mh},stream:{oh:G.Pg.oh}},file:{node:{fh:G.Ng.fh,Vg:G.Ng.Vg},stream:{oh:G.Pg.oh,read:G.Pg.read,write:G.Pg.write,Yh:G.Pg.Yh,ii:G.Pg.ii,ki:G.Pg.ki}},link:{node:{fh:G.Ng.fh,Vg:G.Ng.Vg,yh:G.Ng.yh},stream:{}},bi:{node:{fh:G.Ng.fh,Vg:G.Ng.Vg},stream:eb}});
c=fb(a,b,c,d);I(c.mode)?(c.Ng=G.gh.dir.node,c.Pg=G.gh.dir.stream,c.Og={}):32768===(c.mode&61440)?(c.Ng=G.gh.file.node,c.Pg=G.gh.file.stream,c.Sg=0,c.Og=null):40960===(c.mode&61440)?(c.Ng=G.gh.link.node,c.Pg=G.gh.link.stream):8192===(c.mode&61440)&&(c.Ng=G.gh.bi.node,c.Pg=G.gh.bi.stream);c.timestamp=Date.now();a&&(a.Og[b]=c,a.timestamp=c.timestamp);return c},Ng:{fh(a){var b={};b.Fi=8192===(a.mode&61440)?a.id:1;b.gi=a.id;b.mode=a.mode;b.Xi=1;b.uid=0;b.Mi=0;b.xh=a.xh;I(a.mode)?b.size=4096:32768===(a.mode&
61440)?b.size=a.Sg:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.vi=new Date(a.timestamp);b.Jh=new Date(a.timestamp);b.yi=new Date(a.timestamp);b.wi=4096;b.xi=Math.ceil(b.size/b.wi);return b},Vg(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Sg!=b))if(0==b)a.Og=null,a.Sg=0;else{var c=a.Og;a.Og=new Uint8Array(b);c&&a.Og.set(c.subarray(0,Math.min(b,a.Sg)));a.Sg=b}},vh(){throw gb[44];},Ih(a,b,c,d){return G.createNode(a,b,
c,d)},ni(a,b,c){if(I(a.mode)){try{var d=hb(b,c)}catch(f){}if(d)for(var e in d.Og)throw new F(55);}delete a.parent.Og[a.name];a.parent.timestamp=Date.now();a.name=c;b.Og[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Ph(a,b){delete a.Og[b];a.timestamp=Date.now()},Lh(a,b){var c=hb(a,b),d;for(d in c.Og)throw new F(55);delete a.Og[b];a.timestamp=Date.now()},Kh(a){var b=[".",".."],c;for(c of Object.keys(a.Og))b.push(c);return b},Mh(a,b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},yh(a){if(40960!==
(a.mode&61440))throw new F(28);return a.link}},Pg:{read(a,b,c,d,e){var f=a.node.Og;if(e>=a.node.Sg)return 0;a=Math.min(a.node.Sg-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===k.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Og||a.Og.subarray)){if(f)return a.Og=b.subarray(c,c+d),a.Sg=d;if(0===a.Sg&&0===e)return a.Og=b.slice(c,c+d),a.Sg=d;if(e+d<=a.Sg)return a.Og.set(b.subarray(c,c+d),e),
d}db(a,e+d);if(a.Og.subarray&&b.subarray)a.Og.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Og[e+f]=b[c+f];a.Sg=Math.max(a.Sg,e+d);return d},oh(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Sg);if(0>b)throw new F(28);return b},Yh(a,b,c){db(a.node,b+c);a.node.Sg=Math.max(a.node.Sg,b+c)},ii(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new F(43);a=a.node.Og;if(e&2||a.buffer!==k.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);c=!0;ja();b=void 0;if(!b)throw new F(48);k.set(a,b)}else c=!1,b=a.byteOffset;return{Ej:b,lj:c}},ki(a,b,c,d){G.Pg.write(a,b,0,d,c,!1);return 0}}},ib=h.preloadPlugins||[],jb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},E={Ch:{},indexedDB:()=>{if("undefined"!=typeof indexedDB)return indexedDB;var a=null;"object"==typeof window&&(a=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB);a||ja("IDBFS used, but indexedDB not supported");return a},si:21,mh:"FILE_DATA",
Wg:function(a){return G.Wg.apply(null,arguments)},oi:(a,b,c)=>{E.Ki(a,(d,e)=>{if(d)return c(d);E.Li(a,(f,g)=>{if(f)return c(f);E.Yi(b?g:e,b?e:g,c)})})},Gj:()=>{Object.values(E.Ch).forEach(a=>a.close());E.Ch={}},Ji:(a,b)=>{var c=E.Ch[a];if(c)return b(null,c);try{var d=E.indexedDB().open(a,E.si)}catch(e){return b(e)}if(!d)return b("Unable to connect to IndexedDB");d.onupgradeneeded=e=>{var f=e.target.result;e=e.target.transaction;var g;f.objectStoreNames.contains(E.mh)?g=e.objectStore(E.mh):g=f.createObjectStore(E.mh);
g.indexNames.contains("timestamp")||g.createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=()=>{c=d.result;E.Ch[a]=c;b(null,c)};d.onerror=e=>{b(e.target.error);e.preventDefault()}},Ki:(a,b)=>{function c(l){return"."!==l&&".."!==l}function d(l){return m=>Pa(l+"/"+m)}var e={};for(a=kb(a.wh).filter(c).map(d(a.wh));a.length;){var f=a.pop();try{var g=lb(f)}catch(l){return b(l)}I(g.mode)&&a.push.apply(a,kb(f).filter(c).map(d(f)));e[f]={timestamp:g.Jh}}return b(null,{type:"local",entries:e})},Li:(a,
b)=>{var c={};E.Ji(a.wh,(d,e)=>{if(d)return b(d);try{var f=e.transaction([E.mh],"readonly");f.onerror=g=>{b(g.target.error);g.preventDefault()};f.objectStore(E.mh).index("timestamp").openKeyCursor().onsuccess=g=>{g=g.target.result;if(!g)return b(null,{type:"remote",db:e,entries:c});c[g.primaryKey]={timestamp:g.key};g.continue()}}catch(g){return b(g)}})},Ui:(a,b)=>{try{var c=J(a).node;var d=lb(a)}catch(f){return b(f)}if(I(d.mode))return b(null,{timestamp:d.Jh,mode:d.mode});if(32768===(d.mode&61440)){a=
c;var e=c.Og?c.Og.subarray?c.Og.subarray(0,c.Sg):new Uint8Array(c.Og):new Uint8Array(0);a.Og=e;return b(null,{timestamp:d.Jh,mode:d.mode,contents:c.Og})}return b(Error("node type not supported"))},bj:(a,b,c)=>{try{if(I(b.mode))for(var d=b.mode,e=a.split("/"),f="",g=0;g<e.length;++g){if(e[g]){f+="/"+e[g];try{Fa(f,d)}catch(D){if(20!=D.$g)throw D;}}}else if(32768===(b.mode&61440)){f=b.contents;d={$h:!0};d.flags=d.flags||577;g=mb(a,d.flags,d.mode);if("string"==typeof f){var l=new Uint8Array(Wa(f)+1),
m=B(f,l,0,l.length);nb(g,l,0,m,void 0,d.$h)}else if(ArrayBuffer.isView(f))nb(g,f,0,f.byteLength,void 0,d.$h);else throw Error("Unsupported data type");ob(g)}else return c(Error("node type not supported"));var q=b.mode;var r="string"==typeof a?J(a,{rh:!0}).node:a;if(!r.Ng.Vg)throw new F(63);r.Ng.Vg(r,{mode:q&4095|r.mode&-4096,timestamp:Date.now()});var x=b.timestamp,M=b.timestamp,p=J(a,{rh:!0}).node;p.Ng.Vg(p,{timestamp:Math.max(x,M)})}catch(D){return c(D)}c(null)},Zi:(a,b)=>{try{var c=lb(a);if(I(c.mode)){var d=
J(a,{parent:!0}).node,e=Ra(a),f=hb(d,e),g=pb(d,e,!0);if(g)throw new F(g);if(!d.Ng.Lh)throw new F(63);if(f.sh)throw new F(10);d.Ng.Lh(d,e);qb(f)}else if(32768===(c.mode&61440)){var l=J(a,{parent:!0}).node;if(!l)throw new F(44);var m=Ra(a),q=hb(l,m),r=pb(l,m,!1);if(r)throw new F(r);if(!l.Ng.Ph)throw new F(63);if(q.sh)throw new F(10);l.Ng.Ph(l,m);qb(q)}}catch(x){return b(x)}b(null)},Vi:(a,b,c)=>{a=a.get(b);a.onsuccess=d=>c(null,d.target.result);a.onerror=d=>{c(d.target.error);d.preventDefault()}},cj:(a,
b,c,d)=>{try{var e=a.put(c,b)}catch(f){d(f);return}e.onsuccess=()=>d();e.onerror=f=>{d(f.target.error);f.preventDefault()}},$i:(a,b,c)=>{a=a.delete(b);a.onsuccess=()=>c();a.onerror=d=>{c(d.target.error);d.preventDefault()}},Yi:(a,b,c)=>{function d(r){if(r&&!l)return l=!0,c(r)}var e=0,f=[];Object.keys(a.entries).forEach(function(r){var x=a.entries[r],M=b.entries[r];M&&x.timestamp.getTime()==M.timestamp.getTime()||(f.push(r),e++)});var g=[];Object.keys(b.entries).forEach(function(r){a.entries[r]||(g.push(r),
e++)});if(!e)return c(null);var l=!1,m=("remote"===a.type?a.db:b.db).transaction([E.mh],"readwrite"),q=m.objectStore(E.mh);m.onerror=r=>{d(this.error);r.preventDefault()};m.oncomplete=()=>{l||c(null)};f.sort().forEach(r=>{"local"===b.type?E.Vi(q,r,(x,M)=>{if(x)return d(x);E.bj(r,M,d)}):E.Ui(r,(x,M)=>{if(x)return d(x);E.cj(q,r,M,d)})});g.sort().reverse().forEach(r=>{"local"===b.type?E.Zi(r,d):E.$i(q,r,d)})}},rb=null,sb={},tb=[],ub=1,vb=null,wb=!0,F=class{constructor(a){this.name="ErrnoError";this.$g=
a}},gb={},xb=0;function J(a,b={}){a=Ua(a);if(!a)return{path:"",node:null};b=Object.assign({ei:!0,Th:0},b);if(8<b.Th)throw new F(32);a=a.split("/").filter(g=>!!g);for(var c=rb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=hb(c,a[e]);d=Pa(d+"/"+a[e]);c.sh&&(!f||f&&b.ei)&&(c=c.sh.root);if(!f||b.rh)for(f=0;40960===(c.mode&61440);)if(c=yb(d),d=Ua(Qa(d),c),c=J(d,{Th:b.Th+1}).node,40<f++)throw new F(32);}return{path:d,node:c}}
function zb(a){for(var b;;){if(a===a.parent)return a=a.Wg.wh,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Ab(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%vb.length}function qb(a){var b=Ab(a.parent.id,a.name);if(vb[b]===a)vb[b]=a.th;else for(b=vb[b];b;){if(b.th===a){b.th=a.th;break}b=b.th}}
function hb(a,b){var c=I(a.mode)?(c=Bb(a,"x"))?c:a.Ng.vh?0:2:54;if(c)throw new F(c);for(c=vb[Ab(a.id,b)];c;c=c.th){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ng.vh(a,b)}function fb(a,b,c,d){a=new Cb(a,b,c,d);b=Ab(a.parent.id,a.name);a.th=vb[b];return vb[b]=a}function I(a){return 16384===(a&61440)}function Db(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Bb(a,b){if(wb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Eb(a,b){try{return hb(a,b),20}catch(c){}return Bb(a,"wx")}function pb(a,b,c){try{var d=hb(a,b)}catch(e){return e.$g}if(a=Bb(a,"wx"))return a;if(c){if(!I(d.mode))return 54;if(d===d.parent||"/"===zb(d))return 10}else if(I(d.mode))return 31;return 0}function Fb(){for(var a=0;4096>=a;a++)if(!tb[a])return a;throw new F(33);}
function Hb(a){a=tb[a];if(!a)throw new F(8);return a}function Ib(a,b=-1){Jb||(Jb=function(){this.bh={}},Jb.prototype={},Object.defineProperties(Jb.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.bh.flags},set(c){this.bh.flags=c}},position:{get(){return this.bh.position},set(c){this.bh.position=c}}}));a=Object.assign(new Jb,a);-1==b&&(b=Fb());a.fd=b;return tb[b]=a}var eb={open(a){a.Pg=sb[a.node.xh].Pg;a.Pg.open?.(a)},oh(){throw new F(70);}};
function $a(a,b){sb[a]={Pg:b}}function Kb(){for(var a=[],b=[rb.Wg];b.length;){var c=b.pop();a.push(c);b.push.apply(b,c.ji)}return a}function Ha(a,b){function c(g){xb--;return b(g)}function d(g){if(g){if(!d.Gi)return d.Gi=!0,c(g)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);xb++;1<xb&&ha(`warning: ${xb} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Kb(),f=0;e.forEach(g=>{if(!g.type.oi)return d(null);g.type.oi(g,a,d)})}
function Ga(a,b){var c="/"===b;if(c&&rb)throw new F(10);if(!c&&b){var d=J(b,{ei:!1});b=d.path;d=d.node;if(d.sh)throw new F(10);if(!I(d.mode))throw new F(54);}b={type:a,Cj:{},wh:b,ji:[]};a=a.Wg(b);a.Wg=b;b.root=a;c?rb=a:d&&(d.sh=b,d.Wg&&d.Wg.ji.push(b))}function Lb(a,b,c){var d=J(a,{parent:!0}).node;a=Ra(a);if(!a||"."===a||".."===a)throw new F(28);var e=Eb(d,a);if(e)throw new F(e);if(!d.Ng.Ih)throw new F(63);return d.Ng.Ih(d,a,b,c)}function Fa(a,b){return Lb(a,(void 0!==b?b:511)&1023|16384,0)}
function Mb(a,b,c){"undefined"==typeof c&&(c=b,b=438);Lb(a,b|8192,c)}function Nb(a,b){if(!Ua(a))throw new F(44);var c=J(b,{parent:!0}).node;if(!c)throw new F(44);b=Ra(b);var d=Eb(c,b);if(d)throw new F(d);if(!c.Ng.Mh)throw new F(63);c.Ng.Mh(c,b,a)}function kb(a){a=J(a,{rh:!0}).node;if(!a.Ng.Kh)throw new F(54);return a.Ng.Kh(a)}function yb(a){a=J(a).node;if(!a)throw new F(44);if(!a.Ng.yh)throw new F(28);return Ua(zb(a.parent),a.Ng.yh(a))}
function lb(a){a=J(a,{rh:!0}).node;if(!a)throw new F(44);if(!a.Ng.fh)throw new F(63);return a.Ng.fh(a)}
function mb(a,b,c){if(""===a)throw new F(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Pa(a);try{e=J(a,{rh:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new F(20);}else e=Lb(a,c,0),d=!0;if(!e)throw new F(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!I(e.mode))throw new F(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:I(e.mode)&&("r"!==Db(b)||b&512)?31:Bb(e,Db(b)):44))throw new F(c);if(b&512&&!d){c=e;c="string"==typeof c?J(c,{rh:!0}).node:c;if(!c.Ng.Vg)throw new F(63);if(I(c.mode))throw new F(31);if(32768!==(c.mode&61440))throw new F(28);if(d=Bb(c,"w"))throw new F(d);c.Ng.Vg(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Ib({node:e,path:zb(e),flags:b,seekable:!0,position:0,Pg:e.Pg,hj:[],error:!1});e.Pg.open&&e.Pg.open(e);!h.logReadFiles||b&1||(Ob||={},a in Ob||(Ob[a]=1));return e}
function ob(a){if(null===a.fd)throw new F(8);a.nh&&(a.nh=null);try{a.Pg.close&&a.Pg.close(a)}catch(b){throw b;}finally{tb[a.fd]=null}a.fd=null}function Pb(a,b,c){if(null===a.fd)throw new F(8);if(!a.seekable||!a.Pg.oh)throw new F(70);if(0!=c&&1!=c&&2!=c)throw new F(28);a.position=a.Pg.oh(a,b,c);a.hj=[];return a.position}
function nb(a,b,c,d,e,f){if(0>d||0>e)throw new F(28);if(null===a.fd)throw new F(8);if(0===(a.flags&2097155))throw new F(8);if(I(a.node.mode))throw new F(31);if(!a.Pg.write)throw new F(28);a.seekable&&a.flags&1024&&Pb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new F(70);b=a.Pg.write(a,b,c,d,e,f);g||(a.position+=b);return b}var Qb;
function Rb(a,b,c){a=Pa("/dev/"+a);var d=jb(!!b,!!c);Sb||=64;var e=Sb++<<8|0;$a(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,l,m){for(var q=0,r=0;r<m;r++){try{var x=b()}catch(M){throw new F(29);}if(void 0===x&&0===q)throw new F(6);if(null===x||void 0===x)break;q++;g[l+r]=x}q&&(f.node.timestamp=Date.now());return q},write(f,g,l,m){for(var q=0;q<m;q++)try{c(g[l+q])}catch(r){throw new F(29);}m&&(f.node.timestamp=Date.now());return q}});Mb(a,d,e)}var Sb,Tb={},Jb,Ob,Ub=void 0;
function Vb(){var a=t[+Ub>>2];Ub+=4;return a}
var Wb=a=>0===a%4&&(0!==a%100||0===a%400),Xb=[0,31,60,91,121,152,182,213,244,274,305,335],Yb=[0,31,59,90,120,151,181,212,243,273,304,334],K=a=>{var b=Wa(a)+1,c=A(b);c&&B(a,n,c,b);return c},ic=(a,b)=>{Zb=a;$b=b;if(ac)if(bc||=!0,0==a)cc=function(){var d=Math.max(0,dc+b-ec())|0;setTimeout(fc,d)};else if(1==a)cc=function(){gc(fc)};else if(2==a){if("undefined"==typeof hc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),
c.shift()()},!0);hc=function(d){c.push(d);postMessage("setimmediate","*")}}else hc=setImmediate;cc=function(){hc(fc)}}},ec;ec=()=>performance.now();
var rc=(a,b,c,d,e)=>{!ac||ja("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");ac=a;jc=d;var f=kc;bc=!1;fc=function(){if(!la)if(0<lc.length){var g=lc.shift();g.wj(g.mj);if(mc){var l=mc,m=0==l%1?l-1:Math.floor(l);mc=g.tj?m:(8*l+(m+.5))/9}h.setStatus&&(g=h.statusMessage||"Please wait...",l=mc,m=nc.vj,l?l<m?h.setStatus(g+" ("+(m-l)+"/"+m+")"):h.setStatus(g):h.setStatus(""));
f<kc||setTimeout(fc,0)}else if(!(f<kc))if(oc=oc+1|0,1==Zb&&1<$b&&0!=oc%$b)cc();else{0==Zb&&(dc=ec());if(!(la||h.preMainLoop&&!1===h.preMainLoop())){if(!la)try{a(),pc()}catch(q){qc(q)}h.postMainLoop?.()}f<kc||("object"==typeof SDL&&SDL.audio?.Fj?.(),cc())}};e||(b&&0<b?ic(0,1E3/b):ic(1,1),cc());if(c)throw"unwind";},qc=a=>{a instanceof Ja||"unwind"==a||da(1,a)},sc=a=>{ma=a;La||(h.onExit?.(a),la=!0);da(a,new Ja(a))},tc=a=>{ma=a;sc(a)},pc=()=>{if(!La)try{var a=ma;ma=a;sc(a)}catch(b){qc(b)}},uc=a=>{setTimeout(()=>
{if(!la)try{a(),pc()}catch(b){qc(b)}},1E4)},bc=!1,cc=null,kc=0,ac=null,jc=0,Zb=0,$b=0,oc=0,lc=[],nc={},dc,fc,mc,vc=!1,wc=!1,xc=[];
function yc(){function a(){wc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!zc){zc=!0;ib.push({canHandle:function(c){return!h.Bj&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Ac(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Ac(d)}));var l=URL.createObjectURL(g),m=new Image;m.onload=()=>{m.complete||ja(`Image ${d} could not be decoded`);
var q=document.createElement("canvas");q.width=m.width;q.height=m.height;q.getContext("2d").drawImage(m,0,0);URL.revokeObjectURL(l);e?.(c)};m.onerror=()=>{ha(`Image ${l} could not be decoded`);f?.()};m.src=l}});ib.push({canHandle:function(c){return!h.Aj&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,l=URL.createObjectURL(new Blob([c],{type:Ac(d)})),m=new Audio;m.addEventListener("canplaythrough",()=>f(m),!1);m.onerror=function(){if(!g){ha(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var q="",r=0,x=0,M=0;M<c.length;M++)for(r=r<<8|c[M],x+=8;6<=x;){var p=r>>x-6&63;x-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[p]}2==x?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&3)<<4],q+="=="):4==x&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&15)<<2],q+="=");m.src="data:audio/x-"+d.substr(-3)+";base64,"+q;f(m)}};m.src=l;uc(()=>{f(m)})}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!wc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Bc=!1,Cc=void 0,Dc=void 0;function Ec(){if(!vc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Fc=0;
function gc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Fc)Fc=b+1E3/60;else for(;b+2>=Fc;)Fc+=1E3/60;setTimeout(a,Math.max(Fc-b,0))}}function Ac(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Gc=[];function Hc(){var a=h.canvas;Gc.forEach(b=>b(a.width,a.height))}
function Ic(a,b,c){b&&c?(a.jj=b,a.Ni=c):(b=a.jj,c=a.Ni);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Dc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var hc,zc,L=12288,Jc=!1,Kc=0,Lc=0,Mc=0,N={alpha:!1,depth:!1,stencil:!1,antialias:!1},Nc={},Oc,Pc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Qc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Rc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))};
function Sc(a){var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");return(a.getSupportedExtensions()||
[]).filter(c=>b.includes(c))}var Tc=1,Uc=[],O=[],Vc=[],Wc=[],Xc=[],P=[],Yc=[],Zc=[],Q=[],$c=[],ad=[],bd=[],cd={},dd={},ed=4;function R(a){fd||=a}
var gd=a=>{for(var b=Tc++,c=a.length;c<b;c++)a[c]=null;return b},jd=(a,b)=>{a.bh||(a.bh=a.getContext,a.getContext=function(d,e){e=a.bh(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Eh?a.getContext("webgl2",b):a.getContext("webgl",b);return c?hd(c,b):0},hd=(a,b)=>{var c=gd(Zc),d={handle:c,attributes:b,version:b.Eh,jh:a};a.canvas&&(a.canvas.uh=d);Zc[c]=d;("undefined"==typeof b.ci||b.ci)&&kd(d);return c},ld=a=>{S=Zc[a];h.dh=T=S?.jh;return!(a&&!T)},kd=a=>{a||=S;if(!a.Pi){a.Pi=
!0;var b=a.jh;Pc(b);Qc(b);Rc(b);b.uj=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.yj=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Zg=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Zg)b.Zg=b.getExtension("EXT_disjoint_timer_query");b.zj=b.getExtension("WEBGL_multi_draw");Sc(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},md={},fd,S,nd=[],od=(a,b)=>{nd.length=0;for(var c;c=n[a++];){var d=
105!=c;d&=112!=c;b+=d&&b%8?4:0;nd.push(112==c?u[b>>2]:105==c?t[b>>2]:w[b>>3]);b+=d?8:4}return nd},rd=a=>{var b=pd();a=a();qd(b);return a},sd=0,td=[];function ud(a,b,c){function d(g,l){if(g.length!=l.length)return!1;for(var m in g)if(g[m]!=l[m])return!1;return!0}for(var e in td){var f=td[e];if(f.Vh==a&&d(f.Zh,c))return}td.push({Vh:a,mi:b,Zh:c});td.sort((g,l)=>g.mi<l.mi)}function vd(a){for(var b=0;b<td.length;++b)td[b].Vh==a&&(td.splice(b,1),--b)}
function wd(){return navigator.userActivation?navigator.userActivation.isActive:sd&&xd.Ah}function yd(){if(wd())for(var a=0;a<td.length;++a){var b=td[a];td.splice(a,1);--a;b.Vh.apply(null,b.Zh)}}var zd=[];function Ad(a){var b=zd[a];b.target.removeEventListener(b.Tg,b.di,b.Xg);zd.splice(a,1)}
function Bd(a){if(!a.target)return-4;if(a.Yg)a.di=function(c){++sd;xd=a;yd();a.ah(c);yd();--sd},a.target.addEventListener(a.Tg,a.di,a.Xg),zd.push(a);else for(var b=0;b<zd.length;++b)zd[b].target==a.target&&zd[b].Tg==a.Tg&&Ad(b--);return 0}function Cd(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}function Dd(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Ed={},xd,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd={},Sd=[0,document,window],U=a=>{a=2<a?a?C(n,a):"":a;return Sd[a]||document.querySelector(a)},Ud=a=>{var b=Wa(a)+1,c=Td(b);B(a,n,c,b);return c},Vd=a=>rd(()=>{var b=Td(8),c=b+4,d=Ud(a.id);if(d=U(d))t[b>>2]=d.width,t[c>>2]=d.height;return[t[b>>2],t[c>>2]]}),Wd=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},Xd=(a,b,c)=>{a.sj?rd(()=>{var d=Ud(a.id);Wd(d,b,c)}):(a.width=b,a.height=c)},Yd=[],Zd,V=a=>{var b=Yd[a];b||(a>=Yd.length&&(Yd.length=
a+1),Yd[a]=b=Zd.get(a));return b},$d=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Xd(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,m||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=m,a.style.paddingLeft=q,a.style.paddingRight=r,a.style.paddingTop=x,a.style.paddingBottom=M,a.style.marginLeft=p,a.style.marginRight=
D,a.style.marginTop=H,a.style.marginBottom=Y,document.body.style.margin=Gb,document.documentElement.style.overflow=Kf,document.body.scroll=Lf,a.style.kh=Mf,a.uh&&a.uh.jh.viewport(0,0,d,e),Rd.Bh&&V(Rd.Bh)(37,0,Rd.ai))}var c=Vd(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,m=document.body.style.backgroundColor,q=a.style.paddingLeft,r=a.style.paddingRight,x=a.style.paddingTop,M=a.style.paddingBottom,p=a.style.marginLeft,D=a.style.marginRight,H=a.style.marginTop,Y=a.style.marginBottom,
Gb=document.body.style.margin,Kf=document.documentElement.style.overflow,Lf=document.body.scroll,Mf=a.style.kh;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},ae=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},be=a=>0>Sd.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},ce=(a,b)=>{if(0!=b.Uh||0!=b.Qh){$d(a);var c=b.aj?innerWidth:screen.width,d=b.aj?innerHeight:screen.height,e=be(a),
f=e.width;e=e.height;var g=Vd(a),l=g[0];g=g[1];3==b.Uh?(ae(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Uh&&(c*g<l*d?(f=g*c/l,ae(a,(d-f)/2,0),d=f):(f=l*d/g,ae(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Ii&&(a.style.kh="optimizeSpeed",a.style.kh="-moz-crisp-edges",a.style.kh="-o-crisp-edges",a.style.kh="-webkit-optimize-contrast",a.style.kh="optimize-contrast",
a.style.kh="crisp-edges",a.style.kh="pixelated");f=2==b.Qh?devicePixelRatio:1;0!=b.Qh&&(c=c*f|0,d=d*f|0,Xd(a,c,d),a.uh&&a.uh.jh.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Dd()?-3:-1;Rd=b;b.Bh&&V(b.Bh)(37,0,b.ai);return 0},de=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},ee=(a,b)=>{w[a>>3]=b.timestamp;for(var c=
0;c<b.axes.length;++c)w[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)w[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)t[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];t[a+1296>>2]=b.connected;t[a+1300>>2]=b.index;t[a+8>>2]=b.axes.length;t[a+12>>2]=b.buttons.length;B(b.id,n,a+1304,64);B(b.mapping,n,a+1368,64)},fe=(a,b)=>{T.attachShader(O[a],P[b])},ge=(a,b)=>{35051==a?T.Rh=b:35052==a&&(T.eh=b);T.bindBuffer(a,
Uc[b])},he=(a,b)=>{T.bindTexture(a,Xc[b])},ie=a=>{T.bindVertexArray(Yc[a])};function je(a,b){T.blendFunc(a,b)}var ke=(a,b,c,d)=>{2<=S.version?c&&b?T.bufferData(a,n,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?n.subarray(c,c+b):b,d)},le=(a,b,c,d)=>{2<=S.version?c&&T.bufferSubData(a,b,n,d,c):T.bufferSubData(a,b,n.subarray(d,d+c))};function me(a){T.clear(a)}function ne(a,b,c,d){T.clearColor(a,b,c,d)}
var oe=(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},pe=a=>{T.compileShader(P[a])},qe=()=>{var a=gd(O),b=T.createProgram();b.name=a;b.Hh=b.Fh=b.Gh=0;b.Xh=1;O[a]=b;return a},re=a=>{var b=gd(P);P[b]=T.createShader(a);return b},se=(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Uc[d];e&&(T.deleteBuffer(e),e.name=0,Uc[d]=null,d==T.Rh&&(T.Rh=0),d==T.eh&&(T.eh=0))}},te=(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];T.deleteVertexArray(Yc[d]);Yc[d]=null}};function ue(a){T.depthFunc(a)}
var ve=(a,b,c)=>{T.drawArrays(a,b,c)},we=(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},xe=[],ye=(a,b)=>{for(var c=xe[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];T.drawBuffers(c)},ze=(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)};function Ae(a){T.enable(a)}var Be=a=>{T.enableVertexAttribArray(a)},Ce=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=T[c](),g=f&&gd(d);f?(f.name=g,d[g]=f):R(1282);t[b+4*e>>2]=g}},De=(a,b)=>{Ce(a,b,"createBuffer",Uc)},Ee=(a,b)=>{Ce(a,b,"createTexture",Xc)};
function Fe(a,b){Ce(a,b,"createVertexArray",Yc)}var Ge=(a,b,c,d,e,f,g,l)=>{b=O[b];if(a=T[a](b,c))d=l&&B(a.name,n,l,d),e&&(t[e>>2]=d),f&&(t[f>>2]=a.size),g&&(t[g>>2]=a.type)},He=(a,b)=>T.getAttribLocation(O[a],b?C(n,b):""),Ie=(a,b)=>{u[a>>2]=b;u[a+4>>2]=(b-u[a>>2])/4294967296};function Je(){var a=Sc(T);return a=a.concat(a.map(b=>"GL_"+b))}
var Ke=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=T.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>S.version){R(1282);return}d=Je().length;break;case 33307:case 33308:if(2>S.version){R(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=T.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:R(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+4*a>>2]=e[a];break;case 2:v[b+4*a>>2]=e[a];break;case 4:k[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){R(1280);ha(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:R(1280);ha(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:Ie(b,d);break;case 0:t[b>>2]=d;break;case 2:v[b>>2]=d;break;case 4:k[b>>0]=d?1:0}}else R(1281)},Le=(a,b,c,d)=>{if(c){b=T.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:R(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{R(1280);return}break;default:R(1280);return}switch(d){case 1:Ie(c,a);break;case 0:t[c>>2]=a;break;case 2:v[c>>2]=a;break;
case 4:k[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else R(1281)},Me=(a,b,c)=>{if(c){a=Q[a];b=2>S.version?T.Zg.getQueryObjectEXT(a,b):T.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Ie(c,d)}else R(1281)},Ne=(a,b,c)=>{if(c){a=T.Zg.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d}else R(1281)},Oe=(a,b,c,d)=>{a=T.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,n,d,b):0;c&&(t[c>>2]=b)},Pe=(a,b,
c)=>{c?35716==b?(a=T.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(P[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=T.getShaderParameter(P[a],b):R(1281)},Qe=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Re=a=>{var b=a.zh,c=a.ri,d;if(!b)for(a.zh=b={},a.pi={},d=0;d<T.getProgramParameter(a,35718);++d){var e=T.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Qe(f);g=0<g?f.slice(0,g):f;var l=a.Xh;a.Xh+=e;c[g]=[e,l];for(f=0;f<e;++f)b[l]=f,a.pi[l++]=g}},Se=
(a,b)=>{b=b?C(n,b):"";if(a=O[a]){Re(a);var c=a.zh,d=0,e=b,f=Qe(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.ri[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else R(1281);return-1},W=a=>{var b=T.Ai;if(b){var c=b.zh[a];"number"==typeof c&&(b.zh[a]=c=T.getUniformLocation(b,b.pi[a]+(0<c?`[${c}]`:"")));return c}R(1282)},Te=(a,b,c,d)=>{if(c)if(a=O[a],Re(a),a=T.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:v[c>>
2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:v[c+4*b>>2]=a[b]}else R(1281)},Ue=(a,b,c,d)=>{if(c)if(a=T.getVertexAttrib(a,b),34975==b)t[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:v[c>>2]=a;break;case 5:t[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:v[c+4*b>>2]=a[b];break;case 5:t[c+4*b>>2]=Math.fround(a[b])}else R(1281)},Ve=(a,b,c)=>{Ue(a,b,c,0)},We=a=>
(a=Yc[a])?T.isVertexArray(a):0,Xe=a=>{a=O[a];T.linkProgram(a);a.zh=0;a.ri={}},Ye=a=>{a-=5120;return 0==a?k:1==a?n:2==a?na:4==a?t:6==a?v:5==a||28922==a||28520==a||30779==a||30782==a?u:oa},Ze=(a,b,c,d,e)=>{a=Ye(a);var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=ed;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)},$e=(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=Na(u[c+4*f>>2],d?u[d+4*f>>2]:void 0);T.shaderSource(P[a],e)},af=(a,b,c,d,e,
f,g,l,m)=>{if(2<=S.version)if(T.eh)T.texImage2D(a,b,c,d,e,f,g,l,m);else if(m){var q=Ye(l);T.texImage2D(a,b,c,d,e,f,g,l,q,m>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else T.texImage2D(a,b,c,d,e,f,g,l,null);else T.texImage2D(a,b,c,d,e,f,g,l,m?Ze(l,g,d,e,m):null)};function bf(a,b,c){T.texParameteri(a,b,c)}
var cf=(a,b,c,d,e,f,g,l,m)=>{if(2<=S.version)if(T.eh)T.texSubImage2D(a,b,c,d,e,f,g,l,m);else if(m){var q=Ye(l);T.texSubImage2D(a,b,c,d,e,f,g,l,q,m>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else T.texSubImage2D(a,b,c,d,e,f,g,l,null);else q=null,m&&(q=Ze(l,g,e,f,m)),T.texSubImage2D(a,b,c,d,e,f,g,l,q)},df=(a,b)=>{T.uniform1f(W(a),b)},ef=[],ff=[],gf=(a,b,c)=>{T.uniform2f(W(a),b,c)},hf=(a,b,c)=>{if(2<=S.version)b&&T.uniform3fv(W(a),v,c>>2,3*b);else{if(96>=b)for(var d=ef[3*b-1],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>
2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);T.uniform3fv(W(a),d)}},jf=(a,b,c)=>{if(2<=S.version)b&&T.uniform4fv(W(a),v,c>>2,4*b);else{if(72>=b){var d=ef[4*b-1],e=v;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=v.subarray(c>>2,c+16*b>>2);T.uniform4fv(W(a),d)}},kf=(a,b,c,d)=>{if(2<=S.version)b&&T.uniformMatrix4fv(W(a),!!c,v,d>>2,16*b);else{if(18>=b){var e=ef[16*b-1],f=v;d>>=2;for(var g=0;g<16*b;g+=16){var l=
d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=v.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(W(a),!!c,e)}},lf=a=>{a=O[a];T.useProgram(a);T.Ai=a};function mf(a,b){T.vertexAttrib1f(a,b)}function nf(a,b,c){T.vertexAttrib2f(a,b,c)}
var of=(a,b)=>{T.vertexAttribDivisor(a,b)},pf=(a,b,c,d,e,f)=>{T.vertexAttribPointer(a,b,c,!!d,e,f)};function qf(a,b,c,d){T.viewport(a,b,c,d)}
var rf=(a,b)=>{if(!Dd())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?wd()?ce(a,b):b.Ei?(ud(ce,1,[a,b]),1):-2:-3:-4},sf=()=>{try{if(navigator.getGamepads)return(Fd=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},tf=(a,b)=>{var c={target:U(2),Tg:"beforeunload",Yg:b,ah:(d=event)=>{var e=V(b)(28,0,a);e&&=e?C(n,e):"";if(e)return d.preventDefault(),d.returnValue=e},Xg:!0};return Bd(c)},uf=(a,b,c,d,e,f)=>{Gd||=A(256);a={target:U(a),Tg:f,Yg:d,ah:(g=event)=>
{var l=g.target.id?g.target.id:"",m=Gd;B(Cd(g.target),n,m+0,128);B(l,n,m+128,128);V(d)(e,m,b)&&g.preventDefault()},Xg:c};return Bd(a)},vf=(a,b,c,d,e)=>{Id||=A(280);return Bd({target:a,Tg:e,Yg:d,ah:(f=event)=>{var g=Id,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,m=!!l;t[g>>2]=m;t[g+4>>2]=Dd();var q=m?l:Hd,r=q?.id||"";B(Cd(q),n,g+8,128);B(r,n,g+136,128);t[g+264>>2]=q?q.clientWidth:0;t[g+268>>2]=q?q.clientHeight:0;t[g+272>>
2]=screen.width;t[g+276>>2]=screen.height;m&&(Hd=l);V(d)(19,g,b)&&f.preventDefault()},Xg:c})},wf=(a,b,c,d,e)=>{Jd||=A(1432);b={target:U(2),Ah:!0,Tg:e,Yg:c,ah:(f=event)=>{var g=Jd;ee(g,f.gamepad);V(c)(d,g,a)&&f.preventDefault()},Xg:b};return Bd(b)},xf=(a,b,c,d,e,f)=>{Kd||=A(176);a={target:U(a),Tg:f,Yg:d,ah:g=>{var l=Kd;w[l>>3]=g.timeStamp;var m=l>>2;t[m+2]=g.location;t[m+3]=g.ctrlKey;t[m+4]=g.shiftKey;t[m+5]=g.altKey;t[m+6]=g.metaKey;t[m+7]=g.repeat;t[m+8]=g.charCode;t[m+9]=g.keyCode;t[m+10]=g.which;
B(g.key||"",n,l+44,32);B(g.code||"",n,l+76,32);B(g.char||"",n,l+108,32);B(g.locale||"",n,l+140,32);V(d)(e,l,b)&&g.preventDefault()},Xg:c};return Bd(a)},yf=(a,b,c)=>{w[a>>3]=b.timeStamp;a>>=2;t[a+2]=b.screenX;t[a+3]=b.screenY;t[a+4]=b.clientX;t[a+5]=b.clientY;t[a+6]=b.ctrlKey;t[a+7]=b.shiftKey;t[a+8]=b.altKey;t[a+9]=b.metaKey;na[2*a+20]=b.button;na[2*a+21]=b.buttons;t[a+11]=b.movementX;t[a+12]=b.movementY;c=be(c);t[a+13]=b.clientX-c.left;t[a+14]=b.clientY-c.top},zf=(a,b,c,d,e,f)=>{Ld||=A(72);a=U(a);
return Bd({target:a,Ah:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Tg:f,Yg:d,ah:(g=event)=>{yf(Ld,g,a);V(d)(e,Ld,b)&&g.preventDefault()},Xg:c})},Af=(a,b,c,d,e)=>{Md||=A(260);return Bd({target:a,Tg:e,Yg:d,ah:(f=event)=>{var g=Md,l=document.pointerLockElement||document.ti||document.kj||document.ui;t[g>>2]=!!l;var m=l?.id||"";B(Cd(l),n,g+4,128);B(m,n,g+132,128);V(d)(20,g,b)&&f.preventDefault()},Xg:c})},Bf=(a,b,c,d)=>{Nd||=A(36);a=U(a);return Bd({target:a,Tg:"resize",Yg:d,ah:(e=event)=>{if(e.target==
a){var f=document.body;if(f){var g=Nd;t[g>>2]=e.detail;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset;t[g+32>>2]=pageYOffset;V(d)(10,g,b)&&e.preventDefault()}}},Xg:c})},Cf=(a,b,c,d,e,f)=>{Od||=A(1696);a=U(a);return Bd({target:a,Ah:"touchstart"==f||"touchend"==f,Tg:f,Yg:d,ah:g=>{for(var l,m={},q=g.touches,r=0;r<q.length;++r)l=q[r],l.hi=l.li=0,m[l.identifier]=l;for(r=0;r<g.changedTouches.length;++r)l=
g.changedTouches[r],l.hi=1,m[l.identifier]=l;for(r=0;r<g.targetTouches.length;++r)m[g.targetTouches[r].identifier].li=1;q=Od;w[q>>3]=g.timeStamp;var x=q>>2;t[x+3]=g.ctrlKey;t[x+4]=g.shiftKey;t[x+5]=g.altKey;t[x+6]=g.metaKey;x+=7;var M=be(a),p=0;for(r in m)if(l=m[r],t[x]=l.identifier,t[x+1]=l.screenX,t[x+2]=l.screenY,t[x+3]=l.clientX,t[x+4]=l.clientY,t[x+5]=l.pageX,t[x+6]=l.pageY,t[x+7]=l.hi,t[x+8]=l.li,t[x+9]=l.clientX-M.left,t[x+10]=l.clientY-M.top,x+=13,31<++p)break;t[q+8>>2]=p;V(d)(e,q,b)&&g.preventDefault()},
Xg:c})},Df=(a,b,c)=>{var d=Sd[1];Pd||=A(8);return Bd({target:d,Tg:"visibilitychange",Yg:c,ah:(e=event)=>{var f=Pd,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);t[f>>2]=document.hidden;t[f+4>>2]=g;V(c)(21,f,a)&&e.preventDefault()},Xg:b})},Ef=(a,b,c,d)=>{Qd||=A(104);return Bd({target:a,Ah:!0,Tg:"wheel",Yg:d,ah:(e=event)=>{var f=Qd;yf(f,e,a);w[f+72>>3]=e.deltaX;w[f+80>>3]=e.deltaY;w[f+88>>3]=e.deltaZ;t[f+96>>2]=e.deltaMode;V(d)(9,f,b)&&e.preventDefault()},Xg:c})},Ff=
["default","low-power","high-performance"],X={lh:[null],Rg:null},Gf={},If=()=>{if(!Hf){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Gf)void 0===Gf[b]?delete a[b]:a[b]=Gf[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Hf=c}return Hf},Hf,Jf=[31,29,31,30,31,30,31,31,30,31,30,31],Nf=[31,28,31,30,31,30,31,31,30,31,30,31],Of=
(a,b,c,d)=>{function e(p,D,H){for(p="number"==typeof p?p.toString():p||"";p.length<D;)p=H[0]+p;return p}function f(p,D){return e(p,D,"0")}function g(p,D){function H(Gb){return 0>Gb?-1:0<Gb?1:0}var Y;0===(Y=H(p.getFullYear()-D.getFullYear()))&&0===(Y=H(p.getMonth()-D.getMonth()))&&(Y=H(p.getDate()-D.getDate()));return Y}function l(p){switch(p.getDay()){case 0:return new Date(p.getFullYear()-1,11,29);case 1:return p;case 2:return new Date(p.getFullYear(),0,3);case 3:return new Date(p.getFullYear(),
0,2);case 4:return new Date(p.getFullYear(),0,1);case 5:return new Date(p.getFullYear()-1,11,31);case 6:return new Date(p.getFullYear()-1,11,30)}}function m(p){var D=p.ph;for(p=new Date((new Date(p.qh+1900,0,1)).getTime());0<D;){var H=p.getMonth(),Y=(Wb(p.getFullYear())?Jf:Nf)[H];if(D>Y-p.getDate())D-=Y-p.getDate()+1,p.setDate(1),11>H?p.setMonth(H+1):(p.setMonth(0),p.setFullYear(p.getFullYear()+1));else{p.setDate(p.getDate()+D);break}}H=new Date(p.getFullYear()+1,0,4);D=l(new Date(p.getFullYear(),
0,4));H=l(H);return 0>=g(D,p)?0>=g(H,p)?p.getFullYear()+1:p.getFullYear():p.getFullYear()-1}var q=u[d+40>>2];d={fj:t[d>>2],ej:t[d+4>>2],Nh:t[d+8>>2],Wh:t[d+12>>2],Oh:t[d+16>>2],qh:t[d+20>>2],hh:t[d+24>>2],ph:t[d+28>>2],Ij:t[d+32>>2],dj:t[d+36>>2],gj:q?q?C(n,q):"":""};c=c?C(n,c):"";q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in q)c=c.replace(new RegExp(r,"g"),q[r]);var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),M="January February March April May June July August September October November December".split(" ");q={"%a":p=>x[p.hh].substring(0,3),"%A":p=>x[p.hh],"%b":p=>M[p.Oh].substring(0,3),"%B":p=>M[p.Oh],"%C":p=>f((p.qh+1900)/
100|0,2),"%d":p=>f(p.Wh,2),"%e":p=>e(p.Wh,2," "),"%g":p=>m(p).toString().substring(2),"%G":m,"%H":p=>f(p.Nh,2),"%I":p=>{p=p.Nh;0==p?p=12:12<p&&(p-=12);return f(p,2)},"%j":p=>{for(var D=0,H=0;H<=p.Oh-1;D+=(Wb(p.qh+1900)?Jf:Nf)[H++]);return f(p.Wh+D,3)},"%m":p=>f(p.Oh+1,2),"%M":p=>f(p.ej,2),"%n":()=>"\n","%p":p=>0<=p.Nh&&12>p.Nh?"AM":"PM","%S":p=>f(p.fj,2),"%t":()=>"\t","%u":p=>p.hh||7,"%U":p=>f(Math.floor((p.ph+7-p.hh)/7),2),"%V":p=>{var D=Math.floor((p.ph+7-(p.hh+6)%7)/7);2>=(p.hh+371-p.ph-2)%7&&
D++;if(D)53==D&&(H=(p.hh+371-p.ph)%7,4==H||3==H&&Wb(p.qh)||(D=1));else{D=52;var H=(p.hh+7-p.ph-1)%7;(4==H||5==H&&Wb(p.qh%400-1))&&D++}return f(D,2)},"%w":p=>p.hh,"%W":p=>f(Math.floor((p.ph+7-(p.hh+6)%7)/7),2),"%y":p=>(p.qh+1900).toString().substring(2),"%Y":p=>p.qh+1900,"%z":p=>{p=p.dj;var D=0<=p;p=Math.abs(p)/60;return(D?"+":"-")+String("0000"+(p/60*100+p%60)).slice(-4)},"%Z":p=>p.gj,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(r in q)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),q[r](d)));c=
c.replace(/\0\0/g,"%");r=Xa(c,!1);if(r.length>b)return 0;k.set(r,a);return r.length-1};function Cb(a,b,c,d){a||=this;this.parent=a;this.Wg=a.Wg;this.sh=null;this.id=ub++;this.name=b;this.mode=c;this.Ng={};this.Pg={};this.xh=d}Object.defineProperties(Cb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});
[44].forEach(a=>{gb[a]=new F(a);gb[a].stack="<generic error, no stack>"});vb=Array(4096);Ga(G,"/");Fa("/tmp");Fa("/home");Fa("/home/web_user");(function(){Fa("/dev");$a(259,{read:()=>0,write:(d,e,f,g)=>g});Mb("/dev/null",259);Za(1280,bb);Za(1536,cb);Mb("/dev/tty",1280);Mb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ta(a).byteLength);return a[--b]};Rb("random",c);Rb("urandom",c);Fa("/dev/shm");Fa("/dev/shm/tmp")})();
(function(){Fa("/proc");var a=Fa("/proc/self");Fa("/proc/self/fd");Ga({Wg(){var b=fb(a,"fd",16895,73);b.Ng={vh(c,d){var e=Hb(+d);c={parent:null,Wg:{wh:"fake"},Ng:{yh:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
h.requestFullscreen=function(a,b){function c(){vc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Ec,Cc&&d.requestPointerLock(),vc=!0,Dc?("undefined"!=typeof SDL&&(t[SDL.screen>>2]=u[SDL.screen>>2]|8388608),Ic(h.canvas),Hc()):Ic(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Dc?("undefined"!=typeof SDL&&(t[SDL.screen>>2]=
u[SDL.screen>>2]&-8388609),Ic(h.canvas),Hc()):Ic(d));h.onFullScreen?.(vc);h.onFullscreen?.(vc)}Cc=a;Dc=b;"undefined"==typeof Cc&&(Cc=!0);"undefined"==typeof Dc&&(Dc=!1);var d=h.canvas;Bc||(Bc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=gc;h.setCanvasSize=function(a,b,c){Ic(h.canvas,a,b);c||Hc()};h.pauseMainLoop=function(){cc=null;kc++};h.resumeMainLoop=function(){kc++;var a=Zb,b=$b,c=ac;ac=null;rc(c,0,!1,jc,!0);ic(a,b);cc()};
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.dh&&a==h.canvas)return h.dh;var e;if(b){var f={antialias:!1,alpha:!1,Eh:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof md&&(e=jd(a,f)))var l=Zc[e].jh}else l=a.getContext("2d");if(!l)return null;c&&(b||"undefined"==typeof T||ja("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.dh=l,b&&ld(e),h.ij=b,xc.forEach(m=>m()),yc());return l};for(var T,Z=0;32>Z;++Z)xe.push(Array(Z));
var Pf=new Float32Array(288);for(Z=0;288>Z;++Z)ef[Z]=Pf.subarray(0,Z+1);var Qf=new Int32Array(288);for(Z=0;288>Z;++Z)ff[Z]=Qf.subarray(0,Z+1);
var Sf={a:(a,b,c,d)=>{ja(`Assertion failed: ${a?C(n,a):""}, at: `+[b?b?C(n,b):"":"unknown filename",c,d?d?C(n,d):"":"unknown function"])},la:function(a,b,c){Ub=c;try{var d=Hb(a);switch(b){case 0:var e=Vb();if(0>e)break;for(;tb[e];)e++;return Ib(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Vb(),d.flags|=e,0;case 12:return e=Vb(),na[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof Tb||"ErrnoError"!==f.name)throw f;return-f.$g}},Pa:function(a,b,c){try{var d=
Hb(a);d.nh||(d.nh=kb(d.path));a=0;for(var e=Pb(d,0,1),f=Math.floor(e/280);f<d.nh.length&&a+280<=c;){var g=d.nh[f];if("."===g){var l=d.node.id;var m=4}else if(".."===g)l=J(d.path,{parent:!0}).node.id,m=4;else{var q=hb(d.node,g);l=q.id;m=8192===(q.mode&61440)?2:I(q.mode)?4:40960===(q.mode&61440)?10:8}z=[l>>>0,(y=l,1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];t[b+a>>2]=z[0];t[b+a+4>>2]=z[1];z=[280*(f+1)>>>0,(y=280*(f+1),1<=+Math.abs(y)?0<y?+Math.floor(y/
4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];t[b+a+8>>2]=z[0];t[b+a+12>>2]=z[1];na[b+a+16>>1]=280;k[b+a+18>>0]=m;B(g,n,b+a+19,256);a+=280;f+=1}Pb(d,280*f,0);return a}catch(r){if("undefined"==typeof Tb||"ErrnoError"!==r.name)throw r;return-r.$g}},Ya:function(a,b,c){Ub=c;try{var d=Hb(a);switch(b){case 21509:return d.Qg?0:-59;case 21505:if(!d.Qg)return-59;if(d.Qg.ih.Ri){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Vb();t[e>>2]=25856;t[e+4>>2]=
5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;32>f;f++)k[e+f+17>>0]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Qg?0:-59;case 21506:case 21507:case 21508:if(!d.Qg)return-59;if(d.Qg.ih.Si)for(e=Vb(),a=[],f=0;32>f;f++)a.push(k[e+f+17>>0]);return 0;case 21519:if(!d.Qg)return-59;e=Vb();return t[e>>2]=0;case 21520:return d.Qg?-28:-59;case 21531:e=Vb();if(!d.Pg.Qi)throw new F(59);return d.Pg.Qi(d,b,e);case 21523:if(!d.Qg)return-59;d.Qg.ih.Ti&&(f=[24,80],e=Vb(),na[e>>1]=f[0],na[e+2>>1]=f[1]);
return 0;case 21524:return d.Qg?0:-59;case 21515:return d.Qg?0:-59;default:return-28}}catch(g){if("undefined"==typeof Tb||"ErrnoError"!==g.name)throw g;return-g.$g}},ma:function(a,b,c,d){Ub=d;try{b=b?C(n,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":Hb(a).path;if(0==e.length)throw new F(44);b=Pa(f+"/"+e)}var g=d?Vb():0;return mb(b,c,g).fd}catch(l){if("undefined"==typeof Tb||"ErrnoError"!==l.name)throw l;return-l.$g}},Na:function(a,b){try{a=a?C(n,a):"";var c=lb(a);t[b>>2]=c.Fi;t[b+
4>>2]=c.mode;u[b+8>>2]=c.Xi;t[b+12>>2]=c.uid;t[b+16>>2]=c.Mi;t[b+20>>2]=c.xh;z=[c.size>>>0,(y=c.size,1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];t[b+24>>2]=z[0];t[b+28>>2]=z[1];t[b+32>>2]=4096;t[b+36>>2]=c.xi;var d=c.vi.getTime(),e=c.Jh.getTime(),f=c.yi.getTime();z=[Math.floor(d/1E3)>>>0,(y=Math.floor(d/1E3),1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];t[b+40>>2]=z[0];t[b+44>>2]=z[1];u[b+48>>
2]=d%1E3*1E3;z=[Math.floor(e/1E3)>>>0,(y=Math.floor(e/1E3),1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];t[b+56>>2]=z[0];t[b+60>>2]=z[1];u[b+64>>2]=e%1E3*1E3;z=[Math.floor(f/1E3)>>>0,(y=Math.floor(f/1E3),1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];t[b+72>>2]=z[0];t[b+76>>2]=z[1];u[b+80>>2]=f%1E3*1E3;z=[c.gi>>>0,(y=c.gi,1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>
0))/4294967296)>>>0:0)];t[b+88>>2]=z[0];t[b+92>>2]=z[1];return 0}catch(g){if("undefined"==typeof Tb||"ErrnoError"!==g.name)throw g;return-g.$g}},Za:()=>1,La:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));t[c>>2]=a.getSeconds();t[c+4>>2]=a.getMinutes();t[c+8>>2]=a.getHours();t[c+12>>2]=a.getDate();t[c+16>>2]=a.getMonth();t[c+20>>2]=a.getFullYear()-1900;t[c+24>>2]=a.getDay();t[c+28>>2]=(Wb(a.getFullYear())?Xb:Yb)[a.getMonth()]+a.getDate()-1|0;t[c+36>>2]=-(60*a.getTimezoneOffset());
b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();t[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},Ra:(a,b,c)=>{function d(m){return(m=m.toTimeString().match(/\(([A-Za-z ]+)\)$/))?m[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var l=g.getTimezoneOffset();u[a>>2]=60*Math.max(e,l);t[b>>2]=Number(e!=l);a=d(f);b=d(g);a=K(a);b=K(b);l<e?(u[c>>2]=a,u[c+4>>2]=b):(u[c>>2]=b,u[c+4>>
2]=a)},c:()=>{ja("")},xg:function(a){navigator.clipboard&&navigator.clipboard.writeText(a?C(n,a):"")},zc:a=>{if(12448==a)return L=12288,1;L=12300;return 0},Ne:(a,b,c,d,e)=>{if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=t[b>>2];if(12321==a)N.alpha=0<t[b+4>>2];else if(12325==a)N.depth=0<t[b+4>>2];else if(12326==a)N.stencil=0<t[b+4>>2];else if(12337==a)a=t[b+4>>2],N.antialias=0<a;else if(12338==a)a=t[b+4>>2],N.antialias=1==a;else if(12544==a)N.xj=12547!=t[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&
(t[e>>2]=1),c&&0<d&&(u[c>>2]=62002),L=12288,c=1):(L=12300,c=0)}return c},re:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;for(a=1;;){b=t[d>>2];if(12440==b)a=t[d+4>>2];else if(12344==b)break;else return L=12292,0;d+=8}if(2>a||3<a)return L=12293,0;N.Eh=a-1;N.Wi=0;Oc=jd(h.canvas,N);if(0!=Oc)return L=12288,ld(Oc),h.ij=!0,xc.forEach(function(e){e()}),ld(null),62004;L=12297;return 0},Xd:(a,b)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},ge:(a,b)=>{if(62E3!=a)return L=12296,
0;if(62004!=b)return L=12294,0;a=Oc;S===Zc[a]&&(S=null);if("object"==typeof Ed)for(var c=Zc[a].jh.canvas,d=0;d<zd.length;++d)zd[d].target!=c||Ad(d--);Zc[a]&&Zc[a].jh.canvas&&(Zc[a].jh.canvas.uh=void 0);Zc[a]=null;L=12288;Kc==b&&(Kc=0);return 1},Md:(a,b)=>{if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;Lc==b&&(Lc=0);Mc==b&&(Mc=0);L=12288;return 1},Ce:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return t[d>>2]=N.alpha?
32:24,1;case 12321:return t[d>>2]=N.alpha?8:0,1;case 12322:return t[d>>2]=8,1;case 12323:return t[d>>2]=8,1;case 12324:return t[d>>2]=8,1;case 12325:return t[d>>2]=N.depth?24:0,1;case 12326:return t[d>>2]=N.stencil?8:0,1;case 12327:return t[d>>2]=12344,1;case 12328:return t[d>>2]=62002,1;case 12329:return t[d>>2]=0,1;case 12330:return t[d>>2]=4096,1;case 12331:return t[d>>2]=16777216,1;case 12332:return t[d>>2]=4096,1;case 12333:return t[d>>2]=0,1;case 12334:return t[d>>2]=0,1;case 12335:return t[d>>
2]=12344,1;case 12337:return t[d>>2]=N.antialias?4:0,1;case 12338:return t[d>>2]=N.antialias?1:0,1;case 12339:return t[d>>2]=4,1;case 12340:return t[d>>2]=12344,1;case 12341:case 12342:case 12343:return t[d>>2]=-1,1;case 12345:case 12346:return t[d>>2]=0,1;case 12347:return t[d>>2]=0,1;case 12348:return t[d>>2]=1;case 12349:case 12350:return t[d>>2]=0,1;case 12351:return t[d>>2]=12430,1;case 12352:return t[d>>2]=4,1;case 12354:return t[d>>2]=0,1;default:return L=12292,0}},oa:a=>{L=12288;return 0!=
a&&1!=a?0:62E3},dc:()=>L,hf:(a,b,c)=>{if(62E3!=a)return L=12296,0;b&&(t[b>>2]=1);c&&(t[c>>2]=4);Jc=!0;L=12288;return 1},Bd:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return L=12301,0;ld(d?Oc:null);Kc=d;Mc=b;Lc=c;L=12288;return 1},oc:(a,b)=>{if(62E3!=a)return L=12296,0;L=12288;if(Nc[b])return Nc[b];switch(b){case 12371:a=K("Emscripten");break;case 12372:a=K("1.4 Emscripten EGL");break;case 12373:a=K("");break;case 12429:a=K("OpenGL_ES");
break;default:return L=12300,0}return Nc[b]=a},qd:()=>{if(Jc)if(h.dh)if(h.dh.isContextLost())L=12302;else return L=12288,1;else L=12290;else L=12289;return 0},fd:(a,b)=>{if(62E3!=a)return L=12296,0;0==b?ic(0,0):ic(1,b);L=12288;return 1},Ye:a=>{if(62E3!=a)return L=12296,0;Mc=Lc=Kc=0;Jc=!1;L=12288;return 1},Kc:()=>{L=12288;return 1},Wc:()=>{L=12288;return 1},pa:(a,b,c)=>{b=od(b,c);return Ia[a].apply(null,b)},p:(a,b,c)=>{b=od(b,c);return Ia[a].apply(null,b)},C:()=>Date.now(),Ia:()=>{if(!Dd())return-1;
vd(ce);var a=Sd[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},d:()=>{vd(de);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},o:()=>devicePixelRatio,n:(a,b,c)=>{a=U(a);if(!a)return-4;a=be(a);w[b>>3]=a.width;w[c>>3]=a.height;return 0},S:(a,b)=>{if(0>a||a>=Fd.length)return-5;if(!Fd[a])return-7;ee(b,Fd[a]);return 0},B:ec,Ha:()=>Fd.length,Ub:(a,b)=>{t[a>>
2]=screen.width;t[b>>2]=screen.height},_f:function(a){T.activeTexture(a)},Zf:fe,Pc:(a,b)=>{T.beginQuery(a,Q[b])},og:(a,b)=>{T.Zg.beginQueryEXT(a,Q[b])},tc:function(a){T.beginTransformFeedback(a)},Yf:(a,b,c)=>{T.bindAttribLocation(O[a],b,c?C(n,c):"")},Xf:ge,qc:(a,b,c)=>{T.bindBufferBase(a,b,Uc[c])},rc:(a,b,c,d,e)=>{T.bindBufferRange(a,b,Uc[c],d,e)},Wf:(a,b)=>{T.bindFramebuffer(a,Vc[b])},Vf:(a,b)=>{T.bindRenderbuffer(a,Wc[b])},vb:(a,b)=>{T.bindSampler(a,$c[b])},Uf:he,nb:(a,b)=>{T.bindTransformFeedback(a,
ad[b])},yc:ie,gg:ie,Tf:function(a,b,c,d){T.blendColor(a,b,c,d)},Sf:function(a){T.blendEquation(a)},Rf:function(a,b){T.blendEquationSeparate(a,b)},Qf:je,Pf:function(a,b,c,d){T.blendFuncSeparate(a,b,c,d)},Cc:function(a,b,c,d,e,f,g,l,m,q){T.blitFramebuffer(a,b,c,d,e,f,g,l,m,q)},Of:ke,Nf:le,Mf:function(a){return T.checkFramebufferStatus(a)},Lf:me,Sb:function(a,b,c,d){T.clearBufferfi(a,b,c,d)},Tb:(a,b,c)=>{T.clearBufferfv(a,b,v,c>>2)},Wb:(a,b,c)=>{T.clearBufferiv(a,b,t,c>>2)},Vb:(a,b,c)=>{T.clearBufferuiv(a,
b,u,c>>2)},Kf:ne,Jf:function(a){T.clearDepth(a)},If:function(a){T.clearStencil(a)},Eb:(a,b,c,d)=>T.clientWaitSync(bd[a],b,(c>>>0)+4294967296*d),Hf:oe,Gf:pe,Ff:(a,b,c,d,e,f,g,l)=>{2<=S.version?T.eh||!g?T.compressedTexImage2D(a,b,c,d,e,f,g,l):T.compressedTexImage2D(a,b,c,d,e,f,n,l,g):T.compressedTexImage2D(a,b,c,d,e,f,l?n.subarray(l,l+g):null)},Uc:(a,b,c,d,e,f,g,l,m)=>{T.eh?T.compressedTexImage3D(a,b,c,d,e,f,g,l,m):T.compressedTexImage3D(a,b,c,d,e,f,g,n,m,l)},Ef:(a,b,c,d,e,f,g,l,m)=>{2<=S.version?T.eh||
!l?T.compressedTexSubImage2D(a,b,c,d,e,f,g,l,m):T.compressedTexSubImage2D(a,b,c,d,e,f,g,n,m,l):T.compressedTexSubImage2D(a,b,c,d,e,f,g,m?n.subarray(m,m+l):null)},Tc:(a,b,c,d,e,f,g,l,m,q,r)=>{T.eh?T.compressedTexSubImage3D(a,b,c,d,e,f,g,l,m,q,r):T.compressedTexSubImage3D(a,b,c,d,e,f,g,l,m,n,r,q)},Qb:function(a,b,c,d,e){T.copyBufferSubData(a,b,c,d,e)},Df:function(a,b,c,d,e,f,g,l){T.copyTexImage2D(a,b,c,d,e,f,g,l)},Cf:function(a,b,c,d,e,f,g,l){T.copyTexSubImage2D(a,b,c,d,e,f,g,l)},Vc:function(a,b,c,
d,e,f,g,l,m){T.copyTexSubImage3D(a,b,c,d,e,f,g,l,m)},Bf:qe,Af:re,zf:function(a){T.cullFace(a)},yf:se,xf:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=Vc[d];e&&(T.deleteFramebuffer(e),e.name=0,Vc[d]=null)}},wf:a=>{if(a){var b=O[a];b?(T.deleteProgram(b),b.name=0,O[a]=null):R(1281)}},Rc:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Q[d];e&&(T.deleteQuery(e),Q[d]=null)}},rg:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Q[d];e&&(T.Zg.deleteQueryEXT(e),Q[d]=null)}},vf:(a,b)=>{for(var c=0;c<a;c++){var d=
t[b+4*c>>2],e=Wc[d];e&&(T.deleteRenderbuffer(e),e.name=0,Wc[d]=null)}},xb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=$c[d];e&&(T.deleteSampler(e),e.name=0,$c[d]=null)}},uf:a=>{if(a){var b=P[a];b?(T.deleteShader(b),P[a]=null):R(1281)}},Fb:a=>{if(a){var b=bd[a];b?(T.deleteSync(b),b.name=0,bd[a]=null):R(1281)}},tf:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Xc[d];e&&(T.deleteTexture(e),e.name=0,Xc[d]=null)}},mb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=ad[d];e&&(T.deleteTransformFeedback(e),
e.name=0,ad[d]=null)}},xc:te,fg:te,sf:ue,rf:a=>{T.depthMask(!!a)},qf:function(a,b){T.depthRange(a,b)},pf:(a,b)=>{T.detachShader(O[a],P[b])},of:function(a){T.disable(a)},nf:a=>{T.disableVertexAttribArray(a)},mf:ve,Jb:we,bg:we,dd:we,ed:we,_a:we,Jc:ye,$c:ye,cg:ye,lf:(a,b,c,d)=>{T.drawElements(a,b,c,d)},Ib:ze,ag:ze,ad:ze,bd:ze,cd:ze,Zc:(a,b,c,d,e,f)=>{T.drawElements(a,d,e,f)},kf:Ae,jf:Be,Oc:function(a){T.endQuery(a)},ng:a=>{T.Zg.endQueryEXT(a)},sc:function(){T.endTransformFeedback()},Hb:(a,b)=>(a=T.fenceSync(a,
b))?(b=gd(bd),a.name=b,bd[b]=a,b):0,gf:function(){T.finish()},ff:function(){T.flush()},ef:(a,b,c,d)=>{T.framebufferRenderbuffer(a,b,c,Wc[d])},df:(a,b,c,d,e)=>{T.framebufferTexture2D(a,b,c,Xc[d],e)},Ac:(a,b,c,d,e)=>{T.framebufferTextureLayer(a,b,Xc[c],d,e)},cf:function(a){T.frontFace(a)},bf:De,$e:(a,b)=>{Ce(a,b,"createFramebuffer",Vc)},Sc:(a,b)=>{Ce(a,b,"createQuery",Q)},sg:(a,b)=>{for(var c=0;c<a;c++){var d=T.Zg.createQueryEXT();if(!d){for(R(1282);c<a;)t[b+4*c++>>2]=0;break}var e=gd(Q);d.name=e;Q[e]=
d;t[b+4*c>>2]=e}},_e:(a,b)=>{Ce(a,b,"createRenderbuffer",Wc)},yb:(a,b)=>{Ce(a,b,"createSampler",$c)},Ze:Ee,lb:(a,b)=>{Ce(a,b,"createTransformFeedback",ad)},wc:Fe,eg:Fe,af:function(a){T.generateMipmap(a)},Xe:(a,b,c,d,e,f,g)=>{Ge("getActiveAttrib",a,b,c,d,e,f,g)},We:(a,b,c,d,e,f,g)=>{Ge("getActiveUniform",a,b,c,d,e,f,g)},Lb:(a,b,c,d,e)=>{a=O[a];if(a=T.getActiveUniformBlockName(a,b))e&&0<c?(c=B(a,n,e,c),d&&(t[d>>2]=c)):d&&(t[d>>2]=0)},Mb:(a,b,c,d)=>{if(d)if(a=O[a],35393==c)t[d>>2]=T.getActiveUniformBlockName(a,
b).length+1;else{if(a=T.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)t[d+4*c>>2]=a[c];else t[d>>2]=a}else R(1281)},Ob:(a,b,c,d,e)=>{if(e)if(0<b&&0==c)R(1281);else{a=O[a];for(var f=[],g=0;g<b;g++)f.push(t[c+4*g>>2]);if(a=T.getActiveUniforms(a,f,d))for(b=a.length,g=0;g<b;g++)t[e+4*g>>2]=a[g]}else R(1281)},Ve:(a,b,c,d)=>{a=T.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);t[c>>2]=e;for(b=0;b<e;++b)t[d+4*b>>2]=P.indexOf(a[b])},Ue:He,Te:(a,b)=>Ke(a,b,4),zb:(a,b,
c)=>{c?Ie(c,T.getBufferParameter(a,b)):R(1281)},Se:(a,b,c)=>{c?t[c>>2]=T.getBufferParameter(a,b):R(1281)},Re:()=>{var a=T.getError()||fd;fd=0;return a},Qe:(a,b)=>Ke(a,b,2),ec:(a,b)=>T.getFragDataLocation(O[a],b?C(n,b):""),Pe:(a,b,c,d)=>{a=T.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;t[d>>2]=a},Ab:(a,b,c)=>Le(a,b,c,1),Cb:(a,b)=>{Ke(a,b,1)},uc:(a,b,c)=>Le(a,b,c,0),Oe:(a,b)=>Ke(a,b,0),ab:(a,b,c,d,e)=>{if(0>d)R(1281);else if(e){if(a=
T.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)t[e+4*b>>2]=a[b]}else R(1281)},hb:()=>{R(1282)},Le:(a,b,c,d)=>{a=T.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,n,d,b):0;c&&(t[c>>2]=b)},Me:(a,b,c)=>{if(c)if(a>=Tc)R(1281);else if(a=O[a],35716==b)a=T.getProgramInfoLog(a),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.Hh)for(b=0;b<T.getProgramParameter(a,35718);++b)a.Hh=Math.max(a.Hh,T.getActiveUniform(a,b).name.length+1);t[c>>
2]=a.Hh}else if(35722==b){if(!a.Fh)for(b=0;b<T.getProgramParameter(a,35721);++b)a.Fh=Math.max(a.Fh,T.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.Fh}else if(35381==b){if(!a.Gh)for(b=0;b<T.getProgramParameter(a,35382);++b)a.Gh=Math.max(a.Gh,T.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.Gh}else t[c>>2]=T.getProgramParameter(a,b);else R(1281)},ig:Me,kg:Ne,hg:Me,Mc:(a,b,c)=>{if(c){a=T.getQueryParameter(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d}else R(1281)},jg:Ne,Nc:(a,b,c)=>{c?
t[c>>2]=T.getQuery(a,b):R(1281)},lg:(a,b,c)=>{c?t[c>>2]=T.Zg.getQueryEXT(a,b):R(1281)},Ke:(a,b,c)=>{c?t[c>>2]=T.getRenderbufferParameter(a,b):R(1281)},pb:(a,b,c)=>{c?v[c>>2]=T.getSamplerParameter($c[a],b):R(1281)},qb:(a,b,c)=>{c?t[c>>2]=T.getSamplerParameter($c[a],b):R(1281)},Ie:Oe,He:(a,b,c,d)=>{a=T.getShaderPrecisionFormat(a,b);t[c>>2]=a.rangeMin;t[c+4>>2]=a.rangeMax;t[d>>2]=a.precision},Ge:(a,b,c,d)=>{if(a=T.getShaderSource(P[a]))b=0<b&&d?B(a,n,d,b):0,c&&(t[c>>2]=b)},Je:Pe,Fe:a=>{var b=cd[a];if(!b){switch(a){case 7939:b=
K(Je().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=T.getParameter(a))||R(1280);b=b?K(b):0;break;case 7938:b=T.getParameter(7938);b=2<=S.version?`OpenGL ES 3.0 (${b})`:`OpenGL ES 2.0 (${b})`;b=K(b);break;case 35724:b=T.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=K(b);break;default:R(1280)}cd[a]=b}return b},Rb:(a,b)=>{if(2>S.version)return R(1282),0;var c=dd[a];if(c)return 0>
b||b>=c.length?(R(1281),0):c[b];switch(a){case 7939:return c=Je().map(K),c=dd[a]=c,0>b||b>=c.length?(R(1281),0):c[b];default:return R(1280),0}},Bb:(a,b,c,d,e)=>{0>c?R(1281):e?(a=T.getSyncParameter(bd[a],b),null!==a&&(t[e>>2]=a,d&&(t[d>>2]=1))):R(1281)},Ee:(a,b,c)=>{c?v[c>>2]=T.getTexParameter(a,b):R(1281)},De:(a,b,c)=>{c?t[c>>2]=T.getTexParameter(a,b):R(1281)},nc:(a,b,c,d,e,f,g)=>{a=O[a];if(a=T.getTransformFeedbackVarying(a,b))g&&0<c?(c=B(a.name,n,g,c),d&&(t[d>>2]=c)):d&&(t[d>>2]=0),e&&(t[e>>2]=a.size),
f&&(t[f>>2]=a.type)},Nb:(a,b)=>T.getUniformBlockIndex(O[a],b?C(n,b):""),Pb:(a,b,c,d)=>{if(d)if(0<b&&(0==c||0==d))R(1281);else{a=O[a];for(var e=[],f=0;f<b;f++)e.push(Na(t[c+4*f>>2]));if(a=T.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)t[d+4*f>>2]=a[f]}else R(1281)},ze:Se,Be:(a,b,c)=>{Te(a,b,c,2)},Ae:(a,b,c)=>{Te(a,b,c,0)},fc:(a,b,c)=>Te(a,b,c,0),lc:Ve,kc:Ve,we:(a,b,c)=>{c?t[c>>2]=T.getVertexAttribOffset(a,b):R(1281)},ye:(a,b,c)=>{Ue(a,b,c,2)},xe:(a,b,c)=>{Ue(a,b,c,5)},ve:function(a,b){T.hint(a,
b)},eb:(a,b,c)=>{for(var d=xe[b],e=0;e<b;e++)d[e]=t[c+4*e>>2];T.invalidateFramebuffer(a,d)},db:(a,b,c,d,e,f,g)=>{for(var l=xe[b],m=0;m<b;m++)l[m]=t[c+4*m>>2];T.invalidateSubFramebuffer(a,l,d,e,f,g)},ue:a=>(a=Uc[a])?T.isBuffer(a):0,te:function(a){return T.isEnabled(a)},se:a=>(a=Vc[a])?T.isFramebuffer(a):0,qe:a=>(a=O[a])?T.isProgram(a):0,Qc:a=>(a=Q[a])?T.isQuery(a):0,qg:a=>(a=Q[a])?T.Zg.isQueryEXT(a):0,pe:a=>(a=Wc[a])?T.isRenderbuffer(a):0,wb:a=>(a=$c[a])?T.isSampler(a):0,oe:a=>(a=P[a])?T.isShader(a):
0,Gb:a=>T.isSync(bd[a]),ne:a=>(a=Xc[a])?T.isTexture(a):0,kb:a=>T.isTransformFeedback(ad[a]),vc:We,dg:We,me:function(a){T.lineWidth(a)},le:Xe,jb:function(){T.pauseTransformFeedback()},ke:(a,b)=>{3317==a&&(ed=b);T.pixelStorei(a,b)},je:function(a,b){T.polygonOffset(a,b)},gb:()=>{R(1280)},fb:()=>{R(1280)},mg:(a,b)=>{T.Zg.queryCounterEXT(Q[a],b)},_c:function(a){T.readBuffer(a)},ie:(a,b,c,d,e,f,g)=>{if(2<=S.version)if(T.Rh)T.readPixels(a,b,c,d,e,f,g);else{var l=Ye(f);T.readPixels(a,b,c,d,e,f,l,g>>31-Math.clz32(l.BYTES_PER_ELEMENT))}else(g=
Ze(f,e,c,d,g))?T.readPixels(a,b,c,d,e,f,g):R(1280)},he:()=>{},fe:function(a,b,c,d){T.renderbufferStorage(a,b,c,d)},Bc:function(a,b,c,d,e){T.renderbufferStorageMultisample(a,b,c,d,e)},ib:function(){T.resumeTransformFeedback()},ee:(a,b)=>{T.sampleCoverage(a,!!b)},sb:(a,b,c)=>{T.samplerParameterf($c[a],b,c)},rb:(a,b,c)=>{T.samplerParameterf($c[a],b,v[c>>2])},ub:(a,b,c)=>{T.samplerParameteri($c[a],b,c)},tb:(a,b,c)=>{T.samplerParameteri($c[a],b,t[c>>2])},de:function(a,b,c,d){T.scissor(a,b,c,d)},ce:()=>
{R(1280)},be:$e,ae:function(a,b,c){T.stencilFunc(a,b,c)},$d:function(a,b,c,d){T.stencilFuncSeparate(a,b,c,d)},_d:function(a){T.stencilMask(a)},Zd:function(a,b){T.stencilMaskSeparate(a,b)},Yd:function(a,b,c){T.stencilOp(a,b,c)},Wd:function(a,b,c,d){T.stencilOpSeparate(a,b,c,d)},Vd:af,Yc:(a,b,c,d,e,f,g,l,m,q)=>{if(T.eh)T.texImage3D(a,b,c,d,e,f,g,l,m,q);else if(q){var r=Ye(m);T.texImage3D(a,b,c,d,e,f,g,l,m,r,q>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else T.texImage3D(a,b,c,d,e,f,g,l,m,null)},Ud:function(a,
b,c){T.texParameterf(a,b,c)},Td:(a,b,c)=>{T.texParameterf(a,b,v[c>>2])},Sd:bf,Rd:(a,b,c)=>{T.texParameteri(a,b,t[c>>2])},cb:function(a,b,c,d,e){T.texStorage2D(a,b,c,d,e)},bb:function(a,b,c,d,e,f){T.texStorage3D(a,b,c,d,e,f)},Qd:cf,Xc:(a,b,c,d,e,f,g,l,m,q,r)=>{if(T.eh)T.texSubImage3D(a,b,c,d,e,f,g,l,m,q,r);else if(r){var x=Ye(q);T.texSubImage3D(a,b,c,d,e,f,g,l,m,q,x,r>>31-Math.clz32(x.BYTES_PER_ELEMENT))}else T.texSubImage3D(a,b,c,d,e,f,g,l,m,q,null)},pc:(a,b,c,d)=>{a=O[a];for(var e=[],f=0;f<b;f++)e.push(Na(t[c+
4*f>>2]));T.transformFeedbackVaryings(a,e,d)},Pd:df,Od:(a,b,c)=>{if(2<=S.version)b&&T.uniform1fv(W(a),v,c>>2,b);else{if(288>=b)for(var d=ef[b-1],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);T.uniform1fv(W(a),d)}},Nd:(a,b)=>{T.uniform1i(W(a),b)},Ld:(a,b,c)=>{if(2<=S.version)b&&T.uniform1iv(W(a),t,c>>2,b);else{if(288>=b)for(var d=ff[b-1],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);T.uniform1iv(W(a),d)}},cc:(a,b)=>{T.uniform1ui(W(a),b)},_b:(a,b,c)=>{b&&T.uniform1uiv(W(a),
u,c>>2,b)},Kd:gf,Jd:(a,b,c)=>{if(2<=S.version)b&&T.uniform2fv(W(a),v,c>>2,2*b);else{if(144>=b)for(var d=ef[2*b-1],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);T.uniform2fv(W(a),d)}},Id:(a,b,c)=>{T.uniform2i(W(a),b,c)},Hd:(a,b,c)=>{if(2<=S.version)b&&T.uniform2iv(W(a),t,c>>2,2*b);else{if(144>=b)for(var d=ff[2*b-1],e=0;e<2*b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2];else d=t.subarray(c>>2,c+8*b>>2);T.uniform2iv(W(a),d)}},bc:(a,b,c)=>{T.uniform2ui(W(a),b,
c)},Zb:(a,b,c)=>{b&&T.uniform2uiv(W(a),u,c>>2,2*b)},Gd:(a,b,c,d)=>{T.uniform3f(W(a),b,c,d)},Fd:hf,Ed:(a,b,c,d)=>{T.uniform3i(W(a),b,c,d)},Dd:(a,b,c)=>{if(2<=S.version)b&&T.uniform3iv(W(a),t,c>>2,3*b);else{if(96>=b)for(var d=ff[3*b-1],e=0;e<3*b;e+=3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2];else d=t.subarray(c>>2,c+12*b>>2);T.uniform3iv(W(a),d)}},ac:(a,b,c,d)=>{T.uniform3ui(W(a),b,c,d)},Yb:(a,b,c)=>{b&&T.uniform3uiv(W(a),u,c>>2,3*b)},Cd:(a,b,c,d,e)=>{T.uniform4f(W(a),b,c,d,e)},
Ad:jf,zd:(a,b,c,d,e)=>{T.uniform4i(W(a),b,c,d,e)},yd:(a,b,c)=>{if(2<=S.version)b&&T.uniform4iv(W(a),t,c>>2,4*b);else{if(72>=b)for(var d=ff[4*b-1],e=0;e<4*b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2];else d=t.subarray(c>>2,c+16*b>>2);T.uniform4iv(W(a),d)}},$b:(a,b,c,d,e)=>{T.uniform4ui(W(a),b,c,d,e)},Xb:(a,b,c)=>{b&&T.uniform4uiv(W(a),u,c>>2,4*b)},Kb:(a,b,c)=>{a=O[a];T.uniformBlockBinding(a,b,c)},xd:(a,b,c,d)=>{if(2<=S.version)b&&T.uniformMatrix2fv(W(a),
!!c,v,d>>2,4*b);else{if(72>=b)for(var e=ef[4*b-1],f=0;f<4*b;f+=4)e[f]=v[d+4*f>>2],e[f+1]=v[d+(4*f+4)>>2],e[f+2]=v[d+(4*f+8)>>2],e[f+3]=v[d+(4*f+12)>>2];else e=v.subarray(d>>2,d+16*b>>2);T.uniformMatrix2fv(W(a),!!c,e)}},Ic:(a,b,c,d)=>{b&&T.uniformMatrix2x3fv(W(a),!!c,v,d>>2,6*b)},Gc:(a,b,c,d)=>{b&&T.uniformMatrix2x4fv(W(a),!!c,v,d>>2,8*b)},wd:(a,b,c,d)=>{if(2<=S.version)b&&T.uniformMatrix3fv(W(a),!!c,v,d>>2,9*b);else{if(32>=b)for(var e=ef[9*b-1],f=0;f<9*b;f+=9)e[f]=v[d+4*f>>2],e[f+1]=v[d+(4*f+4)>>
2],e[f+2]=v[d+(4*f+8)>>2],e[f+3]=v[d+(4*f+12)>>2],e[f+4]=v[d+(4*f+16)>>2],e[f+5]=v[d+(4*f+20)>>2],e[f+6]=v[d+(4*f+24)>>2],e[f+7]=v[d+(4*f+28)>>2],e[f+8]=v[d+(4*f+32)>>2];else e=v.subarray(d>>2,d+36*b>>2);T.uniformMatrix3fv(W(a),!!c,e)}},Hc:(a,b,c,d)=>{b&&T.uniformMatrix3x2fv(W(a),!!c,v,d>>2,6*b)},Ec:(a,b,c,d)=>{b&&T.uniformMatrix3x4fv(W(a),!!c,v,d>>2,12*b)},vd:kf,Fc:(a,b,c,d)=>{b&&T.uniformMatrix4x2fv(W(a),!!c,v,d>>2,8*b)},Dc:(a,b,c,d)=>{b&&T.uniformMatrix4x3fv(W(a),!!c,v,d>>2,12*b)},ud:lf,td:a=>
{T.validateProgram(O[a])},sd:mf,rd:(a,b)=>{T.vertexAttrib1f(a,v[b>>2])},pd:nf,od:(a,b)=>{T.vertexAttrib2f(a,v[b>>2],v[b+4>>2])},nd:function(a,b,c,d){T.vertexAttrib3f(a,b,c,d)},md:(a,b)=>{T.vertexAttrib3f(a,v[b>>2],v[b+4>>2],v[b+8>>2])},ld:function(a,b,c,d,e){T.vertexAttrib4f(a,b,c,d,e)},kd:(a,b)=>{T.vertexAttrib4f(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},ob:of,$f:of,gd:of,hd:of,$a:of,jc:function(a,b,c,d,e){T.vertexAttribI4i(a,b,c,d,e)},hc:(a,b)=>{T.vertexAttribI4i(a,t[b>>2],t[b+4>>2],t[b+8>>2],
t[b+12>>2])},ic:function(a,b,c,d,e){T.vertexAttribI4ui(a,b,c,d,e)},gc:(a,b)=>{T.vertexAttribI4ui(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},mc:(a,b,c,d,e)=>{T.vertexAttribIPointer(a,b,c,d,e)},jd:pf,id:qf,Db:(a,b,c,d)=>{T.waitSync(bd[a],b,(c>>>0)+4294967296*d)},F:()=>0,Va:(a,b,c)=>n.copyWithin(a,b,b+c),Ja:(a,b,c)=>rf(a,{Uh:t[c>>2],Qh:t[c+4>>2],Ii:t[c+8>>2],Ei:b,Bh:t[c+12>>2],ai:t[c+16>>2]}),na:(a,b)=>{a=U(a);return a?a.requestPointerLock?wd()?de(a):b?(ud(de,2,[a]),1):-2:-1:-4},Qa:a=>{var b=n.length;
a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ka.buffer.byteLength+65535)/65536;try{ka.grow(e);pa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},T:sf,U:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:tf(a,b),da:(a,b,c,d)=>uf(a,b,c,d,12,"blur"),q:Wd,A:(a,b,c)=>{a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},ea:(a,b,c,
d)=>uf(a,b,c,d,13,"focus"),X:(a,b,c,d)=>{if(!Dd())return-1;a=U(a);if(!a)return-4;vf(a,b,c,d,"webkitfullscreenchange");return vf(a,b,c,d,"fullscreenchange")},u:(a,b,c)=>sf()?-1:wf(a,b,c,26,"gamepadconnected"),t:(a,b,c)=>sf()?-1:wf(a,b,c,27,"gamepaddisconnected"),_:(a,b,c,d)=>xf(a,b,c,d,2,"keydown"),Y:(a,b,c,d)=>xf(a,b,c,d,1,"keypress"),Z:(a,b,c,d)=>xf(a,b,c,d,3,"keyup"),Da:(a,b,c)=>{a=V(a);rc(a,b,c)},ja:(a,b,c,d)=>zf(a,b,c,d,5,"mousedown"),ha:(a,b,c,d)=>zf(a,b,c,d,33,"mouseenter"),ga:(a,b,c,d)=>zf(a,
b,c,d,34,"mouseleave"),ka:(a,b,c,d)=>zf(a,b,c,d,8,"mousemove"),ia:(a,b,c,d)=>zf(a,b,c,d,6,"mouseup"),y:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.bh||document.body.ui||document.body.ti))return-1;a=U(a);if(!a)return-4;Af(a,b,c,d,"mozpointerlockchange");Af(a,b,c,d,"webkitpointerlockchange");Af(a,b,c,d,"mspointerlockchange");return Af(a,b,c,d,"pointerlockchange")},W:(a,b,c,d)=>Bf(a,b,c,d),$:(a,b,c,d)=>Cf(a,b,c,d,25,"touchcancel"),ba:(a,b,c,d)=>Cf(a,b,
c,d,23,"touchend"),aa:(a,b,c,d)=>Cf(a,b,c,d,24,"touchmove"),ca:(a,b,c,d)=>Cf(a,b,c,d,22,"touchstart"),V:(a,b,c)=>Df(a,b,c),fa:(a,b,c,d)=>(a=U(a))?"undefined"!=typeof a.onwheel?Ef(a,b,c,d):-1:-4,Ka:a=>document.title=a?C(n,a):"",E:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},P:(a,b)=>{b>>=2;b={alpha:!!t[b],depth:!!t[b+1],stencil:!!t[b+2],antialias:!!t[b+3],premultipliedAlpha:!!t[b+4],preserveDrawingBuffer:!!t[b+5],powerPreference:Ff[t[b+
6]],failIfMajorPerformanceCaveat:!!t[b+7],Eh:t[b+8],Wi:t[b+9],ci:t[b+10],Hi:t[b+11],Dj:t[b+12],Hj:t[b+13]};a=U(a);return!a||b.Hi?0:jd(a,b)},Ea:a=>ld(a)?0:-5,Ba:a=>{if("undefined"==typeof WebSocket)return-1;if(!a)return-5;var b=a>>2;a=Na(t[b]);a=(b=t[b+1])?new WebSocket(a,(b?C(n,b):"").split(",")):new WebSocket(a);a.binaryType="arraybuffer";b=X.lh.length;X.lh[b]=a;return b},l:(a,b,c)=>{a=X.lh[a];if(!a)return-3;a.send(n.subarray(b,b+c));return 0},M:(a,b)=>{a=X.lh[a];if(!a)return-3;b=b?C(n,b):"";a.send(b);
return 0},ya:(a,b,c)=>{X.Rg||(X.Rg=A(1024));var d=X.lh[a];if(!d)return-3;d.onclose=function(e){u[X.Rg>>2]=a;u[X.Rg+4>>2]=e.wasClean;u[X.Rg+8>>2]=e.code;B(e.reason,n,X.Rg+10,512);V(c)(0,X.Rg,b)};return 0},za:(a,b,c)=>{X.Rg||(X.Rg=A(1024));var d=X.lh[a];if(!d)return-3;d.onerror=function(){u[X.Rg>>2]=a;V(c)(0,X.Rg,b)};return 0},Aa:(a,b,c)=>{X.Rg||(X.Rg=A(1024));var d=X.lh[a];if(!d)return-3;d.onmessage=function(e){u[X.Rg>>2]=a;if("string"==typeof e.data){var f=K(e.data),g=Wa(e.data)+1;u[X.Rg+12>>2]=1}else g=
e.data.byteLength,f=A(g),k.set(new Uint8Array(e.data),f),u[X.Rg+12>>2]=0;u[X.Rg+4>>2]=f;u[X.Rg+8>>2]=g;V(c)(0,X.Rg,b);Rf(f)};return 0},xa:(a,b,c)=>{X.Rg||(X.Rg=A(1024));var d=X.lh[a];if(!d)return-3;d.onopen=function(){u[X.Rg>>2]=a;V(c)(0,X.Rg,b)};return 0},Ta:(a,b)=>{var c=0;If().forEach((d,e)=>{var f=b+c;e=u[a+4*e>>2]=f;for(f=0;f<d.length;++f)k[e++>>0]=d.charCodeAt(f);k[e>>0]=0;c+=d.length+1});return 0},Ua:(a,b)=>{var c=If();u[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);u[b>>2]=d;return 0},
R:tc,v:function(a){try{var b=Hb(a);ob(b);return 0}catch(c){if("undefined"==typeof Tb||"ErrnoError"!==c.name)throw c;return c.$g}},Xa:function(a,b,c,d){try{a:{var e=Hb(a);a=b;for(var f,g=b=0;g<c;g++){var l=u[a>>2],m=u[a+4>>2];a+=8;var q=e,r=f,x=k;if(0>m||0>r)throw new F(28);if(null===q.fd)throw new F(8);if(1===(q.flags&2097155))throw new F(8);if(I(q.node.mode))throw new F(31);if(!q.Pg.read)throw new F(28);var M="undefined"!=typeof r;if(!M)r=q.position;else if(!q.seekable)throw new F(70);var p=q.Pg.read(q,
x,l,m,r);M||(q.position+=p);var D=p;if(0>D){var H=-1;break a}b+=D;if(D<m)break;"undefined"!==typeof f&&(f+=D)}H=b}u[d>>2]=H;return 0}catch(Y){if("undefined"==typeof Tb||"ErrnoError"!==Y.name)throw Y;return Y.$g}},Ma:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Hb(a);Pb(f,b,d);z=[f.position>>>0,(y=f.position,1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];t[e>>2]=z[0];t[e+4>>2]=z[1];f.nh&&
0===b&&0===d&&(f.nh=null);return 0}catch(g){if("undefined"==typeof Tb||"ErrnoError"!==g.name)throw g;return g.$g}},Wa:function(a,b,c,d){try{a:{var e=Hb(a);a=b;for(var f,g=b=0;g<c;g++){var l=u[a>>2],m=u[a+4>>2];a+=8;var q=nb(e,k,l,m,f);if(0>q){var r=-1;break a}b+=q;"undefined"!==typeof f&&(f+=q)}r=b}u[d>>2]=r;return 0}catch(x){if("undefined"==typeof Tb||"ErrnoError"!==x.name)throw x;return x.$g}},Ca:function(){return K(location.hash.replace("#",""))},ra:fe,f:ge,g:he,b:ie,Sa:je,i:ke,h:le,N:me,Ga:ne,
Q:oe,ta:pe,Ag:qe,J:re,ug:se,tg:te,Lc:ue,e:ve,D:Ae,s:Be,K:De,I:Ee,L:Fe,z:He,sa:Oe,w:Pe,m:Se,zg:Xe,Cg:function(a,b){const c=T.getExtension("WEBGL_polygon_mode");c&&c.polygonModeWEBGL(a,b)},ua:$e,G:af,k:bf,x:cf,H:df,qa:gf,Bg:hf,pg:jf,j:kf,yg:lf,va:mf,wa:nf,r:pf,Fa:qf,Dg:function(){return window.fullScreen||window.innerWidth==screen.width&&window.innerHeight==screen.height},vg:function(){return"ontouchstart"in window||0<navigator.maxTouchPoints||0<navigator.msMaxTouchPoints},O:function(a){location.hash=
a?C(n,a):""},Oa:(a,b,c,d)=>Of(a,b,c,d),wg:function(){document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement?document.bh?document.bh():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen():document.documentElement.requestFullscreen?document.documentElement.requestFullscreen():document.documentElement.mozRequestFullScreen?document.documentElement.mozRequestFullScreen():document.documentElement.webkitRequestFullscreen&&
document.documentElement.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}},Tf=function(){function a(c){Tf=c.exports;ka=Tf.Eg;pa();Zd=Tf.Jg;ra.unshift(Tf.Fg);va--;h.monitorRunDependencies?.(va);0==va&&(null!==wa&&(clearInterval(wa),wa=null),xa&&(c=xa,xa=null,c()));return Tf}var b={a:Sf};va++;h.monitorRunDependencies?.(va);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return ha(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ea(b,function(c){a(c.instance)});return{}}(),
A=a=>(A=Tf.Gg)(a),Rf=a=>(Rf=Tf.Hg)(a),Uf=h._main=(a,b)=>(Uf=h._main=Tf.Ig)(a,b),pd=()=>(pd=Tf.Kg)(),qd=a=>(qd=Tf.Lg)(a),Td=a=>(Td=Tf.Mg)(a);h.___start_em_js=111084;h.___stop_em_js=112407;var Vf;xa=function Wf(){Vf||Xf();Vf||(xa=Wf)};function Yf(a=[]){var b=Uf;a.unshift(ca);var c=a.length,d=Td(4*(c+1)),e=d;a.forEach(g=>{u[e>>2]=Ud(g);e+=4});u[e>>2]=0;try{var f=b(c,d);tc(f,!0)}catch(g){qc(g)}}
function Xf(){var a=ba;function b(){if(!Vf&&(Vf=!0,h.calledRun=!0,!la)){h.noFSInit||Qb||(Qb=!0,h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Rb("stdin",h.stdin):Nb("/dev/tty","/dev/stdin"),h.stdout?Rb("stdout",null,h.stdout):Nb("/dev/tty","/dev/stdout"),h.stderr?Rb("stderr",null,h.stderr):Nb("/dev/tty1","/dev/stderr"),mb("/dev/stdin",0),mb("/dev/stdout",1),mb("/dev/stderr",1));wb=!1;Ka(ra);Ka(sa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();Zf&&Yf(a);if(h.postRun)for("function"==
typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ta.unshift(c)}Ka(ta)}}if(!(0<va)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ua();Ka(qa);0<va||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Zf=!0;h.noInitialRun&&(Zf=!1);Xf();
