var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="",fa;"undefined"!=typeof document&&document.currentScript&&(ea=document.currentScript.src);ea=0!==ea.indexOf("blob:")?ea.substr(0,ea.replace(/[?#].*/,"").lastIndexOf("/")+1):"";fa=a=>{document.title=a};var ha=f.print||console.log.bind(console),k=f.printErr||console.warn.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);
f.thisProgram&&(ca=f.thisProgram);f.quit&&(da=f.quit);var ia;f.wasmBinary&&(ia=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&m("no native wasm support detected");var ja,ka=!1,la,ma="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ma)return ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function p(a,b){return a?na(r,a,b):""}
function oa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function t(a,b,c){return oa(a,r,b,c)}
function pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var u,r,qa,ra,w,x,y,A;function sa(){var a=ja.buffer;f.HEAP8=u=new Int8Array(a);f.HEAP16=qa=new Int16Array(a);f.HEAP32=w=new Int32Array(a);f.HEAPU8=r=new Uint8Array(a);f.HEAPU16=ra=new Uint16Array(a);f.HEAPU32=x=new Uint32Array(a);f.HEAPF32=y=new Float32Array(a);f.HEAPF64=A=new Float64Array(a)}var ta,ua=[],va=[],wa=[],xa=[],ya=[];
function za(){var a=f.preRun.shift();ua.unshift(a)}var Aa=0,Ba=null,Da=null;function m(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";k(a);ka=!0;la=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ea(a){return a.startsWith("data:application/octet-stream;base64,")}var Fa;Fa="index.wasm";if(!Ea(Fa)){var Ga=Fa;Fa=f.locateFile?f.locateFile(Ga,ea):ea+Ga}
function Ha(a){try{if(a==Fa&&ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}catch(b){m(b)}}function Ia(a){return ia||"function"!=typeof fetch?Promise.resolve().then(function(){return Ha(a)}):fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return Ha(a)})}
function Ja(a,b,c){return Ia(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){k("failed to asynchronously prepare wasm: "+d);m(d)})}
function Ka(a,b){var c=Fa;ia||"function"!=typeof WebAssembly.instantiateStreaming||Ea(c)||"function"!=typeof fetch?Ja(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(e){k("wasm streaming compile failed: "+e);k("falling back to ArrayBuffer instantiation");return Ja(c,a,b)})})}
var La,Ma,Qa={91844:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,91991:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,92225:a=>{"undefined"===typeof f.SDL2&&(f.SDL2={});var b=f.SDL2;a?b.capture={}:b.audio={};b.Gg||("undefined"!==typeof AudioContext?b.Gg=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.Gg=new webkitAudioContext),b.Gg&&
Na(b.Gg));return void 0===b.Gg?-1:0},92718:()=>f.SDL2.Gg.sampleRate,92786:(a,b,c,d)=>{function e(){}function g(l){void 0!==h.capture.Yg&&(clearTimeout(h.capture.Yg),h.capture.Yg=void 0);h.capture.bh=h.Gg.createMediaStreamSource(l);h.capture.Kg=h.Gg.createScriptProcessor(b,a,1);h.capture.Kg.onaudioprocess=function(n){void 0!==h&&void 0!==h.capture&&(n.outputBuffer.getChannelData(0).fill(0),h.capture.hh=n.inputBuffer,Oa(c,[d]))};h.capture.bh.connect(h.capture.Kg);h.capture.Kg.connect(h.Gg.destination);
h.capture.stream=l}var h=f.SDL2;h.capture.dh=h.Gg.createBuffer(a,b,h.Gg.sampleRate);h.capture.dh.getChannelData(0).fill(0);h.capture.Yg=setTimeout(function(){h.capture.hh=h.capture.dh;Oa(c,[d])},b/h.Gg.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},94438:(a,b,c,d)=>{var e=f.SDL2;e.audio.Kg=
e.Gg.createScriptProcessor(b,0,a);e.audio.Kg.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(e.audio.mh=g.outputBuffer,Oa(c,[d]))};e.audio.Kg.connect(e.Gg.destination)},94848:(a,b)=>{for(var c=f.SDL2,d=c.capture.hh.numberOfChannels,e=0;e<d;++e){var g=c.capture.hh.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var h=0;h<b;++h)Pa(a+4*h,g[h]);else for(h=0;h<b;++h)Pa(a+4*(h*d+e),
g[h])}},95453:(a,b)=>{for(var c=f.SDL2,d=c.audio.mh.numberOfChannels,e=0;e<d;++e){var g=c.audio.mh.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var h=0;h<b;++h)g[h]=y[a+(h*d+e<<2)>>2]}},95933:a=>{var b=f.SDL2;if(a){void 0!==b.capture.Yg&&clearTimeout(b.capture.Yg);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=
void 0}void 0!==b.capture.Kg&&(b.capture.Kg.onaudioprocess=function(){},b.capture.Kg.disconnect(),b.capture.Kg=void 0);void 0!==b.capture.bh&&(b.capture.bh.disconnect(),b.capture.bh=void 0);void 0!==b.capture.dh&&(b.capture.dh=void 0);b.capture=void 0}else void 0!=b.audio.Kg&&(b.audio.Kg.disconnect(),b.audio.Kg=void 0),b.audio=void 0;void 0!==b.Gg&&void 0===b.audio&&void 0===b.capture&&(b.Gg.close(),b.Gg=void 0)},97105:(a,b,c)=>{f.SDL2||(f.SDL2={});var d=f.SDL2;d.wh!==f.canvas&&(d.Og=f.createContext(f.canvas,
!1,!0),d.wh=f.canvas);if(d.w!==a||d.Eh!==b||d.Gh!==d.Og)d.image=d.Og.createImageData(a,b),d.w=a,d.Eh=b,d.Gh=d.Og;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=w[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.yh!==a&&(d.xh=new Int32Array(a.buffer),d.zh=new Uint8Array(a.buffer),d.yh=a),a=d.xh,c=a.length,a.set(w.subarray(b,b+c)),a=d.zh,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,
b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Og.putImageData(d.image,0,0)},98574:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var h=g.getContext("2d");a=h.createImageData(a,b);b=a.data;e>>=2;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var q=w[e];b[l]=q&255;b[l+1]=q>>8&255;b[l+2]=q>>16&255;b[l+3]=q>>24&255;e++;l+=
4}else b=new Int32Array(b.buffer),n=b.length,b.set(w.subarray(e,e+n));h.putImageData(a,0,0);c=0===c&&0===d?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=B(c.length+1);t(c,d,c.length+1);return d},99563:a=>{f.canvas&&(f.canvas.style.cursor=p(a))},99646:()=>{f.canvas&&(f.canvas.style.cursor="none")},99715:()=>window.innerWidth,99745:()=>window.innerHeight};function Ra(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Sa(a){for(;0<a.length;)a.shift()(f)}
function Pa(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":u[a>>0]=b;break;case "i8":u[a>>0]=b;break;case "i16":qa[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":Ma=[b>>>0,(La=b,1<=+Math.abs(La)?0<La?(Math.min(+Math.floor(La/4294967296),4294967295)|0)>>>0:~~+Math.ceil((La-+(~~La>>>0))/4294967296)>>>0:0)];w[a>>2]=Ma[0];w[a+4>>2]=Ma[1];break;case "float":y[a>>2]=b;break;case "double":A[a>>3]=b;break;case "*":x[a>>2]=b;break;default:m("invalid type for setValue: "+c)}}
function Ta(a,b){Ua=a;Va=b;if(Wa)if(Xa||(Xa=!0),0==a)Ya=function(){var d=Math.max(0,Za+b-$a())|0;setTimeout(ab,d)};else if(1==a)Ya=function(){bb(ab)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}Ya=function(){setImmediate(ab)}}}var $a;$a=()=>performance.now();
function cb(a,b,c,d,e){!Wa||m("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Wa=a;db=d;var g=eb;Xa=!1;ab=function(){if(!ka)if(0<fb.length){var h=Date.now(),l=fb.shift();l.Sh(l.Nh);if(gb){var n=gb,q=0==n%1?n-1:Math.floor(n);gb=l.Ph?q:(8*n+(q+.5))/9}ha('main loop blocker "'+l.name+'" took '+(Date.now()-h)+" ms");f.setStatus&&(h=f.statusMessage||"Please wait...",
l=gb,n=hb.Rh,l?l<n?f.setStatus(h+" ("+(n-l)+"/"+n+")"):f.setStatus(h):f.setStatus(""));g<eb||setTimeout(ab,0)}else g<eb||(ib=ib+1|0,1==Ua&&1<Va&&0!=ib%Va?Ya():(0==Ua&&(Za=$a()),ka||f.preMainLoop&&!1===f.preMainLoop()||(jb(a),f.postMainLoop&&f.postMainLoop()),g<eb||("object"==typeof SDL&&SDL.audio&&SDL.audio.Jh&&SDL.audio.Jh(),Ya())))};e||(b&&0<b?Ta(0,1E3/b):Ta(1,1),Ya());if(c)throw"unwind";}function kb(a){a instanceof Ra||"unwind"==a||da(1,a)}
function lb(a){la=la=a;if(!noExitRuntime){if(f.onExit)f.onExit(a);ka=!0}da(a,new Ra(a))}function jb(a){if(!ka)try{if(a(),!noExitRuntime)try{lb(la)}catch(b){kb(b)}}catch(b){kb(b)}}function mb(a){setTimeout(function(){jb(a)},1E4)}function nb(a){ob||(ob={});ob[a]||(ob[a]=1,k(a))}var ob,Xa=!1,Ya=null,eb=0,Wa=null,db=0,Ua=0,Va=0,ib=0,fb=[],hb={},Za,ab,gb,pb=!1,qb=!1,rb=[];
function sb(){function a(){qb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!tb){tb=!0;try{ub=!0}catch(c){ub=!1,k("warning: no blob constructor, cannot create blobs with mimetypes")}vb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:ub?null:k("warning: no BlobBuilder");wb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;f.qh||"undefined"!=typeof wb||(k("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.qh=!0);f.preloadPlugins.push({canHandle:function(c){return!f.qh&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=null;if(ub)try{h=new Blob([c],{type:xb(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:xb(d)}))}catch(q){nb("Blob constructor present but fails: "+
q+"; falling back to blob builder")}h||(h=new vb,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var l=wb.createObjectURL(h),n=new Image;n.onload=()=>{n.complete||m("Image "+d+" could not be decoded");var q=document.createElement("canvas");q.width=n.width;q.height=n.height;q.getContext("2d").drawImage(n,0,0);wb.revokeObjectURL(l);e&&e(c)};n.onerror=()=>{ha("Image "+l+" could not be decoded");g&&g()};n.src=l}});f.preloadPlugins.push({canHandle:function(c){return!f.Xh&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,g){function h(){n||(n=!0,e&&e(c))}function l(){n||(n=!0,new Audio,g&&g())}var n=!1;if(ub){try{var q=new Blob([c],{type:xb(d)})}catch(z){return l()}q=wb.createObjectURL(q);var v=new Audio;v.addEventListener("canplaythrough",()=>h(v),!1);v.onerror=function(){if(!n){k("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var z="",W=0,Q=0,Ca=0;Ca<c.length;Ca++)for(W=W<<8|c[Ca],Q+=8;6<=Q;){var Bb=W>>Q-6&63;Q-=6;z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[Bb]}2==
Q?(z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(W&3)<<4],z+="=="):4==Q&&(z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(W&15)<<2],z+="=");v.src="data:audio/x-"+d.substr(-3)+";base64,"+z;h(v)}};v.src=q;mb(function(){h(v)})}else return l()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!qb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function yb(a,b,c,d){if(b&&f.Og&&a==f.canvas)return f.Og;var e;if(b){var g={antialias:!1,alpha:!1,ah:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!=typeof zb&&(e=Ab(a,g)))var l=C[e].Pg}else l=a.getContext("2d");if(!l)return null;c&&(b||"undefined"==typeof D||m("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Og=l,b&&Cb(e),f.Lh=b,rb.forEach(function(n){n()}),sb());return l}var Db=!1,Eb=void 0,Fb=void 0;
function Gb(a,b){function c(){pb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Hb,Eb&&d.requestPointerLock(),pb=!0,Fb?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]|8388608),Ib(f.canvas),Jb()):Ib(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Fb?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]&
-8388609),Ib(f.canvas),Jb()):Ib(d));if(f.onFullScreen)f.onFullScreen(pb);if(f.onFullscreen)f.onFullscreen(pb)}Eb=a;Fb=b;"undefined"==typeof Eb&&(Eb=!0);"undefined"==typeof Fb&&(Fb=!1);var d=f.canvas;Db||(Db=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Hb(){if(!pb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Kb=0;function bb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Kb)Kb=b+1E3/60;else for(;b+2>=Kb;)Kb+=1E3/60;setTimeout(a,Math.max(Kb-b,0))}}
function xb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Lb=[];function Jb(){var a=f.canvas;Lb.forEach(function(b){b(a.width,a.height)})}
function Ib(a,b,c){b&&c?(a.Mh=b,a.Fh=c):(b=a.Mh,c=a.Fh);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}Fb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var tb,ub,vb,wb,E=12288,Mb=!1,Nb=0,Ob=0,Pb=0,F={alpha:!1,depth:!1,stencil:!1,antialias:!1},Qb={},Rb;function Sb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,h){b.drawElementsInstancedANGLE(c,d,e,g,h)})}
function Tb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Ub(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var Vb=1,G=[],H=[],Wb=[],Xb=[],Yb=[],I=[],J=[],C=[],K=[],L=[],Zb=[],$b=[],ac={},bc={},cc=4;function M(a){dc||(dc=a)}function ec(a){for(var b=Vb++,c=a.length;c<b;c++)a[c]=null;return b}function fc(a,b,c){for(var d="",e=0;e<a;++e){var g=c?w[c+4*e>>2]:-1;d+=p(w[b+4*e>>2],0>g?void 0:g)}return d}
function Ab(a,b){a.Zg||(a.Zg=a.getContext,a.getContext=function(d,e){e=a.Zg(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.ah?a.getContext("webgl2",b):a.getContext("webgl",b);return c?gc(c,b):0}function gc(a,b){var c=ec(C),d={Th:c,attributes:b,version:b.ah,Pg:a};a.canvas&&(a.canvas.Ug=d);C[c]=d;("undefined"==typeof b.oh||b.oh)&&hc(d);return c}function Cb(a){N=C[a];f.Og=D=N&&N.Pg;return!(a&&!D)}
function hc(a){a||(a=N);if(!a.Hh){a.Hh=!0;var b=a.Pg;Sb(b);Tb(b);Ub(b);b.Qh=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Vh=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Jg=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Jg)b.Jg=b.getExtension("EXT_disjoint_timer_query");b.Wh=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var zb={},dc,N;function ic(a){var b=pa(a)+1,c=B(b);c&&oa(a,u,c,b);return c}var jc=[];function kc(a,b){jc.length=0;var c;for(b>>=2;c=r[a++];)b+=105!=c&b,jc.push(105==c?w[b]:A[b++>>1]),++b;return jc}function lc(a){var b=mc();a=a();nc(b);return a}var oc=0;function pc(){for(var a=O.length-1;0<=a;--a)qc(a);O=[];P=[]}var P=[];
function rc(a,b,c){function d(h,l){if(h.length!=l.length)return!1;for(var n in h)if(h[n]!=l[n])return!1;return!0}for(var e in P){var g=P[e];if(g.jh==a&&d(g.kh,c))return}P.push({jh:a,sh:b,kh:c});P.sort(function(h,l){return h.sh<l.sh})}function sc(a){for(var b=0;b<P.length;++b)P[b].jh==a&&(P.splice(b,1),--b)}function tc(){if(oc&&uc.Rg)for(var a=0;a<P.length;++a){var b=P[a];P.splice(a,1);--a;b.jh.apply(null,b.kh)}}var O=[];
function qc(a){var b=O[a];b.target.removeEventListener(b.Ig,b.Bh,b.Lg);O.splice(a,1)}function R(a){function b(d){++oc;uc=a;tc();a.Ng(d);tc();--oc}if(a.Mg)a.Bh=b,a.target.addEventListener(a.Ig,b,a.Lg),O.push(a),vc||(xa.push(pc),vc=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].Ig==a.Ig&&qc(c--)}function wc(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function xc(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var yc={},vc,uc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc={},Mc=[0,document,window];function S(a){a=2<a?p(a):a;return Mc[a]||document.querySelector(a)}function Nc(a){return lc(function(){var b=Oc(8),c=b+4,d=Oc(a.id.length+1);t(a.id,d,a.id.length+1);if(d=S(d))w[b>>2]=d.width,w[c>>2]=d.height;return[w[b>>2],w[c>>2]]})}function Pc(a,b,c){a=S(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function Qc(a,b,c){a.Oh?lc(function(){var d=Oc(a.id.length+1);t(a.id,d,a.id.length+1);Pc(d,b,c)}):(a.width=b,a.height=c)}var Rc=[];function T(a){var b=Rc[a];b||(a>=Rc.length&&(Rc.length=a+1),Rc[a]=b=ta.get(a));return b}
function Sc(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Qc(a,d,e),a.style.width=g,a.style.height=h,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=q,a.style.paddingRight=v,a.style.paddingTop=z,a.style.paddingBottom=W,a.style.marginLeft=Q,a.style.marginRight=Ca,a.style.marginTop=
Bb,a.style.marginBottom=Dd,document.body.style.margin=Ed,document.documentElement.style.overflow=Fd,document.body.scroll=Gd,a.style.Qg=Hd,a.Ug&&a.Ug.Pg.viewport(0,0,d,e),Lc.$g&&T(Lc.$g)(37,0,Lc.lh))}var c=Nc(a),d=c[0],e=c[1],g=a.style.width,h=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,q=a.style.paddingLeft,v=a.style.paddingRight,z=a.style.paddingTop,W=a.style.paddingBottom,Q=a.style.marginLeft,Ca=a.style.marginRight,Bb=a.style.marginTop,Dd=a.style.marginBottom,
Ed=document.body.style.margin,Fd=document.documentElement.style.overflow,Gd=document.body.scroll,Hd=a.style.Qg;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Tc(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Uc(a){return 0>Mc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Vc(a,b){if(0!=b.ih||0!=b.gh){Sc(a);var c=b.Kh?innerWidth:screen.width,d=b.Kh?innerHeight:screen.height,e=Uc(a),g=e.width;e=e.height;var h=Nc(a),l=h[0];h=h[1];3==b.ih?(Tc(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.ih&&(c*h<l*d?(g=h*c/l,Tc(a,(d-g)/2,0),d=g):(g=l*d/h,Tc(a,0,(c-g)/2),c=g));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Dh&&(a.style.Qg="optimizeSpeed",
a.style.Qg="-moz-crisp-edges",a.style.Qg="-o-crisp-edges",a.style.Qg="-webkit-optimize-contrast",a.style.Qg="optimize-contrast",a.style.Qg="crisp-edges",a.style.Qg="pixelated");g=2==b.gh?devicePixelRatio:1;0!=b.gh&&(c=c*g|0,d=d*g|0,Qc(a,c,d),a.Ug&&a.Ug.Pg.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return xc()?-3:-1;Lc=b;b.$g&&T(b.$g)(37,0,b.lh);return 0}
function Wc(a){if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0}
function Xc(a,b){A[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)A[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)A[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)w[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];w[a+1296>>2]=b.connected;w[a+1300>>2]=b.index;w[a+8>>2]=b.axes.length;w[a+12>>2]=b.buttons.length;t(b.id,a+1304,64);t(b.mapping,a+1368,64)}var Yc=[];
function U(a,b,c,d){for(var e=0;e<a;e++){var g=D[c](),h=g&&ec(d);g?(g.name=h,d[h]=g):M(1282);w[b+4*e>>2]=h}}function Zc(a,b,c,d,e,g,h,l){b=H[b];if(a=D[a](b,c))d=l&&t(a.name,l,d),e&&(w[e>>2]=d),g&&(w[g>>2]=a.size),h&&(w[h>>2]=a.type)}function $c(a,b){x[a>>2]=b;x[a+4>>2]=(b-x[a>>2])/4294967296}
function ad(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&M(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=D.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>N.version){M(1282);return}d=2*(D.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>N.version){M(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=D.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":M(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:M(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+4*a>>2]=e[a];break;case 2:y[b+4*a>>2]=e[a];break;case 4:u[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){M(1280);
k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:M(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:$c(b,d);break;case 0:w[b>>2]=d;break;case 2:y[b>>2]=d;break;case 4:u[b>>0]=d?1:0}}else M(1281)}
function bd(a,b,c,d){if(c){b=D.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:M(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{M(1280);return}break;default:M(1280);return}switch(d){case 1:$c(c,a);break;case 0:w[c>>2]=a;break;case 2:y[c>>2]=a;break;case 4:u[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else M(1281)}
function cd(a){var b=pa(a)+1,c=B(b);t(a,c,b);return c}function dd(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function ed(a){var b=a.Sg,c=a.fh,d;if(!b)for(a.Sg=b={},a.th={},d=0;d<D.getProgramParameter(a,35718);++d){var e=D.getActiveUniform(a,d);var g=e.name;e=e.size;var h=dd(g);h=0<h?g.slice(0,h):g;var l=a.eh;a.eh+=e;c[h]=[e,l];for(g=0;g<e;++g)b[l]=g,a.th[l++]=h}}
function V(a){var b=D.nh;if(b){var c=b.Sg[a];"number"==typeof c&&(b.Sg[a]=c=D.getUniformLocation(b,b.th[a]+(0<c?"["+c+"]":"")));return c}M(1282)}function fd(a,b,c,d){if(c)if(a=H[a],ed(a),a=D.getUniform(a,V(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:y[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b]}else M(1281)}
function gd(a,b,c,d){if(c)if(a=D.getVertexAttrib(a,b),34975==b)w[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:y[c>>2]=a;break;case 5:w[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;case 5:w[c+4*b>>2]=Math.fround(a[b])}else M(1281)}function hd(a){a-=5120;return 0==a?u:1==a?r:2==a?qa:4==a?w:6==a?y:5==a||28922==a||28520==a||30779==a||30782==a?x:ra}
function jd(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function kd(a,b,c,d,e){a=hd(a);var g=jd(a),h=cc;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<g)+h-1&-h)>>g)}var X=[],ld=[];function md(a,b){if(!xc())return-1;a=S(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?oc&&uc.Rg?Vc(a,b):b.Ah?(rc(Vc,1,[a,b]),1):-2:-3:-4}
function nd(a,b){var c={target:S(2),Ig:"beforeunload",Mg:b,Ng:function(d=event){var e=T(b)(28,0,a);e&&(e=p(e));if(e)return d.preventDefault(),d.returnValue=e},Lg:!0};R(c)}function od(a,b,c,d,e,g){Ac||(Ac=B(256));a={target:S(a),Ig:g,Mg:d,Ng:function(h=event){var l=h.target.id?h.target.id:"",n=Ac;t(wc(h.target),n+0,128);t(l,n+128,128);T(d)(e,n,b)&&h.preventDefault()},Lg:c};R(a)}
function pd(a,b,c,d,e){Cc||(Cc=B(280));R({target:a,Ig:e,Mg:d,Ng:function(g=event){var h=Cc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;w[h>>2]=n;w[h+4>>2]=xc();var q=n?l:Bc,v=q&&q.id?q.id:"";t(wc(q),h+8,128);t(v,h+136,128);w[h+264>>2]=q?q.clientWidth:0;w[h+268>>2]=q?q.clientHeight:0;w[h+272>>2]=screen.width;w[h+276>>2]=screen.height;n&&(Bc=l);T(d)(19,h,b)&&g.preventDefault()},Lg:c})}
function qd(a,b,c,d,e){Dc||(Dc=B(1432));b={target:S(2),Rg:!0,Ig:e,Mg:c,Ng:function(g=event){var h=Dc;Xc(h,g.gamepad);T(c)(d,h,a)&&g.preventDefault()},Lg:b};R(b)}
function rd(a,b,c,d,e,g){Ec||(Ec=B(176));a={target:S(a),Rg:!0,Ig:g,Mg:d,Ng:function(h){var l=Ec;A[l>>3]=h.timeStamp;var n=l>>2;w[n+2]=h.location;w[n+3]=h.ctrlKey;w[n+4]=h.shiftKey;w[n+5]=h.altKey;w[n+6]=h.metaKey;w[n+7]=h.repeat;w[n+8]=h.charCode;w[n+9]=h.keyCode;w[n+10]=h.which;t(h.key||"",l+44,32);t(h.code||"",l+76,32);t(h.char||"",l+108,32);t(h.locale||"",l+140,32);T(d)(e,l,b)&&h.preventDefault()},Lg:c};R(a)}
function sd(a,b,c){A[a>>3]=b.timeStamp;a>>=2;w[a+2]=b.screenX;w[a+3]=b.screenY;w[a+4]=b.clientX;w[a+5]=b.clientY;w[a+6]=b.ctrlKey;w[a+7]=b.shiftKey;w[a+8]=b.altKey;w[a+9]=b.metaKey;qa[2*a+20]=b.button;qa[2*a+21]=b.buttons;w[a+11]=b.movementX;w[a+12]=b.movementY;c=Uc(c);w[a+13]=b.clientX-c.left;w[a+14]=b.clientY-c.top}
function td(a,b,c,d,e,g){Fc||(Fc=B(72));a=S(a);R({target:a,Rg:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,Ig:g,Mg:d,Ng:function(h=event){sd(Fc,h,a);T(d)(e,Fc,b)&&h.preventDefault()},Lg:c})}function ud(a,b,c,d,e){Gc||(Gc=B(260));R({target:a,Ig:e,Mg:d,Ng:function(g=event){var h=Gc,l=document.pointerLockElement||document.Zg||document.vh||document.uh;w[h>>2]=!!l;var n=l&&l.id?l.id:"";t(wc(l),h+4,128);t(n,h+132,128);T(d)(20,h,b)&&g.preventDefault()},Lg:c})}
function vd(a,b,c,d){Hc||(Hc=B(36));a=S(a);R({target:a,Ig:"resize",Mg:d,Ng:function(e=event){if(e.target==a){var g=document.body;if(g){var h=Hc;w[h>>2]=e.detail;w[h+4>>2]=g.clientWidth;w[h+8>>2]=g.clientHeight;w[h+12>>2]=innerWidth;w[h+16>>2]=innerHeight;w[h+20>>2]=outerWidth;w[h+24>>2]=outerHeight;w[h+28>>2]=pageXOffset;w[h+32>>2]=pageYOffset;T(d)(10,h,b)&&e.preventDefault()}}},Lg:c})}
function wd(a,b,c,d,e,g){Ic||(Ic=B(1696));a=S(a);R({target:a,Rg:"touchstart"==g||"touchend"==g,Ig:g,Mg:d,Ng:function(h){for(var l,n={},q=h.touches,v=0;v<q.length;++v)l=q[v],l.ph=l.rh=0,n[l.identifier]=l;for(v=0;v<h.changedTouches.length;++v)l=h.changedTouches[v],l.ph=1,n[l.identifier]=l;for(v=0;v<h.targetTouches.length;++v)n[h.targetTouches[v].identifier].rh=1;q=Ic;A[q>>3]=h.timeStamp;var z=q>>2;w[z+3]=h.ctrlKey;w[z+4]=h.shiftKey;w[z+5]=h.altKey;w[z+6]=h.metaKey;z+=7;var W=Uc(a),Q=0;for(v in n)if(l=
n[v],w[z]=l.identifier,w[z+1]=l.screenX,w[z+2]=l.screenY,w[z+3]=l.clientX,w[z+4]=l.clientY,w[z+5]=l.pageX,w[z+6]=l.pageY,w[z+7]=l.ph,w[z+8]=l.rh,w[z+9]=l.clientX-W.left,w[z+10]=l.clientY-W.top,z+=13,31<++Q)break;w[q+8>>2]=Q;T(d)(e,q,b)&&h.preventDefault()},Lg:c})}
function xd(a,b,c){var d=Mc[1];Jc||(Jc=B(8));R({target:d,Ig:"visibilitychange",Mg:c,Ng:function(e=event){var g=Jc,h=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);w[g>>2]=document.hidden;w[g+4>>2]=h;T(c)(21,g,a)&&e.preventDefault()},Lg:b})}
function yd(a,b,c,d){Kc||(Kc=B(104));R({target:a,Rg:!0,Ig:"wheel",Mg:d,Ng:function(e=event){var g=Kc;sd(g,e,a);A[g+72>>3]=e.deltaX;A[g+80>>3]=e.deltaY;A[g+88>>3]=e.deltaZ;w[g+96>>2]=e.deltaMode;T(d)(9,g,b)&&e.preventDefault()},Lg:c})}var zd=["default","low-power","high-performance"],Ad=[null],Y=null,Bd={};
function Cd(){if(!Id){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Bd)void 0===Bd[b]?delete a[b]:a[b]=Bd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Id=c}return Id}var Id,Jd=[null,[],[]];function Kd(a,b,c){a.addEventListener(b,c,{once:!0})}
function Na(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&Kd(d,c,()=>{"suspended"===a.state&&a.resume()})})})}function Oa(a,b){if("vi".includes("j")){var c=f.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else T(a).apply(null,b)}f.requestFullscreen=function(a,b){Gb(a,b)};f.requestAnimationFrame=function(a){bb(a)};f.setCanvasSize=function(a,b,c){Ib(f.canvas,a,b);c||Jb()};
f.pauseMainLoop=function(){Ya=null;eb++};f.resumeMainLoop=function(){eb++;var a=Ua,b=Va,c=Wa;Wa=null;cb(c,0,!1,db,!0);Ta(a,b);Ya()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return yb(a,b,c,d)};for(var D,Z=0;32>Z;++Z)Yc.push(Array(Z));var Ld=new Float32Array(288);for(Z=0;288>Z;++Z)X[Z]=Ld.subarray(0,Z+1);var Md=new Int32Array(288);
for(Z=0;288>Z;++Z)ld[Z]=Md.subarray(0,Z+1);
var Od={a:function(a,b,c,d){m("Assertion failed: "+p(a)+", at: "+[b?p(b):"unknown filename",c,d?p(d):"unknown function"])},ca:function(){return 0},Wa:function(){return 0},Xa:function(){},Ya:function(){return!0},c:function(){m("")},Vd:function(a){if(12448==a)return E=12288,1;E=12300;return 0},ig:function(a,b,c,d,e){if(62E3!=a)E=12296,c=0;else{if(b)for(;;){a=w[b>>2];if(12321==a)F.alpha=0<w[b+4>>2];else if(12325==a)F.depth=0<w[b+4>>2];else if(12326==a)F.stencil=0<w[b+4>>2];else if(12337==a)a=w[b+4>>
2],F.antialias=0<a;else if(12338==a)a=w[b+4>>2],F.antialias=1==a;else if(12544==a)F.Uh=12547!=w[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(w[e>>2]=1),c&&0<d&&(w[c>>2]=62002),E=12288,c=1):(E=12300,c=0)}return c},Of:function(a,b,c,d){if(62E3!=a)return E=12296,0;for(a=1;;){b=w[d>>2];if(12440==b)a=w[d+4>>2];else if(12344==b)break;else return E=12292,0;d+=8}if(2>a||3<a)return E=12293,0;F.ah=a-1;F.Ih=0;Rb=Ab(f.canvas,F);if(0!=Rb)return E=12288,Cb(Rb),f.Lh=!0,rb.forEach(function(e){e()}),Cb(null),
62004;E=12297;return 0},sf:function(a,b){if(62E3!=a)return E=12296,0;if(62002!=b)return E=12293,0;E=12288;return 62006},Df:function(a,b){if(62E3!=a)return E=12296,0;if(62004!=b)return E=12294,0;a=Rb;N===C[a]&&(N=null);if("object"==typeof yc)for(var c=C[a].Pg.canvas,d=0;d<O.length;++d)O[d].target!=c||qc(d--);C[a]&&C[a].Pg.canvas&&(C[a].Pg.canvas.Ug=void 0);C[a]=null;E=12288;Nb==b&&(Nb=0);return 1},gf:function(a,b){if(62E3!=a)return E=12296,0;if(62006!=b)return E=12301,1;Ob==b&&(Ob=0);Pb==b&&(Pb=0);
E=12288;return 1},Zf:function(a,b,c,d){if(62E3!=a)return E=12296,0;if(62002!=b)return E=12293,0;if(!d)return E=12300,0;E=12288;switch(c){case 12320:return w[d>>2]=F.alpha?32:24,1;case 12321:return w[d>>2]=F.alpha?8:0,1;case 12322:return w[d>>2]=8,1;case 12323:return w[d>>2]=8,1;case 12324:return w[d>>2]=8,1;case 12325:return w[d>>2]=F.depth?24:0,1;case 12326:return w[d>>2]=F.stencil?8:0,1;case 12327:return w[d>>2]=12344,1;case 12328:return w[d>>2]=62002,1;case 12329:return w[d>>2]=0,1;case 12330:return w[d>>
2]=4096,1;case 12331:return w[d>>2]=16777216,1;case 12332:return w[d>>2]=4096,1;case 12333:return w[d>>2]=0,1;case 12334:return w[d>>2]=0,1;case 12335:return w[d>>2]=12344,1;case 12337:return w[d>>2]=F.antialias?4:0,1;case 12338:return w[d>>2]=F.antialias?1:0,1;case 12339:return w[d>>2]=4,1;case 12340:return w[d>>2]=12344,1;case 12341:case 12342:case 12343:return w[d>>2]=-1,1;case 12345:case 12346:return w[d>>2]=0,1;case 12347:return w[d>>2]=0,1;case 12348:return w[d>>2]=1;case 12349:case 12350:return w[d>>
2]=0,1;case 12351:return w[d>>2]=12430,1;case 12352:return w[d>>2]=4,1;case 12354:return w[d>>2]=0,1;default:return E=12292,0}},J:function(){E=12288;return 62E3},zd:function(){return E},ug:function(a,b,c){if(62E3!=a)return E=12296,0;b&&(w[b>>2]=1);c&&(w[c>>2]=4);Mb=!0;E=12288;return 1},Xe:function(a,b,c,d){if(62E3!=a)return E=12296,0;if(0!=d&&62004!=d)return E=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return E=12301,0;Cb(d?Rb:null);Nb=d;Pb=b;Ob=c;E=12288;return 1},Kd:function(a,b){if(62E3!=a)return E=
12296,0;E=12288;if(Qb[b])return Qb[b];switch(b){case 12371:a=ic("Emscripten");break;case 12372:a=ic("1.4 Emscripten EGL");break;case 12373:a=ic("");break;case 12429:a=ic("OpenGL_ES");break;default:return E=12300,0}return Qb[b]=a},Me:function(){if(Mb)if(f.Og)if(f.Og.isContextLost())E=12302;else return E=12288,1;else E=12290;else E=12289;return 0},Ae:function(a,b){if(62E3!=a)return E=12296,0;0==b?Ta(0,0):Ta(1,b);E=12288;return 1},qg:function(a){if(62E3!=a)return E=12296,0;Pb=Ob=Nb=0;Mb=!1;E=12288;return 1},
ee:function(){E=12288;return 1},pe:function(){E=12288;return 1},Be:function(a,b,c){b=kc(b,c);return Qa[a].apply(null,b)},j:function(a,b,c){b=kc(b,c);return Qa[a].apply(null,b)},D:function(){return Date.now()},Ka:function(){if(!xc())return-1;sc(Vc);var a=Mc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},f:function(){sc(Wc);if(document.exitPointerLock)document.exitPointerLock();
else return-1;return 0},s:function(){return devicePixelRatio},q:function(a,b,c){a=S(a);if(!a)return-4;a=Uc(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},Na:function(a,b){if(0>a||a>=zc.length)return-5;if(!zc[a])return-7;Xc(b,zc[a]);return 0},C:$a,Oa:function(){return zc.length},od:function(a,b){w[a>>2]=screen.width;w[b>>2]=screen.height},Wf:function(a){D.activeTexture(a)},Vf:function(a,b){D.attachShader(H[a],I[b])},Jc:function(a,b){D.beginQuery(a,K[b])},mg:function(a,b){D.Jg.beginQueryEXT(a,K[b])},
pc:function(a){D.beginTransformFeedback(a)},Uf:function(a,b,c){D.bindAttribLocation(H[a],b,p(c))},Tf:function(a,b){35051==a?D.Tg=b:35052==a&&(D.Hg=b);D.bindBuffer(a,G[b])},mc:function(a,b,c){D.bindBufferBase(a,b,G[c])},nc:function(a,b,c,d,e){D.bindBufferRange(a,b,G[c],d,e)},Sf:function(a,b){D.bindFramebuffer(a,Wb[b])},Rf:function(a,b){D.bindRenderbuffer(a,Xb[b])},ub:function(a,b){D.bindSampler(a,L[b])},Qf:function(a,b){D.bindTexture(a,Yb[b])},mb:function(a,b){D.bindTransformFeedback(a,Zb[b])},uc:function(a){D.bindVertexArray(J[a])},
dg:function(a){D.bindVertexArray(J[a])},Pf:function(a,b,c,d){D.blendColor(a,b,c,d)},Nf:function(a){D.blendEquation(a)},Mf:function(a,b){D.blendEquationSeparate(a,b)},Lf:function(a,b){D.blendFunc(a,b)},Kf:function(a,b,c,d){D.blendFuncSeparate(a,b,c,d)},xc:function(a,b,c,d,e,g,h,l,n,q){D.blitFramebuffer(a,b,c,d,e,g,h,l,n,q)},Jf:function(a,b,c,d){2<=N.version?c&&b?D.bufferData(a,r,d,c,b):D.bufferData(a,b,d):D.bufferData(a,c?r.subarray(c,c+b):b,d)},If:function(a,b,c,d){2<=N.version?c&&D.bufferSubData(a,
b,r,d,c):D.bufferSubData(a,b,r.subarray(d,d+c))},Hf:function(a){return D.checkFramebufferStatus(a)},Gf:function(a){D.clear(a)},Rb:function(a,b,c,d){D.clearBufferfi(a,b,c,d)},Sb:function(a,b,c){D.clearBufferfv(a,b,y,c>>2)},Ub:function(a,b,c){D.clearBufferiv(a,b,w,c>>2)},Tb:function(a,b,c){D.clearBufferuiv(a,b,x,c>>2)},Ff:function(a,b,c,d){D.clearColor(a,b,c,d)},Ef:function(a){D.clearDepth(a)},Cf:function(a){D.clearStencil(a)},Db:function(a,b,c,d){return D.clientWaitSync($b[a],b,(c>>>0)+4294967296*
d)},Bf:function(a,b,c,d){D.colorMask(!!a,!!b,!!c,!!d)},Af:function(a){D.compileShader(I[a])},zf:function(a,b,c,d,e,g,h,l){2<=N.version?D.Hg||!h?D.compressedTexImage2D(a,b,c,d,e,g,h,l):D.compressedTexImage2D(a,b,c,d,e,g,r,l,h):D.compressedTexImage2D(a,b,c,d,e,g,l?r.subarray(l,l+h):null)},Oc:function(a,b,c,d,e,g,h,l,n){D.Hg?D.compressedTexImage3D(a,b,c,d,e,g,h,l,n):D.compressedTexImage3D(a,b,c,d,e,g,h,r,n,l)},yf:function(a,b,c,d,e,g,h,l,n){2<=N.version?D.Hg||!l?D.compressedTexSubImage2D(a,b,c,d,e,g,
h,l,n):D.compressedTexSubImage2D(a,b,c,d,e,g,h,r,n,l):D.compressedTexSubImage2D(a,b,c,d,e,g,h,n?r.subarray(n,n+l):null)},Nc:function(a,b,c,d,e,g,h,l,n,q,v){D.Hg?D.compressedTexSubImage3D(a,b,c,d,e,g,h,l,n,q,v):D.compressedTexSubImage3D(a,b,c,d,e,g,h,l,n,r,v,q)},Pb:function(a,b,c,d,e){D.copyBufferSubData(a,b,c,d,e)},xf:function(a,b,c,d,e,g,h,l){D.copyTexImage2D(a,b,c,d,e,g,h,l)},wf:function(a,b,c,d,e,g,h,l){D.copyTexSubImage2D(a,b,c,d,e,g,h,l)},Pc:function(a,b,c,d,e,g,h,l,n){D.copyTexSubImage3D(a,
b,c,d,e,g,h,l,n)},vf:function(){var a=ec(H),b=D.createProgram();b.name=a;b.Xg=b.Vg=b.Wg=0;b.eh=1;H[a]=b;return a},uf:function(a){var b=ec(I);I[b]=D.createShader(a);return b},tf:function(a){D.cullFace(a)},rf:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=G[d];e&&(D.deleteBuffer(e),e.name=0,G[d]=null,d==D.Tg&&(D.Tg=0),d==D.Hg&&(D.Hg=0))}},qf:function(a,b){for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=Wb[d];e&&(D.deleteFramebuffer(e),e.name=0,Wb[d]=null)}},pf:function(a){if(a){var b=H[a];b?(D.deleteProgram(b),
b.name=0,H[a]=null):M(1281)}},Lc:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=K[d];e&&(D.deleteQuery(e),K[d]=null)}},og:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=K[d];e&&(D.Jg.deleteQueryEXT(e),K[d]=null)}},of:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Xb[d];e&&(D.deleteRenderbuffer(e),e.name=0,Xb[d]=null)}},wb:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=L[d];e&&(D.deleteSampler(e),e.name=0,L[d]=null)}},nf:function(a){if(a){var b=I[a];b?(D.deleteShader(b),
I[a]=null):M(1281)}},Eb:function(a){if(a){var b=$b[a];b?(D.deleteSync(b),b.name=0,$b[a]=null):M(1281)}},mf:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Yb[d];e&&(D.deleteTexture(e),e.name=0,Yb[d]=null)}},lb:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Zb[d];e&&(D.deleteTransformFeedback(e),e.name=0,Zb[d]=null)}},tc:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];D.deleteVertexArray(J[d]);J[d]=null}},cg:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];D.deleteVertexArray(J[d]);
J[d]=null}},lf:function(a){D.depthFunc(a)},kf:function(a){D.depthMask(!!a)},jf:function(a,b){D.depthRange(a,b)},hf:function(a,b){D.detachShader(H[a],I[b])},ff:function(a){D.disable(a)},ef:function(a){D.disableVertexAttribArray(a)},df:function(a,b,c){D.drawArrays(a,b,c)},Ib:function(a,b,c,d){D.drawArraysInstanced(a,b,c,d)},_f:function(a,b,c,d){D.drawArraysInstanced(a,b,c,d)},Yc:function(a,b,c,d){D.drawArraysInstanced(a,b,c,d)},Zc:function(a,b,c,d){D.drawArraysInstanced(a,b,c,d)},Za:function(a,b,c,
d){D.drawArraysInstanced(a,b,c,d)},Fc:function(a,b){for(var c=Yc[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];D.drawBuffers(c)},Uc:function(a,b){for(var c=Yc[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];D.drawBuffers(c)},$f:function(a,b){for(var c=Yc[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];D.drawBuffers(c)},cf:function(a,b,c,d){D.drawElements(a,b,c,d)},Hb:function(a,b,c,d,e){D.drawElementsInstanced(a,b,c,d,e)},Yf:function(a,b,c,d,e){D.drawElementsInstanced(a,b,c,d,e)},Vc:function(a,b,c,d,e){D.drawElementsInstanced(a,b,c,d,e)},Wc:function(a,
b,c,d,e){D.drawElementsInstanced(a,b,c,d,e)},Xc:function(a,b,c,d,e){D.drawElementsInstanced(a,b,c,d,e)},Sc:function(a,b,c,d,e,g){D.drawElements(a,d,e,g)},bf:function(a){D.enable(a)},af:function(a){D.enableVertexAttribArray(a)},Ic:function(a){D.endQuery(a)},lg:function(a){D.Jg.endQueryEXT(a)},oc:function(){D.endTransformFeedback()},Gb:function(a,b){return(a=D.fenceSync(a,b))?(b=ec($b),a.name=b,$b[b]=a,b):0},$e:function(){D.finish()},_e:function(){D.flush()},Ze:function(a,b,c,d){D.framebufferRenderbuffer(a,
b,c,Xb[d])},Ye:function(a,b,c,d,e){D.framebufferTexture2D(a,b,c,Yb[d],e)},vc:function(a,b,c,d,e){D.framebufferTextureLayer(a,b,Yb[c],d,e)},We:function(a){D.frontFace(a)},Ve:function(a,b){U(a,b,"createBuffer",G)},Te:function(a,b){U(a,b,"createFramebuffer",Wb)},Mc:function(a,b){U(a,b,"createQuery",K)},pg:function(a,b){for(var c=0;c<a;c++){var d=D.Jg.createQueryEXT();if(!d){for(M(1282);c<a;)w[b+4*c++>>2]=0;break}var e=ec(K);d.name=e;K[e]=d;w[b+4*c>>2]=e}},Se:function(a,b){U(a,b,"createRenderbuffer",
Xb)},xb:function(a,b){U(a,b,"createSampler",L)},Re:function(a,b){U(a,b,"createTexture",Yb)},kb:function(a,b){U(a,b,"createTransformFeedback",Zb)},sc:function(a,b){U(a,b,"createVertexArray",J)},bg:function(a,b){U(a,b,"createVertexArray",J)},Ue:function(a){D.generateMipmap(a)},Qe:function(a,b,c,d,e,g,h){Zc("getActiveAttrib",a,b,c,d,e,g,h)},Pe:function(a,b,c,d,e,g,h){Zc("getActiveUniform",a,b,c,d,e,g,h)},Kb:function(a,b,c,d,e){a=H[a];if(a=D.getActiveUniformBlockName(a,b))e&&0<c?(c=t(a,e,c),d&&(w[d>>
2]=c)):d&&(w[d>>2]=0)},Lb:function(a,b,c,d){if(d)if(a=H[a],35393==c)c=D.getActiveUniformBlockName(a,b),w[d>>2]=c.length+1;else{if(a=D.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)w[d+4*c>>2]=a[c];else w[d>>2]=a}else M(1281)},Nb:function(a,b,c,d,e){if(e)if(0<b&&0==c)M(1281);else{a=H[a];for(var g=[],h=0;h<b;h++)g.push(w[c+4*h>>2]);if(a=D.getActiveUniforms(a,g,d))for(b=a.length,h=0;h<b;h++)w[e+4*h>>2]=a[h]}else M(1281)},Oe:function(a,b,c,d){a=D.getAttachedShaders(H[a]);
var e=a.length;e>b&&(e=b);w[c>>2]=e;for(b=0;b<e;++b)w[d+4*b>>2]=I.indexOf(a[b])},Ne:function(a,b){return D.getAttribLocation(H[a],p(b))},Le:function(a,b){ad(a,b,4)},yb:function(a,b,c){c?$c(c,D.getBufferParameter(a,b)):M(1281)},Ke:function(a,b,c){c?w[c>>2]=D.getBufferParameter(a,b):M(1281)},Je:function(){var a=D.getError()||dc;dc=0;return a},Ie:function(a,b){ad(a,b,2)},bc:function(a,b){return D.getFragDataLocation(H[a],p(b))},He:function(a,b,c,d){a=D.getFramebufferAttachmentParameter(a,b,c);if(a instanceof
WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;w[d>>2]=a},zb:function(a,b,c){bd(a,b,c,1)},Bb:function(a,b){ad(a,b,1)},qc:function(a,b,c){bd(a,b,c,0)},Ge:function(a,b){ad(a,b,0)},$a:function(a,b,c,d,e){if(0>d)M(1281);else if(e){if(a=D.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)w[e+4*b>>2]=a[b]}else M(1281)},gb:function(){M(1282)},Ee:function(a,b,c,d){a=D.getProgramInfoLog(H[a]);null===a&&(a="(unknown error)");b=0<b&&d?t(a,d,b):0;c&&(w[c>>2]=b)},Fe:function(a,b,
c){if(c)if(a>=Vb)M(1281);else if(a=H[a],35716==b)a=D.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.Xg)for(b=0;b<D.getProgramParameter(a,35718);++b)a.Xg=Math.max(a.Xg,D.getActiveUniform(a,b).name.length+1);w[c>>2]=a.Xg}else if(35722==b){if(!a.Vg)for(b=0;b<D.getProgramParameter(a,35721);++b)a.Vg=Math.max(a.Vg,D.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.Vg}else if(35381==b){if(!a.Wg)for(b=0;b<D.getProgramParameter(a,35382);++b)a.Wg=Math.max(a.Wg,
D.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.Wg}else w[c>>2]=D.getProgramParameter(a,b);else M(1281)},fg:function(a,b,c){if(c){a=K[a];b=2>N.version?D.Jg.getQueryObjectEXT(a,b):D.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;$c(c,d)}else M(1281)},hg:function(a,b,c){if(c){a=D.Jg.getQueryObjectEXT(K[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else M(1281)},eg:function(a,b,c){if(c){a=K[a];b=2>N.version?D.Jg.getQueryObjectEXT(a,b):D.getQueryParameter(a,b);var d;"boolean"==
typeof b?d=b?1:0:d=b;$c(c,d)}else M(1281)},Gc:function(a,b,c){if(c){a=D.getQueryParameter(K[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else M(1281)},gg:function(a,b,c){if(c){a=D.Jg.getQueryObjectEXT(K[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else M(1281)},Hc:function(a,b,c){c?w[c>>2]=D.getQuery(a,b):M(1281)},jg:function(a,b,c){c?w[c>>2]=D.Jg.getQueryEXT(a,b):M(1281)},De:function(a,b,c){c?w[c>>2]=D.getRenderbufferParameter(a,b):M(1281)},ob:function(a,b,c){c?y[c>>2]=D.getSamplerParameter(L[a],
b):M(1281)},pb:function(a,b,c){c?w[c>>2]=D.getSamplerParameter(L[a],b):M(1281)},ze:function(a,b,c,d){a=D.getShaderInfoLog(I[a]);null===a&&(a="(unknown error)");b=0<b&&d?t(a,d,b):0;c&&(w[c>>2]=b)},ye:function(a,b,c,d){a=D.getShaderPrecisionFormat(a,b);w[c>>2]=a.rangeMin;w[c+4>>2]=a.rangeMax;w[d>>2]=a.precision},xe:function(a,b,c,d){if(a=D.getShaderSource(I[a]))b=0<b&&d?t(a,d,b):0,c&&(w[c>>2]=b)},Ce:function(a,b,c){c?35716==b?(a=D.getShaderInfoLog(I[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+
1:0):35720==b?(a=D.getShaderSource(I[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=D.getShaderParameter(I[a],b):M(1281)},we:function(a){var b=ac[a];if(!b){switch(a){case 7939:b=D.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=cd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=D.getParameter(a))||M(1280);b=b&&cd(b);break;case 7938:b=D.getParameter(7938);b=2<=N.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=cd(b);break;case 35724:b=D.getParameter(35724);
var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=cd(b);break;default:M(1280)}ac[a]=b}return b},Qb:function(a,b){if(2>N.version)return M(1282),0;var c=bc[a];if(c)return 0>b||b>=c.length?(M(1281),0):c[b];switch(a){case 7939:return c=D.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return cd(d)}),c=bc[a]=c,0>b||b>=c.length?(M(1281),0):c[b];default:return M(1280),
0}},Ab:function(a,b,c,d,e){0>c?M(1281):e?(a=D.getSyncParameter($b[a],b),null!==a&&(w[e>>2]=a,d&&(w[d>>2]=1))):M(1281)},ve:function(a,b,c){c?y[c>>2]=D.getTexParameter(a,b):M(1281)},ue:function(a,b,c){c?w[c>>2]=D.getTexParameter(a,b):M(1281)},kc:function(a,b,c,d,e,g,h){a=H[a];if(a=D.getTransformFeedbackVarying(a,b))h&&0<c?(c=t(a.name,h,c),d&&(w[d>>2]=c)):d&&(w[d>>2]=0),e&&(w[e>>2]=a.size),g&&(w[g>>2]=a.type)},Mb:function(a,b){return D.getUniformBlockIndex(H[a],p(b))},Ob:function(a,b,c,d){if(d)if(0<
b&&(0==c||0==d))M(1281);else{a=H[a];for(var e=[],g=0;g<b;g++)e.push(p(w[c+4*g>>2]));if(a=D.getUniformIndices(a,e))for(b=a.length,g=0;g<b;g++)w[d+4*g>>2]=a[g]}else M(1281)},re:function(a,b){b=p(b);if(a=H[a]){ed(a);var c=a.Sg,d=0,e=b,g=dd(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.fh[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||D.getUniformLocation(a,b)))return d}else M(1281);return-1},te:function(a,b,c){fd(a,b,c,2)},se:function(a,b,c){fd(a,b,c,0)},cc:function(a,b,c){fd(a,b,c,0)},ic:function(a,
b,c){gd(a,b,c,0)},hc:function(a,b,c){gd(a,b,c,0)},ne:function(a,b,c){c?w[c>>2]=D.getVertexAttribOffset(a,b):M(1281)},qe:function(a,b,c){gd(a,b,c,2)},oe:function(a,b,c){gd(a,b,c,5)},me:function(a,b){D.hint(a,b)},db:function(a,b,c){for(var d=Yc[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];D.invalidateFramebuffer(a,d)},cb:function(a,b,c,d,e,g,h){for(var l=Yc[b],n=0;n<b;n++)l[n]=w[c+4*n>>2];D.invalidateSubFramebuffer(a,l,d,e,g,h)},le:function(a){return(a=G[a])?D.isBuffer(a):0},ke:function(a){return D.isEnabled(a)},
je:function(a){return(a=Wb[a])?D.isFramebuffer(a):0},ie:function(a){return(a=H[a])?D.isProgram(a):0},Kc:function(a){return(a=K[a])?D.isQuery(a):0},ng:function(a){return(a=K[a])?D.Jg.isQueryEXT(a):0},he:function(a){return(a=Xb[a])?D.isRenderbuffer(a):0},vb:function(a){return(a=L[a])?D.isSampler(a):0},ge:function(a){return(a=I[a])?D.isShader(a):0},Fb:function(a){return D.isSync($b[a])},fe:function(a){return(a=Yb[a])?D.isTexture(a):0},jb:function(a){return D.isTransformFeedback(Zb[a])},rc:function(a){return(a=
J[a])?D.isVertexArray(a):0},ag:function(a){return(a=J[a])?D.isVertexArray(a):0},de:function(a){D.lineWidth(a)},ce:function(a){a=H[a];D.linkProgram(a);a.Sg=0;a.fh={}},ib:function(){D.pauseTransformFeedback()},be:function(a,b){3317==a&&(cc=b);D.pixelStorei(a,b)},ae:function(a,b){D.polygonOffset(a,b)},fb:function(){M(1280)},eb:function(){M(1280)},kg:function(a,b){D.Jg.queryCounterEXT(K[a],b)},Tc:function(a){D.readBuffer(a)},$d:function(a,b,c,d,e,g,h){if(2<=N.version)if(D.Tg)D.readPixels(a,b,c,d,e,g,
h);else{var l=hd(g);D.readPixels(a,b,c,d,e,g,l,h>>jd(l))}else(h=kd(g,e,c,d,h))?D.readPixels(a,b,c,d,e,g,h):M(1280)},_d:function(){},Zd:function(a,b,c,d){D.renderbufferStorage(a,b,c,d)},wc:function(a,b,c,d,e){D.renderbufferStorageMultisample(a,b,c,d,e)},hb:function(){D.resumeTransformFeedback()},Yd:function(a,b){D.sampleCoverage(a,!!b)},rb:function(a,b,c){D.samplerParameterf(L[a],b,c)},qb:function(a,b,c){D.samplerParameterf(L[a],b,y[c>>2])},tb:function(a,b,c){D.samplerParameteri(L[a],b,c)},sb:function(a,
b,c){D.samplerParameteri(L[a],b,w[c>>2])},Xd:function(a,b,c,d){D.scissor(a,b,c,d)},Wd:function(){M(1280)},Ud:function(a,b,c,d){b=fc(b,c,d);D.shaderSource(I[a],b)},Td:function(a,b,c){D.stencilFunc(a,b,c)},Sd:function(a,b,c,d){D.stencilFuncSeparate(a,b,c,d)},Rd:function(a){D.stencilMask(a)},Qd:function(a,b){D.stencilMaskSeparate(a,b)},Pd:function(a,b,c){D.stencilOp(a,b,c)},Od:function(a,b,c,d){D.stencilOpSeparate(a,b,c,d)},Nd:function(a,b,c,d,e,g,h,l,n){if(2<=N.version)if(D.Hg)D.texImage2D(a,b,c,d,
e,g,h,l,n);else if(n){var q=hd(l);D.texImage2D(a,b,c,d,e,g,h,l,q,n>>jd(q))}else D.texImage2D(a,b,c,d,e,g,h,l,null);else D.texImage2D(a,b,c,d,e,g,h,l,n?kd(l,h,d,e,n):null)},Rc:function(a,b,c,d,e,g,h,l,n,q){if(D.Hg)D.texImage3D(a,b,c,d,e,g,h,l,n,q);else if(q){var v=hd(n);D.texImage3D(a,b,c,d,e,g,h,l,n,v,q>>jd(v))}else D.texImage3D(a,b,c,d,e,g,h,l,n,null)},Md:function(a,b,c){D.texParameterf(a,b,c)},Ld:function(a,b,c){D.texParameterf(a,b,y[c>>2])},Jd:function(a,b,c){D.texParameteri(a,b,c)},Id:function(a,
b,c){D.texParameteri(a,b,w[c>>2])},bb:function(a,b,c,d,e){D.texStorage2D(a,b,c,d,e)},ab:function(a,b,c,d,e,g){D.texStorage3D(a,b,c,d,e,g)},Hd:function(a,b,c,d,e,g,h,l,n){if(2<=N.version)if(D.Hg)D.texSubImage2D(a,b,c,d,e,g,h,l,n);else if(n){var q=hd(l);D.texSubImage2D(a,b,c,d,e,g,h,l,q,n>>jd(q))}else D.texSubImage2D(a,b,c,d,e,g,h,l,null);else q=null,n&&(q=kd(l,h,e,g,n)),D.texSubImage2D(a,b,c,d,e,g,h,l,q)},Qc:function(a,b,c,d,e,g,h,l,n,q,v){if(D.Hg)D.texSubImage3D(a,b,c,d,e,g,h,l,n,q,v);else if(v){var z=
hd(q);D.texSubImage3D(a,b,c,d,e,g,h,l,n,q,z,v>>jd(z))}else D.texSubImage3D(a,b,c,d,e,g,h,l,n,q,null)},lc:function(a,b,c,d){a=H[a];for(var e=[],g=0;g<b;g++)e.push(p(w[c+4*g>>2]));D.transformFeedbackVaryings(a,e,d)},Gd:function(a,b){D.uniform1f(V(a),b)},Fd:function(a,b,c){if(2<=N.version)b&&D.uniform1fv(V(a),y,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);D.uniform1fv(V(a),d)}},Ed:function(a,b){D.uniform1i(V(a),b)},Dd:function(a,b,c){if(2<=N.version)b&&
D.uniform1iv(V(a),w,c>>2,b);else{if(288>=b)for(var d=ld[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);D.uniform1iv(V(a),d)}},ac:function(a,b){D.uniform1ui(V(a),b)},Yb:function(a,b,c){b&&D.uniform1uiv(V(a),x,c>>2,b)},Cd:function(a,b,c){D.uniform2f(V(a),b,c)},Bd:function(a,b,c){if(2<=N.version)b&&D.uniform2fv(V(a),y,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);D.uniform2fv(V(a),d)}},Ad:function(a,
b,c){D.uniform2i(V(a),b,c)},yd:function(a,b,c){if(2<=N.version)b&&D.uniform2iv(V(a),w,c>>2,2*b);else{if(144>=b)for(var d=ld[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);D.uniform2iv(V(a),d)}},$b:function(a,b,c){D.uniform2ui(V(a),b,c)},Xb:function(a,b,c){b&&D.uniform2uiv(V(a),x,c>>2,2*b)},xd:function(a,b,c,d){D.uniform3f(V(a),b,c,d)},wd:function(a,b,c){if(2<=N.version)b&&D.uniform3fv(V(a),y,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=
y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);D.uniform3fv(V(a),d)}},vd:function(a,b,c,d){D.uniform3i(V(a),b,c,d)},ud:function(a,b,c){if(2<=N.version)b&&D.uniform3iv(V(a),w,c>>2,3*b);else{if(96>=b)for(var d=ld[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);D.uniform3iv(V(a),d)}},_b:function(a,b,c,d){D.uniform3ui(V(a),b,c,d)},Wb:function(a,b,c){b&&D.uniform3uiv(V(a),x,c>>2,3*b)},td:function(a,
b,c,d,e){D.uniform4f(V(a),b,c,d,e)},sd:function(a,b,c){if(2<=N.version)b&&D.uniform4fv(V(a),y,c>>2,4*b);else{if(72>=b){var d=X[4*b-1],e=y;c>>=2;for(var g=0;g<4*b;g+=4){var h=c+g;d[g]=e[h];d[g+1]=e[h+1];d[g+2]=e[h+2];d[g+3]=e[h+3]}}else d=y.subarray(c>>2,c+16*b>>2);D.uniform4fv(V(a),d)}},rd:function(a,b,c,d,e){D.uniform4i(V(a),b,c,d,e)},qd:function(a,b,c){if(2<=N.version)b&&D.uniform4iv(V(a),w,c>>2,4*b);else{if(72>=b)for(var d=ld[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=
w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);D.uniform4iv(V(a),d)}},Zb:function(a,b,c,d,e){D.uniform4ui(V(a),b,c,d,e)},Vb:function(a,b,c){b&&D.uniform4uiv(V(a),x,c>>2,4*b)},Jb:function(a,b,c){a=H[a];D.uniformBlockBinding(a,b,c)},pd:function(a,b,c,d){if(2<=N.version)b&&D.uniformMatrix2fv(V(a),!!c,y,d>>2,4*b);else{if(72>=b)for(var e=X[4*b-1],g=0;g<4*b;g+=4)e[g]=y[d+4*g>>2],e[g+1]=y[d+(4*g+4)>>2],e[g+2]=y[d+(4*g+8)>>2],e[g+3]=y[d+(4*g+12)>>2];else e=y.subarray(d>>2,d+16*
b>>2);D.uniformMatrix2fv(V(a),!!c,e)}},Ec:function(a,b,c,d){b&&D.uniformMatrix2x3fv(V(a),!!c,y,d>>2,6*b)},Cc:function(a,b,c,d){b&&D.uniformMatrix2x4fv(V(a),!!c,y,d>>2,8*b)},nd:function(a,b,c,d){if(2<=N.version)b&&D.uniformMatrix3fv(V(a),!!c,y,d>>2,9*b);else{if(32>=b)for(var e=X[9*b-1],g=0;g<9*b;g+=9)e[g]=y[d+4*g>>2],e[g+1]=y[d+(4*g+4)>>2],e[g+2]=y[d+(4*g+8)>>2],e[g+3]=y[d+(4*g+12)>>2],e[g+4]=y[d+(4*g+16)>>2],e[g+5]=y[d+(4*g+20)>>2],e[g+6]=y[d+(4*g+24)>>2],e[g+7]=y[d+(4*g+28)>>2],e[g+8]=y[d+(4*g+32)>>
2];else e=y.subarray(d>>2,d+36*b>>2);D.uniformMatrix3fv(V(a),!!c,e)}},Dc:function(a,b,c,d){b&&D.uniformMatrix3x2fv(V(a),!!c,y,d>>2,6*b)},zc:function(a,b,c,d){b&&D.uniformMatrix3x4fv(V(a),!!c,y,d>>2,12*b)},md:function(a,b,c,d){if(2<=N.version)b&&D.uniformMatrix4fv(V(a),!!c,y,d>>2,16*b);else{if(18>=b){var e=X[16*b-1],g=y;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+h;e[h]=g[l];e[h+1]=g[l+1];e[h+2]=g[l+2];e[h+3]=g[l+3];e[h+4]=g[l+4];e[h+5]=g[l+5];e[h+6]=g[l+6];e[h+7]=g[l+7];e[h+8]=g[l+8];e[h+9]=g[l+9];e[h+
10]=g[l+10];e[h+11]=g[l+11];e[h+12]=g[l+12];e[h+13]=g[l+13];e[h+14]=g[l+14];e[h+15]=g[l+15]}}else e=y.subarray(d>>2,d+64*b>>2);D.uniformMatrix4fv(V(a),!!c,e)}},Ac:function(a,b,c,d){b&&D.uniformMatrix4x2fv(V(a),!!c,y,d>>2,8*b)},yc:function(a,b,c,d){b&&D.uniformMatrix4x3fv(V(a),!!c,y,d>>2,12*b)},ld:function(a){a=H[a];D.useProgram(a);D.nh=a},kd:function(a){D.validateProgram(H[a])},jd:function(a,b){D.vertexAttrib1f(a,b)},id:function(a,b){D.vertexAttrib1f(a,y[b>>2])},hd:function(a,b,c){D.vertexAttrib2f(a,
b,c)},gd:function(a,b){D.vertexAttrib2f(a,y[b>>2],y[b+4>>2])},fd:function(a,b,c,d){D.vertexAttrib3f(a,b,c,d)},ed:function(a,b){D.vertexAttrib3f(a,y[b>>2],y[b+4>>2],y[b+8>>2])},dd:function(a,b,c,d,e){D.vertexAttrib4f(a,b,c,d,e)},cd:function(a,b){D.vertexAttrib4f(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},nb:function(a,b){D.vertexAttribDivisor(a,b)},Xf:function(a,b){D.vertexAttribDivisor(a,b)},_c:function(a,b){D.vertexAttribDivisor(a,b)},$c:function(a,b){D.vertexAttribDivisor(a,b)},_a:function(a,b){D.vertexAttribDivisor(a,
b)},gc:function(a,b,c,d,e){D.vertexAttribI4i(a,b,c,d,e)},ec:function(a,b){D.vertexAttribI4i(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},fc:function(a,b,c,d,e){D.vertexAttribI4ui(a,b,c,d,e)},dc:function(a,b){D.vertexAttribI4ui(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},jc:function(a,b,c,d,e){D.vertexAttribIPointer(a,b,c,d,e)},bd:function(a,b,c,d,e,g){D.vertexAttribPointer(a,b,c,!!d,e,g)},ad:function(a,b,c,d){D.viewport(a,b,c,d)},Cb:function(a,b,c,d){D.waitSync($b[a],b,(c>>>0)+4294967296*d)},I:function(){return 0},
Ta:function(a,b,c){r.copyWithin(a,b,b+c)},La:function(a,b,c){return md(a,{ih:w[c>>2],gh:w[c+4>>2],Dh:w[c+8>>2],Ah:b,$g:w[c+12>>2],lh:w[c+16>>2]})},ja:function(a,b){a=S(a);return a?a.requestPointerLock?oc&&uc.Rg?Wc(a):b?(rc(Wc,2,[a]),1):-2:-1:-4},Qa:function(a){var b=r.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,g=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var h=ja.buffer;try{ja.grow(g.call(e,2147483648,d)-h.byteLength+
65535>>>16);sa();var l=1;break a}catch(n){}l=void 0}if(l)return!0}return!1},Bc:function(){return(zc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},Q:function(a,b,c){if("undefined"==typeof onbeforeunload)return-1;if(1!==c)return-5;nd(a,b);return 0},$:function(a,b,c,d){od(a,b,c,d,12,"blur");return 0},r:Pc,E:function(a,b,c){a=S(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},ba:function(a,b,c,d){od(a,b,c,d,13,
"focus");return 0},T:function(a,b,c,d){if(!xc())return-1;a=S(a);if(!a)return-4;pd(a,b,c,d,"fullscreenchange");pd(a,b,c,d,"webkitfullscreenchange");return 0},u:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;qd(a,b,c,26,"gamepadconnected");return 0},t:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;qd(a,b,c,27,"gamepaddisconnected");return 0},W:function(a,b,c,d){rd(a,b,c,d,2,"keydown");return 0},U:function(a,b,c,d){rd(a,b,c,d,1,"keypress");
return 0},V:function(a,b,c,d){rd(a,b,c,d,3,"keyup");return 0},za:function(a,b,c){a=T(a);cb(a,b,c)},ha:function(a,b,c,d){td(a,b,c,d,5,"mousedown");return 0},fa:function(a,b,c,d){td(a,b,c,d,33,"mouseenter");return 0},ea:function(a,b,c,d){td(a,b,c,d,34,"mouseleave");return 0},ia:function(a,b,c,d){td(a,b,c,d,8,"mousemove");return 0},ga:function(a,b,c,d){td(a,b,c,d,6,"mouseup");return 0},B:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Zg||document.body.vh||
document.body.uh))return-1;a=S(a);if(!a)return-4;ud(a,b,c,d,"pointerlockchange");ud(a,b,c,d,"mozpointerlockchange");ud(a,b,c,d,"webkitpointerlockchange");ud(a,b,c,d,"mspointerlockchange");return 0},S:function(a,b,c,d){vd(a,b,c,d);return 0},X:function(a,b,c,d){wd(a,b,c,d,25,"touchcancel");return 0},Z:function(a,b,c,d){wd(a,b,c,d,23,"touchend");return 0},Y:function(a,b,c,d){wd(a,b,c,d,24,"touchmove");return 0},_:function(a,b,c,d){wd(a,b,c,d,22,"touchstart");return 0},R:function(a,b,c){xd(a,b,c);return 0},
da:function(a,b,c,d){a=S(a);return"undefined"!=typeof a.onwheel?(yd(a,b,c,d),0):-1},Ma:function(a){fa(p(a))},H:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},M:function(a,b){b>>=2;b={alpha:!!w[b],depth:!!w[b+1],stencil:!!w[b+2],antialias:!!w[b+3],premultipliedAlpha:!!w[b+4],preserveDrawingBuffer:!!w[b+5],powerPreference:zd[w[b+6]],failIfMajorPerformanceCaveat:!!w[b+7],ah:w[b+8],Ih:w[b+9],oh:w[b+10],Ch:w[b+11],Yh:w[b+
12],Zh:w[b+13]};a=S(a);return!a||b.Ch?0:Ab(a,b)},Ca:function(a){a>>=2;for(var b=0;14>b;++b)w[a+b]=0;w[a]=w[a+1]=w[a+3]=w[a+4]=w[a+8]=w[a+10]=1},Ba:function(a){return Cb(a)?0:-5},xa:function(a){if("undefined"==typeof WebSocket)return-1;if(!a)return-5;var b=a>>2;a=p(w[b]);a=(b=w[b+1])?new WebSocket(a,p(b).split(",")):new WebSocket(a);a.binaryType="arraybuffer";b=Ad.length;Ad[b]=a;return b},m:function(a,b,c){a=Ad[a];if(!a)return-3;a.send(r.subarray(b,b+c));return 0},K:function(a,b){a=Ad[a];if(!a)return-3;
b=p(b);a.send(b);return 0},ua:function(a,b,c){Y||(Y=B(1024));var d=Ad[a];if(!d)return-3;d.onclose=function(e){x[Y>>2]=a;x[Y+4>>2]=e.wasClean;x[Y+8>>2]=e.code;t(e.reason,Y+10,512);T(c)(0,Y,b)};return 0},va:function(a,b,c){Y||(Y=B(1024));var d=Ad[a];if(!d)return-3;d.onerror=function(){x[Y>>2]=a;T(c)(0,Y,b)};return 0},wa:function(a,b,c){Y||(Y=B(1024));var d=Ad[a];if(!d)return-3;d.onmessage=function(e){x[Y>>2]=a;if("string"==typeof e.data){var g=pa(e.data)+1,h=B(g);t(e.data,h,g);x[Y+12>>2]=1}else g=e.data.byteLength,
h=B(g),u.set(new Uint8Array(e.data),h),x[Y+12>>2]=0;x[Y+4>>2]=h;x[Y+8>>2]=g;T(c)(0,Y,b);Nd(h)};return 0},ta:function(a,b,c){Y||(Y=B(1024));var d=Ad[a];if(!d)return-3;d.onopen=function(){x[Y>>2]=a;T(c)(0,Y,b)};return 0},Ra:function(a,b){var c=0;Cd().forEach(function(d,e){var g=b+c;e=x[a+4*e>>2]=g;for(g=0;g<d.length;++g)u[e++>>0]=d.charCodeAt(g);u[e>>0]=0;c+=d.length+1});return 0},Sa:function(a,b){var c=Cd();x[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});x[b>>2]=d;return 0},O:lb,aa:function(){return 52},
Va:function(){return 52},Pa:function(){return 70},Ua:function(a,b,c,d){for(var e=0,g=0;g<c;g++){var h=x[b>>2],l=x[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=r[h+n],v=Jd[a];0===q||10===q?((1===a?ha:k)(na(v,0)),v.length=0):v.push(q)}e+=l}x[d>>2]=e;return 0},ya:function(){return cd(location.hash.replace("#",""))},la:function(a,b){D.attachShader(H[a],I[b])},d:function(a,b){35051==a?D.Tg=b:35052==a&&(D.Hg=b);D.bindBuffer(a,G[b])},h:function(a,b){D.bindTexture(a,Yb[b])},b:function(a){D.bindVertexArray(J[a])},
Ia:function(a,b){D.blendFunc(a,b)},i:function(a,b,c,d){2<=N.version?c&&b?D.bufferData(a,r,d,c,b):D.bufferData(a,b,d):D.bufferData(a,c?r.subarray(c,c+b):b,d)},e:function(a,b,c,d){2<=N.version?c&&D.bufferSubData(a,b,r,d,c):D.bufferSubData(a,b,r.subarray(d,d+c))},P:function(a){D.clear(a)},Ga:function(a,b,c,d){D.clearColor(a,b,c,d)},N:function(a,b,c,d){D.colorMask(!!a,!!b,!!c,!!d)},na:function(a){D.compileShader(I[a])},sg:function(){var a=ec(H),b=D.createProgram();b.name=a;b.Xg=b.Vg=b.Wg=0;b.eh=1;H[a]=
b;return a},pa:function(a){var b=ec(I);I[b]=D.createShader(a);return b},sa:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=G[d];e&&(D.deleteBuffer(e),e.name=0,G[d]=null,d==D.Tg&&(D.Tg=0),d==D.Hg&&(D.Hg=0))}},ra:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];D.deleteVertexArray(J[d]);J[d]=null}},Ja:function(a){D.depthFunc(a)},g:function(a,b,c){D.drawArrays(a,b,c)},A:function(a){D.enable(a)},p:function(a){D.enableVertexAttribArray(a)},w:function(a,b){U(a,b,"createBuffer",G)},G:function(a,
b){U(a,b,"createTexture",Yb)},x:function(a,b){U(a,b,"createVertexArray",J)},ma:function(a,b,c,d){a=D.getShaderInfoLog(I[a]);null===a&&(a="(unknown error)");b=0<b&&d?t(a,d,b):0;c&&(w[c>>2]=b)},v:function(a,b,c){c?35716==b?(a=D.getShaderInfoLog(I[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=D.getShaderSource(I[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=D.getShaderParameter(I[a],b):M(1281)},n:function(a,b){b=p(b);if(a=H[a]){ed(a);var c=a.Sg,d=0,e=b,g=dd(b);0<g&&(d=parseInt(b.slice(g+
1))>>>0,e=b.slice(0,g));if((e=a.fh[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||D.getUniformLocation(a,b)))return d}else M(1281);return-1},rg:function(a){a=H[a];D.linkProgram(a);a.Sg=0;a.fh={}},oa:function(a,b,c,d){b=fc(b,c,d);D.shaderSource(I[a],b)},F:function(a,b,c,d,e,g,h,l,n){if(2<=N.version)if(D.Hg)D.texImage2D(a,b,c,d,e,g,h,l,n);else if(n){var q=hd(l);D.texImage2D(a,b,c,d,e,g,h,l,q,n>>jd(q))}else D.texImage2D(a,b,c,d,e,g,h,l,null);else D.texImage2D(a,b,c,d,e,g,h,l,n?kd(l,h,d,e,n):null)},l:function(a,b,
c){D.texParameteri(a,b,c)},y:function(a,b,c,d,e,g,h,l,n){if(2<=N.version)if(D.Hg)D.texSubImage2D(a,b,c,d,e,g,h,l,n);else if(n){var q=hd(l);D.texSubImage2D(a,b,c,d,e,g,h,l,q,n>>jd(q))}else D.texSubImage2D(a,b,c,d,e,g,h,l,null);else q=null,n&&(q=kd(l,h,e,g,n)),D.texSubImage2D(a,b,c,d,e,g,h,l,q)},z:function(a,b){D.uniform1f(V(a),b)},ka:function(a,b,c){D.uniform2f(V(a),b,c)},Fa:function(a,b,c){if(2<=N.version)b&&D.uniform3fv(V(a),y,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*
e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);D.uniform3fv(V(a),d)}},Ea:function(a,b,c){if(2<=N.version)b&&D.uniform4fv(V(a),y,c>>2,4*b);else{if(72>=b){var d=X[4*b-1],e=y;c>>=2;for(var g=0;g<4*b;g+=4){var h=c+g;d[g]=e[h];d[g+1]=e[h+1];d[g+2]=e[h+2];d[g+3]=e[h+3]}}else d=y.subarray(c>>2,c+16*b>>2);D.uniform4fv(V(a),d)}},k:function(a,b,c,d){if(2<=N.version)b&&D.uniformMatrix4fv(V(a),!!c,y,d>>2,16*b);else{if(18>=b){var e=X[16*b-1],g=y;d>>=2;for(var h=0;h<16*b;h+=
16){var l=d+h;e[h]=g[l];e[h+1]=g[l+1];e[h+2]=g[l+2];e[h+3]=g[l+3];e[h+4]=g[l+4];e[h+5]=g[l+5];e[h+6]=g[l+6];e[h+7]=g[l+7];e[h+8]=g[l+8];e[h+9]=g[l+9];e[h+10]=g[l+10];e[h+11]=g[l+11];e[h+12]=g[l+12];e[h+13]=g[l+13];e[h+14]=g[l+14];e[h+15]=g[l+15]}}else e=y.subarray(d>>2,d+64*b>>2);D.uniformMatrix4fv(V(a),!!c,e)}},Ha:function(a){a=H[a];D.useProgram(a);D.nh=a},tg:function(a,b){D.vertexAttrib1f(a,b)},qa:function(a,b,c){D.vertexAttrib2f(a,b,c)},o:function(a,b,c,d,e,g){D.vertexAttribPointer(a,b,c,!!d,e,
g)},Da:function(a,b,c,d){D.viewport(a,b,c,d)},Aa:function(){return 0},L:function(a){location.hash=p(a)}};
(function(){function a(c){c=c.exports;f.asm=c;ja=f.asm.vg;sa();ta=f.asm.Ag;va.unshift(f.asm.wg);Aa--;f.monitorRunDependencies&&f.monitorRunDependencies(Aa);if(0==Aa&&(null!==Ba&&(clearInterval(Ba),Ba=null),Da)){var d=Da;Da=null;d()}return c}var b={a:Od};Aa++;f.monitorRunDependencies&&f.monitorRunDependencies(Aa);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return k("Module.instantiateWasm callback failed with error: "+c),!1}Ka(b,function(c){a(c.instance)});return{}})();
function B(){return(B=f.asm.xg).apply(null,arguments)}function Nd(){return(Nd=f.asm.yg).apply(null,arguments)}var Pd=f._main=function(){return(Pd=f._main=f.asm.zg).apply(null,arguments)};function mc(){return(mc=f.asm.Bg).apply(null,arguments)}function nc(){return(nc=f.asm.Cg).apply(null,arguments)}function Oc(){return(Oc=f.asm.Dg).apply(null,arguments)}f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.Eg).apply(null,arguments)};
f.dynCall_ji=function(){return(f.dynCall_ji=f.asm.Fg).apply(null,arguments)};f.___start_em_js=99809;f.___stop_em_js=99938;var Qd;Da=function Rd(){Qd||Sd();Qd||(Da=Rd)};function Td(a=[]){var b=Pd;a.unshift(ca);var c=a.length,d=Oc(4*(c+1)),e=d>>2;a.forEach(h=>{var l=w,n=e++,q=pa(h)+1,v=Oc(q);oa(h,u,v,q);l[n]=v});w[e]=0;try{var g=b(c,d);lb(g,!0)}catch(h){kb(h)}}
function Sd(){var a=ba;function b(){if(!Qd&&(Qd=!0,f.calledRun=!0,!ka)){Sa(va);Sa(wa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Ud&&Td(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();ya.unshift(c)}Sa(ya)}}if(!(0<Aa)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)za();Sa(ua);0<Aa||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);
b()},1)):b())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Ud=!0;f.noInitialRun&&(Ud=!1);Sd();
